MultiSafepay/docs

content/payments/methods/banks/bancontact/overview.md, content/payments/methods/banks/giropay/overview.md, content/payments/methods/banks/ideal/overview.md, content/payments/methods/banks/sofort/overview.md, content/payments/methods/banks/trustly/overview.md, content/payments/methods/banks/trustpay/overview.md, content/payments/methods/credit-and-debit-cards/american-express/overview.md, content/payments/methods/credit-and-debit-cards/cartes-bancaires/overview.md, content/payments/methods/credit-and-debit-cards/dankort/overview.md, content/payments/methods/credit-and-debit-cards/mastercard/overview.md, content/payments/methods/credit-and-debit-cards/postepay/overview.md, content/payments/methods/credit-and-debit-cards/visa/overview.md, content/payments/methods/credit-and-debit-cards/vpay/overview.md, content/payments/methods/pay-later/afterpay/overview.md, content/payments/methods/pay-later/betaalpermaand/overview.md, content/payments/methods/pay-later/in3/overview.md, content/payments/methods/pay-later/klarna/_index.md, content/payments/methods/pay-later/klarna/overview.md, content/payments/methods/prepaid-cards/edenred/overview.md, content/payments/methods/prepaid-cards/paysafecard/overview.md, content/payments/methods/wallet/alipay/overview.md, content/payments/methods/wallet/applepay/overview.md, content/payments/methods/wallet/paypal/overview.md, content/payments/methods/wallet/wechatpay/overview.md
=> DOCS-2923: Notice of Klarna changes

content/payments/methods/pay-later/afterpay/overview.md, content/payments/methods/pay-later/e-invoicing/overview.md, content/payments/methods/pay-later/in3/overview.md, content/payments/methods/pay-later/klarna/overview.md, content/payments/methods/pay-later/pay-after-delivery/overview.md, content/payments/methods/pay-later/pay-after-delivery/user-guide/refunds-discounts.md, content/payments/methods/wallet/alipay/overview.md
=> DOCS-2926: Fix pay later refunds links

content/payments/methods/credit-and-debit-cards/american-express/payment-flow.md, content/payments/methods/credit-and-debit-cards/cartes-bancaires/payment-flow.md, content/payments/methods/credit-and-debit-cards/dankort/payment-flow.md, content/payments/methods/credit-and-debit-cards/maestro/payment-flow.md, content/payments/methods/credit-and-debit-cards/mastercard/payment-flow.md, content/payments/methods/credit-and-debit-cards/postepay/payment-flow.md, content/payments/methods/credit-and-debit-cards/visa/payment-flow.md, content/payments/methods/credit-and-debit-cards/vpay/payment-flow.md
=> DOCS-2899: Correct refund and chargeback statuses for credit cards

content/api/orders/payment-component-order.md
=> DOCS-2890: Payment component orders: make customer.ip_address required

content/api/payment_methods/post-order-googlepay.md, content/payments/methods/wallet/googlepay/direct-integration/_index.md
=> Update Google Pay direct integration

content/api/orders/server-to-server-credit-cards.md, content/payments/features/moto/_index.md
=> DOCS-1617: Document S2S MOTO transactions

content/integration/ready-made/magento1/_index.md
=> DOCS-2930: fix magento1 download link

content/developer/api/_index.md, content/developer/api/direct-vs-redirect.md, content/developer/api/google-analytics-tracking.md, content/developer/api/locale-parameter.md, content/developer/api/masking-iban-numbers.md, content/developer/api/notification-url.md, content/developer/api/pagination.md, content/developer/api/redirect-url.md, content/developer/api/xml-api.md, content/integration/checkouts/payment-pages/activating-multisafepay-payment-pages.md
Reverts MultiSafepay/docs#1925
=> Revert "DOCS-1408: Direct vs redirect request diagram"

content/payments/refunds-and-chargebacks/refunds/discounts.md
=> DOCS-2935: Add payment methods to Discounts

content/payments/methods/pay-later/in3/payment-flow.md
=> DOCS-2936: Adjust Shipped status for in3

content/my-account/partner-account/api-onboarding/_index.md, content/my-account/partner-account/api-onboarding/add-bank-accounts.md, content/my-account/partner-account/api-onboarding/add-ubos.md, content/my-account/partner-account/api-onboarding/add-websites.md, content/my-account/partner-account/api-onboarding/create-account.md
=> DOCS-2673: Change authentication method for API onboarding requests

content/my-account/partner-account/api-onboarding/add-bank-accounts.md, content/my-account/partner-account/api-onboarding/add-ubos.md, content/my-account/partner-account/api-onboarding/create-account.md
=> DOCS-2673: minor fixes

content/integration/testing/test-payment-details.md, content/payments/methods/pay-later/klarna/integration-and-testing.md
=> DOCS-2956: add Klarna redirect testing details

.github/mlc_config.json, .github/workflows/markdown-link-check-daily.yml, .github/workflows/markdown-link-check.yml
=> DOCS-0000: turn on verbose mode for markdown link checker

.github/mlc_config.json
=> DOCS-0000: fix JSON error in markdown-link-check action

content/integration/ready-made/prestashop-1-6/faq/skipping-extra-confirmation-page.md
=> DOCS-2972: Fix PrestaShop download link

content/api/orders/create-direct-order.md, content/api/orders/create-redirect-order.md, content/api/other_requests/specify-vouchers.md, content/developer/api/gateway-ids.md, content/developer/general/generic-gateways.md, content/integration/checkouts/payment-components/previous-release/previous-release-2.md, content/integration/checkouts/payment-components/previous-release/previous-release-3.md, content/integration/checkouts/payment-components/single/single-2.md, content/integration/ready-made/craftcommerce/faq/configuring-generic-gateways.md, content/integration/ready-made/drupal8/faq/configuring-generic-gateways.md, content/integration/ready-made/magento1/faq/configuring-generic-gateways.md, content/integration/ready-made/magento2/faq/configuring-generic-gateways.md, content/integration/ready-made/odoo/faq/configuring-generic-gateways.md, content/integration/ready-made/opencart/faq/configuring-generic-gateways.md, content/integration/ready-made/prestashop-1-7/faq/configuring-generic-gateways.md, content/integration/ready-made/shopware5/faq/configuring-generic-gateways.md, content/integration/ready-made/shopware6/faq/configuring-generic-gateways.md, content/integration/ready-made/woocommerce/faq/configuring-generic-gateways.md, content/payments/methods/prepaid-cards/gift-cards/user-guide/creating-custom-gift-cards.md
=> DOCS-2977: Change gateway code to identifier

content/integration/ready-made/magento1/_index.md
=> DOCS-2937: Fix Magento 1 changelog button

content/integration/ready-made/woocommerce/_index.md
Release of 4.12.0 WooCommerce plugin
=> Release of 4.12.0 WooCommerce plugin

content/payments/methods/pay-later/klarna/user-guide/handling-disputes.md
=> DOCS-2976: Document signing up for Klarna Disputes app

.github/mlc_config.json, .github/workflows/markdown-link-check.yml
=> DOCS-0000: make markdown-link-check wait for netlify preview on PR

.github/workflows/markdown-link-check-daily.yml
=> DOCS-0000: change DEPLOYMENT_URL in markdown-link-check-daily.yml

.github/workflows/markdown-link-check-daily.yml
=> DOCS-0000: run markdown link check hourly

.github/workflows/markdown-link-check.yml
=> DOCS-0000: update markdown-link-check.yml to wait for commit

.github/mlc_config.json
=> DOCS-2973: add additional regex ignore patterns

content/payments/methods/credit-and-debit-cards/american-express/payment-flow.md, content/payments/methods/credit-and-debit-cards/cartes-bancaires/payment-flow.md, content/payments/methods/credit-and-debit-cards/dankort/payment-flow.md, content/payments/methods/credit-and-debit-cards/maestro/payment-flow.md, content/payments/methods/credit-and-debit-cards/mastercard/payment-flow.md, content/payments/methods/credit-and-debit-cards/postepay/payment-flow.md, content/payments/methods/credit-and-debit-cards/visa/payment-flow.md, content/payments/methods/credit-and-debit-cards/vpay/payment-flow.md
=> DOCS-2983: Fix credit card uncaptured period

content/integration/checkouts/payment-link/about-payment-links.md
=> DOCS-2982: Fix payment link supported methods

content/payments/methods/wallet/googlepay/integration-and-testing.md
=> DOCS-2984: Clarification on GooglePay ready made integrations

content/accounting/integrations/Yuki/_index.md
=> DOCS-0000: fix yuki freshdesk article dead link

content/payments/methods/banks/sofort/payment-flow.md
=> DOCS-2967: Clarify Sofort amount rules

content/integration/ready-made/ccvshop/_index.md, content/integration/ready-made/craftcommerce/_index.md, content/integration/ready-made/cs-cart/_index.md, content/integration/ready-made/drupal7/_index.md, content/integration/ready-made/drupal8/_index.md, content/integration/ready-made/ecwid/_index.md, content/integration/ready-made/lightspeed_app/_index.md, content/integration/ready-made/logivert/_index.md, content/integration/ready-made/magento1/_index.md, content/integration/ready-made/magento2/_index.md, content/integration/ready-made/mijnwebwinkel/_index.md, content/integration/ready-made/myshop/_index.md, content/integration/ready-made/odoo/_index.md, content/integration/ready-made/opencart/_index.md, content/integration/ready-made/oscommerce/_index.md, content/integration/ready-made/prestashop-1-6/_index.md, content/integration/ready-made/prestashop-1-7/_index.md, content/integration/ready-made/shopify/_index.md, content/integration/ready-made/shopware5/_index.md, content/integration/ready-made/shopware6/_index.md, content/integration/ready-made/virtuemart/_index.md, content/integration/ready-made/woocommerce/_index.md, content/integration/ready-made/x-cart/_index.md, content/integration/ready-made/zencart/_index.md
=> DOCS-2991: Add note about PrestaShop backend orders

content/integration/ready-made/prestashop-1-7/faq/activating-payment-components.md
=> DOCS-2997: Add Payment Component to PrestaShop 1.7

content/payments/methods/pay-later/afterpay/payment-flow.md
=> DOCS-2999: Update AfterPay payment flow

.github/mlc_config.json
=> DOCS-0000: add drupal link to ignore patterns

content/api/payment_methods/post-order-santander.md, content/developer/api/xml-api.md
=> DOCS-0000: resolve typos

content/api/accounts/charges.md, content/api/accounts/payouts.md, content/api/orders/create-direct-order.md, content/api/orders/flexible-3d-disabled-direct.md, content/api/orders/flexible-3d-enabled-direct.md, content/api/orders/get-order-details.md, content/api/orders/order-status-authorised-transaction.md, content/api/orders/order-status-captured-transaction.md, content/api/orders/payment-component-order.md, content/api/orders/refund-order.md, content/api/orders/zero-authorization-order-status.md, content/api/payment_methods/post-order-banktrans.md, content/api/payment_methods/post-order-klarna.md, content/api/payment_methods/post-order-payafter.md, content/api/payment_methods/post-order-santander.md, content/api/payment_methods/post-order-trustly.md, content/api/reference/variables.md
=> DOCS-2996: add format for var1 / var2 / var3

content/accounting/integrations/Actuals Live/_index.md, content/accounting/integrations/Actuals-Live/_index.md, content/accounting/integrations/Yuki/integrations/duopact.md, content/api/accounts/balances.md, content/api/accounts/charges.md, content/api/accounts/payouts.md, content/api/api/authentication.md, content/api/api/environments.md, content/integration/partner-integrations/reservation-management/_index.md, content/integration/partner-integrations/subscription-management/HostBill/_index.md, content/integration/partner-integrations/subscription-management/Twikey/_index.md, content/integration/ready-made/ccvshop/_index.md, content/integration/ready-made/shopify/_index.md, content/integration/ready-made/virtuemart/_index.md, content/integration/testing/testing-process.md, content/my-account/manage-account/site-id-api-key-secure-code.md, content/my-account/partner-primary-accounts/api-onboarding/_index.md, content/my-account/partner-primary-accounts/api-onboarding/add-bank-accounts.md, content/my-account/partner-primary-accounts/api-onboarding/add-ubos.md, content/my-account/partner-primary-accounts/api-onboarding/create-account.md
=> DOCS-3054: update site-id-api-key-secure-code URL

package.json
=> DOCS-0000: Fix dependabot alert

content/getting-started/create-your-integration/_index.md
=> Update button description

content/api/orders/recurring-payments-initial.md, content/api/orders/recurring-payments-subsequent.md, content/api/orders/specify-recurring-model.md, content/api/other_requests/retrieve-customer-tokens.md, content/api/other_requests/retrieve-token-details.md, content/api/reference/payment-details-object.md, content/payments/features/recurring-payments/_index.md
=> DOCS-3064: Fix cardOnFile case

content/payments/methods/wallet/googlepay/direct-integration/_index.md
=> DOCS-3061: Pull Google Pay direct prerequisites out of <details> element

content/payments/methods/wallet/googlepay/direct-integration/_index.md
=> DOCS-3061: Tech edit

.github/mlc_config.json
=> DOCS-0000: add edenred.be to ignore patterns for url checker

.github/mlc_config.json
=> DOCS-0000: add myedenred.be to ignore patterns

content/developer/general/iframes.md
=> DOCS-307: Move iFrame errors to developer general

content/api/reference/custom-info-object.md
=> DOCS-3070: Update max length of custom parameters

content/my-account/partner-primary-accounts/api-onboarding/add-ubos.md
=> DOCS-3076: Remove fax property from UBO requests

content/api/other_requests/retrieve-customer-tokens.md, content/api/other_requests/retrieve-token-details.md
=> DOCS-2985: Update Get token and List customer tokens

content/payments/refunds-and-chargebacks/refunds/full-partial-refunds.md
=> DOCS-3000: Update full and partial refund instructions

content/integration/ready-made/shopify/faq/deprecated-app.md
=> DOCS-0000: fix shopify dead links

content/api/orders/create-redirect-order.md, content/api/other_requests/retrieve-transactions.md, content/api/reference/customer-object.md, content/developer/api/google-analytics-tracking.md, content/developer/api/locale-parameter.md, content/developer/api/masking-iban-numbers.md, content/developer/api/pagination.md, content/payments/methods/banks/bank-transfer/overview.md, data/changelog.json
=> DOCS-1408: fix dead links

content/api/orders/discount-pay-later-orders.md, content/api/orders/discount-regular-orders.md, content/payments/refunds-and-chargebacks/refunds/discounts.md
=> DOCS-3060: Update documentation on discounts

.github/mlc_config.json
=> DOCS-0000: add shopware to ignore URL patterns

content/getting-started/glossary/multisafepay-glossary.md
=> DOCS-3099: Add alias to MultiSafepay glossary

content/my-account/manage-account/managing-currencies.md
=> DOCS-3100: Add alias to Managing currencies

content/integration/ready-made/prestashop-1-7/_index.md
This PR changes the download link of PrestaShop 1.7 plugin.
=> Release of 5.3.0 PrestaShop plugin

content/accounting/integrations/e-boekhouden/integrations/psp-betalingen.md, data/changelog.json
=> DOCS-3110: Update changelog

content/my-account/manage-account/site-id-api-key-secure-code.md
=> DOCS-3116: Remove account API key content

content/payments/methods/pay-later/klarna/user-guide/handling-disputes.md
=> DOCS-3114: Update Klarna portal link validity

content/payments/methods/pay-later/afterpay/_index.md, content/payments/methods/pay-later/afterpay/overview.md, content/payments/methods/pay-later/in3/_index.md, content/payments/methods/pay-later/in3/overview.md, content/payments/methods/pay-later/klarna/_index.md, content/payments/methods/pay-later/klarna/overview.md, content/payments/methods/pay-later/pay-after-delivery/_index.md, content/payments/methods/pay-later/pay-after-delivery/overview.md
=> DOCS-3113: Update surcharges notices

content/integration/ready-made/lightspeed_app/_index.md
=> DOCS-3133: Update Lightspeed installation instructions

content/integration/ready-made/prestashop-1-7/_index.md
=> DOCS-3136: Add minimum supported PHP version

content/integration/ready-made/prestashop-1-7/faq/updating-the-plugin.md
=> DOCS-3137: PrestaShop 1.7 updating the plugin

content/integration/ready-made/prestashop-1-7/faq/disable-shopping-cart.md
=> DOCS-3138: Add FAQ article for disabling the shopping cart

README.md
=> DOCS-3143: fix MultiSafepay careers dead link

content/payments/methods/banks/sepa-direct-debit/payment-flow.md
=> DOCS-3107: Clarify SEPA processing time

content/payments/features/recurring-payments/_index.md
=> DOCS-3144: fix prestashop 1.7 link

.github/mlc_config.json, content/integration/testing/test-payment-details.md
=> DOCS-0000: add postepay.it to ignore patterns

content/developer/wrappers/fastcheckout-ios/manual.md
Update Fastcheckout iOS SDK Documentation
=> [DOCS-3155] Update Fastcheckout iOS SDK Documentation

content/integration/self-made/validate-hmac-signatures.md
=> DOCS-3151: correct example on validate-hmac-signatures.md

content/integration/ready-made/prestashop-1-7/faq/processing-refunds.md
=> DOCS-3158: Update PrestaShop 1.7 refunding FAQ

content/integration/ready-made/prestashop-1-7/_index.md
This PR changes the download link of PrestaShop 1.7 plugin.
=> Release of 5.4.0 PrestaShop plugin

content/payments/features/split-payments/_index.md
=> DOCS-1340: Update Split Payments documentation

README.md
=> DOCS-0000: update MultiSafepay logo in readme

content/my-account/manage-account/vat-invoices.md
=> DOCS-3171: Update VAT invoices

content/my-account/manage-account/displaying-company-name.md, content/my-account/manage-account/uploading-files.md
=> DOCS-3172: Document uploading files via dashboard

content/my-account/manage-account/uploading-files.md
=> DOCS-3172: fix URL

content/integration/ready-made/woocommerce/_index.md
This PR changes the download link of the WooCommerce plugin
=> Release of WooCommerce plugin 4.13.1

content/payments/methods/pay-later/afterpay/integration-and-testing.md
=> DOCS-3166: fix AfterPay test instructions

content/my-account/manage-account/activating-payment-methods.md, content/payments/about-payments/activating-payment-methods.md
=> DOCS-3175: Mirror Activating payment methods

content/integration/ready-made/prestashop-1-7/_index.md, content/integration/ready-made/prestashop-1-7/faq/activating-payment-components.md, content/integration/ready-made/prestashop-1-7/faq/enabling-recurring-payments.md, content/integration/ready-made/prestashop-1-7/faq/processing-refunds.md, content/integration/ready-made/prestashop-1-7/faq/supported-checkouts-themes.md, content/integration/ready-made/prestashop-1-7/faq/translating-payment-methods.md, content/integration/ready-made/prestashop-1-7/faq/updating-the-plugin.md
=> DOCS-2939: Deprecate PrestaShop 1.7 repo

content/accounting/integrations/Yuki/_index.md
=> DOCS-3205: fix Yuki URL

config.toml
=> Remove broken link from sidemenu

data/changelog.json
=> Fix broken link to renamed section

content/integration/ready-made/prestashop-1-7/_index.md
=> DOCS-3209: PrestaShop 1.7 update installation/upgrading section

content/integration/ready-made/prestashop-1-7/_index.md
=> DOCS-3219: PrestaShop 1.7 update download link for release 5.4.1

content/api/_index.md, content/api/api-ref/_index.md
=> DOCS-3224: Add API reference notice page

content/getting-started/create-a-test-account/_index.md
=> DOCS-3226: Rework Create a test account

content/integration/ready-made/lightspeed_app/_index.md
=> DOCS-3227: Add WeChat Pay to Lightspeed

content/integration/checkouts/payment-pages/activating-payment-pages.md, content/payments/features/second-chance/_index.md, content/payments/features/split-payments/_index.md, content/payments/features/zero-authorization/_index.md, content/payments/refunds-and-chargebacks/refunds/discounts.md
=> DOCS-3193: Add links to API recipes

.github/mlc_config.json
=> DOCS-3247: remove markdown anchors from link-check

.github/mlc_config.json
=> DOCS-3249: add opencart to ignore patterns

content/payments/methods/wallet/applepay/integration-and-testing.md, content/payments/methods/wallet/applepay/redirect-integration/_index.md
=> DOCS-3237: add apple pay javascript

content/payments/about-payments/card-errors.md
=> DOCS-1808: Update credit card errors

.github/mlc_config.json, content/integration/ready-made/prestashop-1-7/faq/applying-surcharges.md
=> DOCS-3267: Update documentation on surcharges for Prestashop

.github/mlc_config.json, content/integration/self-made/_index.md, content/my-account/create-account/_index.md, content/my-account/onboarding/conditions-for-selling-alcohol.md
=> DOCS-3269: Fix dead links

config.toml, content/integration/ready-made/coppermine/_index.md, content/integration/ready-made/woocommerce/faq/allowing-notifications.md, content/integration/self-made/configure-your-webhook.md, content/integration/webhook/_index.md, content/my-account/partner-primary-accounts/api-onboarding/add-websites.md
=> DOCS-3276: update menu config and correct webhooks URL

content/my-account/manage-account/activating-payment-methods.md, content/my-account/manage-account/displaying-logos-and-icons.md, content/my-account/manage-account/making-payouts.md, content/my-account/manage-account/managing-currencies.md, content/my-account/manage-account/managing-payment-links.md, content/my-account/manage-account/managing-users.md, content/my-account/manage-account/setting-up-customer-emails.md, content/my-account/manage-account/topping-up-your-balance.md, content/my-account/manage-account/unmasking-ibans.md, content/my-account/manage-account/uploading-files.md, content/my-account/manage-account/viewing-vat-invoices.md, content/payments/about-payments/payment-statuses.md
=> DOCS-3275: Move Payment links and Email templates

.github/mlc_config.json, content/accounting/integrations/Yuki/_index.md, content/integration/checkouts/payment-pages/activating-payment-pages.md, content/my-account/onboarding/onboarding-process.md
=> DOCS-3295: Fix dead links

config.toml
=> DOCS-3280: Fix Getting started side menu

content/payments/methods/pay-later/betaalpermaand/integration-and-testing.md, content/payments/methods/pay-later/in3/integration-and-testing.md, content/payments/methods/pay-later/klarna/integration-and-testing.md, content/payments/methods/pay-later/pay-after-delivery/integration-and-testing.md
=> DOCS-0000: fix in3 integration and testing page

content/integration/ready-made/magento2/faq/activating-magento-vault.md
The checkbox for accepting the storage of the payment token is already included in Magento Vault.
=> PLGMAG2V2-435: Update Magento Vault

content/payments/methods/credit-and-debit-cards/refunds/_index.md
=> DOCS-3308: Relocate card refunds

content/payments/methods/pay-later/betaalpermaand/_index.md
=> DOCS-3314: Add Betaal per Maand contact details

.github/mlc_config.json, content/integration/ready-made/magento2/_index.md, content/my-account/manage-account/second-chance.md, content/payments/methods/banks/bank-transfer/unmatched-payments-dutch.md, content/payments/methods/banks/bank-transfer/unmatched-payments-german.md, content/payments/second-chance/_index.md
=> DOCS-3303: fix remaining dead links

.github/workflows/markdown-link-check.yml
=> DOCS-0000: trigger markdown-link-checker only on PRs to master

content/developer/emails/_index.md, content/developer/google-analytics/_index.md
=> DOCS-3345: Fix Developers

.github/mlc_config.json, content/developer/google-analytics/_index.md, content/integration/ready-made/opencart/_index.md, content/integration/ready-made/prestashop-1-7/_index.md, content/integration/ready-made/woocommerce/_index.md, content/payments/methods/banks/bancontact/_index.md, content/payments/methods/banks/bank-transfer/_index.md, content/payments/methods/banks/belfius/_index.md, content/payments/methods/banks/cbc-kbc/_index.md, content/payments/methods/banks/dotpay/_index.md, content/payments/methods/banks/eps/_index.md, content/payments/methods/banks/giropay/_index.md, content/payments/methods/banks/ideal/_index.md, content/payments/methods/banks/sepa-direct-debit/_index.md, content/payments/methods/banks/sofort/_index.md, content/payments/methods/banks/trustly/_index.md, content/payments/methods/credit-and-debit-cards/overview/_index.md, content/payments/methods/pay-later/afterpay/_index.md, content/payments/methods/pay-later/betaalpermaand/_index.md, content/payments/methods/pay-later/e-invoicing/_index.md, content/payments/methods/pay-later/in3/_index.md, content/payments/methods/pay-later/klarna/_index.md, content/payments/methods/pay-later/pay-after-delivery/_index.md, content/payments/methods/prepaid-cards/gift-cards/_index.md, content/payments/methods/prepaid-cards/paysafecard/_index.md, content/payments/methods/wallet/alipay/_index.md, content/payments/methods/wallet/applepay/_index.md, content/payments/methods/wallet/paypal/_index.md, content/payments/recurring-payments/_index.md, content/payments/second-chance/_index.md
=> DOCS-3346: add aliases for plugin links

content/my-account/manage-account/payment-links.md
=> DOCS-3350: Update payment links

.github/mlc_config.json, content/my-account/manage-account/payment-links.md
=> DOCS-3350: fix dead link

content/developer/email-authentication.md, content/developer/google-analytics.md, content/developer/handling-errors.md, content/developer/http-errors.md, content/developer/iframes.md, content/developer/wrappers-and-sdks.md
=> Review of developer section

.github/banned_words.py
DOCS-3379: add single quote to ignore characters
- Tested
=> Cherry pick DOCS-3379

content/my-account/account-balance.md, content/my-account/account-users.md, content/my-account/affiliated-merchants.md, content/my-account/api-onboarding.md, content/my-account/create-account.md, content/my-account/currencies.md, content/my-account/ibans.md, content/my-account/invoices.md, content/my-account/logos-and-icons.md, content/my-account/onboarding.md, content/my-account/payment-methods.md, content/my-account/payouts.md, content/my-account/websites.md
=> DOCS-3380: Formatting My account

.github/workflows/readme-docs-sync.yml
=> DOCS-3284: add github action for readme sync

.github/workflows/readme-docs-sync.yml
=> DOCS-3284: update readme action

.github/workflows/readme-docs-sync.yml
=> DOCS-3284: fix rdme version

.github/workflows/readme-docs-sync.yml
=> DOCS-3284: change key

.github/workflows/readme-docs-sync.yml
=> DOCS-3284: correct rdme command

.github/workflows/readme-docs-sync.yml
=> DOCS-3284: change readme sync trigger to on merge

content/my-account/websites.md, content/payment-methods/ing-home-pay.md
=> DOCS-3384: fix readme side menu

content/my-account/ibans.md
=> DOCS-3385: IBANs process

content/integrations/magento-2.md, content/integrations/prestashop-1-7.md, content/integrations/woocommerce.md, content/payment-methods/cardholder-data.md
=> DOCS-3382: Fix broken link

content/developer/fastcheckout-android-sdk.md, content/developer/fastcheckout-ios-sdk.md, content/integrations/ccv-shop.md, content/integrations/coppermine.md, content/integrations/craft-commerce.md, content/integrations/cs-cart.md, content/integrations/drupal.md, content/integrations/ecwid.md, content/integrations/lightspeed.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/mijnwebwinkel.md, content/integrations/myshop.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/oscommerce.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop-1-7.md, content/integrations/pwa-studio.md, content/integrations/scandipwa.md, content/integrations/shopify.md, content/integrations/shopware.md, content/integrations/virtuemart.md, content/integrations/vue-storefront.md, content/integrations/woocommerce.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> DOCS-3387: Format integrations

content/developer/wrappers-and-sdks.md, content/integrations/community-integrations.md, content/integrations/craft-commerce.md, content/integrations/cs-cart.md, content/integrations/drupal.md, content/integrations/lightspeed.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/oscommerce.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop-1-7.md, content/integrations/pwa-studio.md, content/integrations/scandipwa.md, content/integrations/shopware.md, content/integrations/virtuemart.md, content/integrations/vue-storefront.md, content/integrations/woocommerce.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> DOCS-3390: Add buttons

content/online-payments/refunds.md, content/payment-methods/klarna.md
=> DOCS-3391: rename refunds page slug

content/getting-started/glossary.md, content/getting-started/security-and-legal.md
=> Reorder getting started

.github/workflows/manual.yml
=> Add action to delete branch

.github/workflows/create-diagrams.yml, .github/workflows/manual.yml, static/diagrams/src/webhook.mmd
- Add action to delete branch after merged PRs
- Create pull request for newly generated diagrams
- Tested
=> Update mermaid workflow

content/payment-methods/afterpay.md, static/diagrams/src/afterpay-payment-flow.mmd
=> Test diagram GitHub Action

.github/workflows/create-diagrams.yml, content/payment-methods/alipay.md, static/diagrams/src/alipay-payment-flow.mmd
=> Test diagram actions

content/online-payments/customer-emails.md, content/online-payments/multiple.md, content/online-payments/payment-components.md, content/online-payments/payment-links.md, content/online-payments/payment-pages.md, content/online-payments/payment-statuses.md, content/online-payments/recurring-payments.md, content/online-payments/refunds.md, content/online-payments/second-chance.md, content/online-payments/single.md, content/online-payments/split-payments.md, content/online-payments/viban.md
=> DOCS-3395: online-payments

content/getting-started/getting-started-guide.md, content/getting-started/glossary.md, content/getting-started/pci-dss.md, content/getting-started/risk-and-fraud.md, content/getting-started/surcharges.md
=> DOCS-3395: getting-started

content/developer/email-authentication.md, content/developer/fastcheckout-android-sdk.md, content/developer/fastcheckout-ios-sdk.md, content/developer/google-analytics.md, content/developer/handling-errors.md, content/developer/http-errors.md
=> DOCS-3395: developer

static/svgs/octopus.svg
=> DOCS-3404: add octopus logo

api/listtransactions.md
=> DOCS-3410: Document API key changes GET /transactions

.github/workflows/readme-docs-sync.yml
=> Sync API stubs on merged PRs

.github/workflows/readme-docs-sync.yml
=> Prepare action for production

content/my-account/email-styling.md, content/my-account/ibans.md, content/my-account/invoices.md, content/my-account/partner-primary-accounts.md, content/my-account/payment-methods.md, content/my-account/payouts.md, content/my-account/sites.md
=> DOCS-3415: Rename and move Email styling

content/integrations/opencart.md
=> DOCS-3400: Add Payment component to OpenCart

aliases/my-account.md
=> DOCS-3411: collect aliases for my account section

content/integrations/craft-commerce.md, content/integrations/cs-cart.md, content/integrations/drupal.md, content/integrations/lightspeed.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/oscommerce.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop-1-7.md, content/integrations/pwa-studio.md, content/integrations/scandipwa.md, content/integrations/shopify.md, content/integrations/shopware.md, content/integrations/virtuemart.md, content/integrations/vue-storefront.md, content/integrations/woocommerce.md
=> DOCS-3417: Alphabetize Our integrations

content/payment-methods/afterpay.md, content/payment-methods/alipay.md, content/payment-methods/betaalpermaand.md, content/payment-methods/gift-cards.md, content/payment-methods/paysafecard.md
=> DOCS-3422: Payment method fixes

README.md, content/integrations/magento-2.md
=> DOCS-3412: update README

content/getting-started/getting-started-guide.md
=> DOCS-3418: Remove Manage my account link in Getting started guide

content/payment-methods/afterpay.md, content/payment-methods/betaalpermaand.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/pay-after-delivery.md
=> DOCS-3425: BNPL fixes

content/my-account/invoices.md
=> DOCS-3428: Remove Invoices table

content/my-account/currencies.md
=> DOCS-3427: Remove brackets in Currencies

aliases/checkout.md, aliases/my-account.md, aliases/payment-management.md
=> DOCS-3411: collect aliases for checkout and payment management sections

content/developer/troubleshooting.md
=> DOCS-3436: Fix in Troubleshooting

content/checkout/qr-codes.md
=> DOCS-3429: Add QR tiles

content/integrations/ccv-shop.md, content/integrations/coppermine.md, content/integrations/craft-commerce.md, content/integrations/cs-cart.md, content/integrations/drupal.md, content/integrations/ecwid.md, content/integrations/lightspeed.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/mijnwebwinkel.md, content/integrations/myshop.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/oscommerce.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop-1-7.md, content/integrations/pwa-studio.md, content/integrations/scandipwa.md, content/integrations/shopify.md, content/integrations/shopware.md, content/integrations/virtuemart.md, content/integrations/vue-storefront.md, content/integrations/woocommerce.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> DOCS-3439: Trim integration excerpts

content/getting-started/security-and-legal.md, content/my-account/manage-my-account.md
=> DOCS-3438: Add summary pages

content/developer/troubleshooting.md
=> DOCS-3442: Another Troubleshooting fix

content/my-account/manage-my-account.md
=> DOCS-3445: Remove Manage my account excerpt

content/payment-methods/chargebacks.md
=> DOCS-3441: Add logos to Chargebacks

content/integrations/lightspeed.md
=> DOCS-3437: lightspeed fix

content/payment-methods/testing.md
=> DOCS-3446: Testing fixes

api/cancelauthorizedorder.md, api/capturepayment.md, api/challengechargeback.md, api/createorder.md, api/deletetoken.md, api/generateapitoken.md, api/getgateway.md, api/getorder.md, api/getpaymentmethod.md, api/getsite.md, api/gettoken.md, api/gettransaction.md, api/listgateways.md, api/listidealissuers.md, api/listpaymentmethods.md, api/listtokens.md, api/listtransactions.md, api/refundorder.md, api/updatecardexpirydate.md, api/updateorder.md, api/updatesite.md
=> DOCS-3447: API warning fix

content/checkout/qr-codes.md
=> DOCS-3449: QR tile fix

aliases/checkout.md, aliases/developer.md, aliases/getting-started.md, aliases/my-account.md, aliases/payment-management.md, aliases/payment-methods.md
=> DOCS-3450: Update aliases

content/developer/fastcheckout-android-sdk.md, content/developer/fastcheckout-ios-sdk.md
=> DOCS-3453: Convert FastCheckout SDKs to Readme

.github/CODEOWNERS
=> DOCS-3455: add CODEOWNERS file

content/integrations/shopify.md
=> DOCS-3310: Update Shopify installation

api/listtransactions.md
=> DOCS-3452: update docs link

.github/workflows/create-diagrams.yml, .github/workflows/readme-docs-sync.yml
- Enable readme sync on master branch
- Enable mermaid diagram generation on master branch
- Tested
=> DOCS-0000: Enable actions on master

content/.gitattributes
=> DOCS-3465: add gitattribute file

content/getting-started/getting-started-guide.md
=> DOCS-3466: Remove Getting started guide numbering

content/checkout/payment-pages.md
=> DOCS-3467: Update styling payment pages

.github/workflows/create-diagrams.yml, .github/workflows/readme-docs-sync.yml
=> DOCS-3469: remove branch reference from readme github action

content/checkout/payment-links.md, content/integrations/craft-commerce.md, content/integrations/opencart.md, content/integrations/shopify.md, content/integrations/shopware.md, content/payment-management/discounts.md, content/payment-management/recurring-payments.md, content/payment-management/second-chance.md, content/payment-methods/bancontact.md, content/payment-methods/cbc-kbc.md, content/payment-methods/e-invoicing.md, content/payment-methods/google-pay.md, content/payment-methods/ideal.md, content/payment-methods/in3.md
=> DOCS-3467: fix dead links after migration

.github/mlc_config.json, api/cancelauthorizedorder.md, api/capturepayment.md, api/challengechargeback.md, api/createorder.md, api/deletetoken.md, api/generateapitoken.md, api/getgateway.md, api/getorder.md, api/getpaymentmethod.md, api/getsite.md, api/gettoken.md, api/gettransaction.md, api/listgateways.md, api/listidealissuers.md, api/listpaymentmethods.md, api/listtokens.md, api/listtransactions.md, api/refundorder.md, api/updatecardexpirydate.md, api/updateorder.md, api/updatesite.md, content/payment-management/second-chance.md, content/payment-methods/afterpay.md
=> DOCS-3467: fix dead links after migration part 2

content/integrations/webshop-access-spanish.md
=> DOCS-3472: fix spanish help us help you URL

content/accounting/reports.md, content/developer/troubleshooting.md, content/getting-started/glossary.md, content/getting-started/risk-and-fraud.md, content/integrations/manage-orders.md, content/my-account/account-balance.md, content/my-account/currencies.md, content/my-account/invoices.md, content/my-account/onboarding.md, content/payment-management/payment-statuses.md, content/payment-management/refunds.md, content/payment-methods/afterpay.md, content/payment-methods/bancontact.md, content/payment-methods/betaalpermaand.md, content/payment-methods/eps.md, content/payment-methods/giropay.md, content/payment-methods/ideal.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/mybank.md, content/payment-methods/pay-after-delivery.md, content/payment-methods/request-to-pay.md, content/payment-methods/sofort.md, content/payment-methods/testing.md, content/payment-methods/uncaptured.md
=> DOCS-3461: Add payout and settlement to glossary

content/payment-methods/trustly.md
=> DOCS-3340: Update Trustly

content/payment-methods/moto.md
=> DOCS-3460: Add MOTO prerequisite

content/my-account/payment-methods.md
=> DOCS-3476: Adjust Payment methods per country

content/my-account/onboarding.md
=> Docs 3487: Update required site information

.github/workflows/banned-words.yml, .github/workflows/mail checker.yml, .github/workflows/markdown-link-check-daily.yml, .github/workflows/urlchecker.yml
=> DOCS-3490: specify checkout action version

content/payment-methods/google-pay-integration.md
=> DOCS-3348: specify Google Pay country code as NL

aliases/full-list.md
=> DOCS-3493: add logos icons redirect

content/getting-started/glossary.md, content/my-account/payment-methods.md, content/payment-management/refunds.md, content/payment-methods/card-payments.md
=> DOCS-3279: clarify reversals can't be canceled

content/integrations/shopware.md
=> DOCS-3361: update shopware download link to 2.6.1

content/integrations/magento-2.md
=> DOCS-3403: clarify magento refund rules with multisafepay dashboard

content/integrations/magento-2.md
=> DOCS-3454: update magento 2 configuration instructions

content/integrations/craft-commerce.md, content/integrations/drupal.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/prestashop-1-7.md, content/integrations/shopware.md, content/integrations/woocommerce.md
=> DOCS-3375: add plugin generic gateways support release versions

content/integrations/shopware.md, content/integrations/woocommerce.md
=> DOCS-3294: add payment component and recurring payments to shopware

glossary/glossary-terms.md
=> DOCS-3497: back up readme glossary terms

content/payment-methods/testing.md
=> DOCS-3499: remove VISA test card number

content/payment-management/viban.md
=> DOCS-3475: Update VIBANs

content/my-account/payment-methods.md, content/payment-methods/gift-cards.md
=> DOCS-3505: update gift cards activation

.github/mlc_config.json
=> DOCS-3507: add API server URLs to ignore patterns

content/integrations/configure-your-webhook.md
=> DOCS-3464: Add masking IBANs to Webhooks

content/my-account/email-styling.md, content/payment-methods/card-payments.md, content/payment-methods/mybank.md, content/payment-methods/testing.md
=> DOCS-3480: Improve directions to locale parameter

content/developer/rounding-rule.md
=> DOCS-3374: Revise rounding rule

.github/mlc_config.json, api/general/authentication.md
=> DOCS-3507: disable link check for authentications page

content/checkout/payment-pages.md, content/my-account/email-styling.md, content/payment-management/discounts.md
=> DOCS-3482: Clarify localizing payment pages

content/payment-methods/ideal.md
=> Docs 3515: Add iDEAL issuers to iDEAL page

content/developer/rounding-rule.md, content/developer/troubleshooting.md, content/developer/wrappers-and-sdks.md
=> DOCS-3374: Alphabetize developer section

content/payment-methods/bancontact.md, content/payment-methods/bank-transfer.md, content/payment-methods/gift-cards.md, content/payment-methods/ideal.md, content/payment-methods/klarna.md, content/payment-methods/paypal.md
=> DOCS-3516: Payment method fixes

content/checkout/payment-pages.md, content/payment-management/discounts.md, content/payment-management/second-chance.md, content/payment-management/split-payments.md, content/payment-methods/afterpay.md, content/payment-methods/betaalpermaand.md, content/payment-methods/e-invoicing.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/pay-after-delivery.md
=> DOCS-3512: Promote shopping_cart recipe

landing-page/landing-page.html
=> DOCS-3502: Backup landing page

content/integrations/shopify.md
=> DOCS-3520: Add Shopify deadline

content/developer/rounding-rule.md
=> Fix rounding rule example JSON

content/payment-methods/apple-pay-integration.md
=> DOCS-3057: Update Apple Pay domain validation download

content/accounting/accounting-integrations.md
=> DOCS-3526: Fix Duopact link

content/developer/email-authentication.md
=> DOCS-3530: Clarify SPF rules

content/payment-methods/in3.md
=> DOCS-3535: Add Magento 2 to in3

.github/archive/integration-team/connectjs.md, api/general/authentication.md, api/general/introduction.md, api/general/transaction-expiration.md, content/integrations/configure-your-webhook.md, content/integrations/webshop-access-ita.md, content/integrations/webshop-access.md
=> DOCS-3456: fix dead links

content/integrations/magento-2.md
=> DOCS-3536: Update Magento 2 Updates

content/payment-methods/3ds2.md, content/payment-methods/cardholder-data.md
=> DOCS-3373: Document 3DS2 for cardholder data payments

content/payment-methods/chargebacks.md
=> DOCS-3510: Review and updated chargebacks

content/accounting/accounting-integrations.md, content/accounting/reports.md, content/developer/fastcheckout-android-sdk.md, content/developer/google-analytics.md, content/developer/troubleshooting.md, content/getting-started/gdpr.md, content/getting-started/getting-started-guide.md, content/getting-started/glossary.md, content/getting-started/surcharges.md, content/integrations/community-integrations.md, content/integrations/configure-your-webhook.md, content/integrations/ecwid.md, content/integrations/handle-notifications.md, content/integrations/manage-orders.md, content/integrations/opencart.md, content/integrations/self-made.md, content/my-account/currencies.md, content/my-account/invoices.md, content/my-account/payment-methods.md, content/payment-methods/apple-pay-integration.md, content/payment-methods/apple-pay.md, content/payment-methods/google-pay.md, content/payment-methods/paypal.md, content/payment-methods/sofort.md, content/payment-methods/testing.md, content/payment-methods/uncaptured.md
=> DOCS-3545: Fix icons and support boxes

.github/mlc_config.json
=> DOCS-3353: add lastpass to ignore patterns

content/checkout/payment-pages.md, content/my-account/email-styling.md
=> DOCS-3554: Add locale example

content/payment-management/second-chance.md
=> DOCS-3552: Update Second Chance

content/payment-management/recurring-payments.md, content/payment-methods/sepa-direct-debit.md
=> DOCS-3555: Update recurring payments

content/integrations/configure-your-webhook.md
=> DOCS-3378: add webhook endpoint default

content/integrations/woocommerce.md
=> DOCS-3558: Add TranslatePress to WooCommerce

content/integrations/prestashop-1-6.md
=> DOCS-3559: Add generic gateway to Prestashop 1.6

content/payment-methods/3ds2.md
=> DOCS-3561: Update 3DS2

content/payment-methods/apple-pay.md
=> DOCS-3563: add American Express to Apple Pay description

content/integrations/configure-your-webhook.md, content/integrations/coppermine.md, content/integrations/craft-commerce.md, content/integrations/cs-cart.md, content/integrations/drupal.md, content/integrations/ecwid.md, content/integrations/handle-notifications.md, content/integrations/lightspeed.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/mijnwebwinkel.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/oscommerce.md, content/integrations/partner-integrations.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop-1-7.md, content/integrations/pwa-studio.md, content/integrations/scandipwa.md, content/integrations/shopify.md, content/integrations/shopware.md, content/integrations/virtuemart.md, content/integrations/vue-storefront.md, content/integrations/webshop-access-ita.md, content/integrations/webshop-access.md, content/integrations/woocommerce.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> DOCS-3500: replace external URLs in integrations

content/checkout/multiple.md, content/checkout/previous-release.md, content/checkout/single.md, content/integrations/magento-2.md, content/integrations/opencart.md, content/integrations/prestashop-1-6.md, content/integrations/shopware.md
=> DOCS-3565: minor UI fixes

.github/external-link-detector.py, .github/external-link-replace.py, .github/workflows/external-urls.yml
=> DOCS-3500: add workflow and python scripts for URL modification

.github/external-link-replace.py
=> DOCS-3500: update external-link-replace.py

.github/workflows/external-urls.yml
=> DOCS-3500: fix external URLs workflow

.github/external-link-replace.py, .github/workflows/external-urls.yml
=> DOCS-3500: test external URLs workflow

content/payment-methods/sofort.md
=> DOCS-3571: Update Sofort processing times

content/payment-methods/manual-capture.md
=> DOCS-3575: add recipe links to manual capture page

content/checkout/fastcheckout-integration.md, content/checkout/fastcheckout.md
=> DOCS-2866-2: Publish FCO docs

content/checkout/fastcheckout.md
=> DOCS-286-4: Fix images

content/checkout/fastcheckout.md
=> DOCS-2866-5: Fix images

content/integrations/scandipwa.md
=> DOCS-3578: Update ScandiPWA installation

content/checkout/fastcheckout.md, content/integrations/pwa-studio.md
=> DOCS-3581: Add installation instructions to PWA Studio

content/checkout/fastcheckout.md
=> DOCS-3582: Add beta banner to FCO

content/payment-methods/bancontact.md
=> DOCS-2719: Update Bancontact mobile statuses

content/integrations/odoo.md
=> DOCS-3592: Update Odoo user guide

api/general/gateway-ids.md, api/general/transaction-expiration.md, content/checkout/payment-components.md, content/checkout/payment-links.md, content/checkout/single.md, content/getting-started/surcharges.md, content/integrations/ccv-shop.md, content/integrations/ecwid.md, content/integrations/magento-1.md, content/integrations/mijnwebwinkel.md, content/integrations/myshop.md, content/integrations/odoo.md, content/integrations/oscommerce.md, content/integrations/partner-integrations.md, content/integrations/prestashop-1-6.md, content/integrations/shopify.md, content/integrations/woocommerce.md
=> DOCS-3595: Update DIRDEB and bank transfer and direct debit changes

content/getting-started/getting-started-guide.md
=> DOCS-3597: Renumber Getting started guide

content/payment-methods/apple-pay.md, content/payment-methods/card-payments.md, content/payment-methods/google-pay.md
=> DOCS-3596: Update Google/Apple Pay activation

content/payment-methods/apple-pay-integration.md, content/payment-methods/google-pay-integration.md
=> DOCS-3598: Update Apple Pay integration callouts

content/payment-methods/direct-debit.md, content/payment-methods/dotpay.md, content/payment-methods/eps.md, content/payment-methods/giropay.md, content/payment-methods/ideal.md
=> DOCS-3598-2: Fix direct debit weight

content/accounting/accounting-integrations.md, content/accounting/reports.md, content/integrations/magento-2.md, content/payment-methods/apple-pay-integration.md, content/payment-methods/google-pay-integration.md
=> DOCS-3598-3: More Apple Pay integration fixes

content/integrations/woocommerce.md
- Update download link. 
- Update requirements.
=> PLGWOOS-831: Release of WooCommerce plugin 5.0.0

content/my-account/partner-primary-accounts.md
=> DOCS-3602: Fix charging affiliates

content/checkout/fastcheckout.md
=> DOCS-3606: Fix FCO headings

content/integrations/magento-2.md
=> DOCS-3607: Fix in Magento 2

api/multisafepay-api/listgateways.md, content/payment-methods/card-payments.md
=> DOCS-3612: Add note about CREDITCARD gateway

content/payment-methods/moto.md
=> DOCS-3601: Add recipe to MOTO

content/checkout/fastcheckout-integration.md, content/checkout/fastcheckout-shipping-options-request.md, content/checkout/fastcheckout.md
=> DOCS-3609: Document FCO shipping options request

content/integrations/prestashop-1-6.md
=> DOCS-3623: Add payment components to PrestaShop 1.6

.github/workflows/spellchecker.yml, .pyspelling.yml, content/my-account/currencies.md, content/payment-methods/testing.md
=> DOCS-3619: add spellchecker weekly schedule

.github/workflows/spellchecker-weekly.yml, .github/workflows/spellchecker.yml
=> DOCS-3619: add spellcheck on pull request

.github/workflows/spellchecker.yml
=> DOCS-3619: spellcheck refinement

content/payment-methods/sofort.md
=> DOCS-3627: Update Sofort

content/checkout/fastcheckout-shipping-options-request.md, content/checkout/fastcheckout.md, static/diagrams/src/fastcheckout-shipping-options.mmd, static/diagrams/src/fastcheckout.mmd
=> DOCS-3628: Add FCO diagrams

content/my-account/payment-methods.md, content/payment-methods/afterpay.md, content/payment-methods/betaalpermaand.md, content/payment-methods/gift-cards.md, content/payment-methods/ideal.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/pay-after-delivery.md, wordlist.txt
=> DOCS-3611: Update AfterPay countries

.github/workflows/spellchecker.yml, content/integrations/webshop-access-ita.md
=> DOCS-3619: add filter to spellcheck action

content/payment-management/refunds.md, content/payment-methods/card-payments.md, content/payment-methods/card-refunds.md, content/payment-methods/uncaptured.md, content/payment-methods/zero-authorization.md
=> DOCS-3608: Improve credit cards

content/payment-management/refunds.md, content/payment-methods/3ds2.md, content/payment-methods/card-errors.md, content/payment-methods/cardholder-data.md, content/payment-methods/chargebacks.md, content/payment-methods/interchange.md, content/payment-methods/manual-capture.md, content/payment-methods/moto.md
=> DOCS-3633: Fix Card refunds weight

content/getting-started/glossary.md
=> DOCS-3585: PAD 2 Glossary

content/payment-methods/chargebacks.md
=> DOCS-3641: Fix Chargeback heading levels

content/checkout/payment-components.md, content/checkout/payment-pages.md, static/diagrams/src/fastcheckout.mmd, static/diagrams/src/payment-components.mmd, static/diagrams/src/payment-pages.mmd
=> DOCS-3539: Add sequence diagrams for integrations

content/integrations/shopware.md
=> DOCS-0000: Remove manual installation instructions from Shopware 6

content/checkout/fastcheckout.md
=> DOCS-3644: Update FCO payment methods

content/developer/google-analytics.md
=> DOCS-1200: update Google Analytics page

content/checkout/payment-links.md
=> DOCS-3647: Update payment link statuses

content/checkout/fastcheckout.md
=> DOCS-3648: Remove Apple Pay from FCO

content/getting-started/getting-started-guide.md
=> DOCS-3649: Getting started guide fixes

content/developer/google-analytics.md
=> DOCS-3650: Fix Google Analytics

content/checkout/fastcheckout-integration.md, content/checkout/fastcheckout.md
=> DOCS-3653: FCO typos

content/checkout/fastcheckout-shipping-options-request.md, content/integrations/configure-your-webhook.md, content/integrations/handle-notifications.md
=> DOCS-3634: Update webhook pages with feed_url

content/payment-methods/gift-cards.md
=> DOCS-3572: Document disabling payment confirmation emails for gift cards

content/integrations/shopware.md, content/payment-methods/alipay-plus.md, content/payment-methods/alipay.md, content/payment-methods/card-errors.md, content/payment-methods/gift-cards.md
=> DOCS-3654: Add POS to glossary

content/payment-methods/apple-pay-integration.md
=> DOCS-3656: Fix Apple Pay

content/payment-methods/afterpay.md, content/payment-methods/e-invoicing.md, content/payment-methods/in3.md, content/payment-methods/pay-after-delivery.md
=> DOCS-3655-2: Fix

api/multisafepay-api/cancelauthorizedorder.md, api/multisafepay-api/capturepayment.md, api/multisafepay-api/challengechargeback.md, api/multisafepay-api/createorder.md, api/multisafepay-api/deletetoken.md, api/multisafepay-api/generateapitoken.md, api/multisafepay-api/getgateway.md, api/multisafepay-api/getorder.md, api/multisafepay-api/getpaymentmethod.md, api/multisafepay-api/getsite.md, api/multisafepay-api/gettoken.md, api/multisafepay-api/gettransaction.md, api/multisafepay-api/listgateways.md, api/multisafepay-api/listidealissuers.md, api/multisafepay-api/listpaymentmethods.md, api/multisafepay-api/listtokens.md, api/multisafepay-api/listtransactions.md, api/multisafepay-api/refundorder.md, api/multisafepay-api/updatecardexpirydate.md, api/multisafepay-api/updateorder.md, api/multisafepay-api/updatesite.md
=> DOCS-3657: Add support to API ref

content/my-account/company-information.md, content/my-account/currencies.md, content/my-account/email-styling.md, content/my-account/ibans.md, content/my-account/invoices.md, content/my-account/onboarding.md, content/my-account/partner-primary-accounts.md, content/my-account/payment-methods.md, content/my-account/payouts.md, content/my-account/sites.md
=> DOCS-3660: Move Company information

content/my-account/onboarding.md
=> DOCS-3660-2: Onboarding fix

api/general/gateway-ids.md, api/general/introduction.md, api/general/pagination.md, api/general/transaction-expiration.md, api/general/troubleshooting.md
=> DOCS-3661: Pagination

api/general/error-reference.md
=> DOCS-2954: Error reference

api/general/transaction-expiration.md
=> DOCS-3662: Fix transaction expiration

content/payment-methods/apple-pay-direct.md, content/payment-methods/apple-pay.md, content/payment-methods/google-pay-direct.md, content/payment-methods/testing.md
=> DOCS-3663: Rename Apple and Google Pay direct

content/payment-methods/ideal.md
=> DOCS-3666: Small iDEAL fix

content/integrations/shopify.md
=> DOCS-3631: Update Shopify

content/integrations/magento-1.md, content/integrations/woocommerce.md, content/payment-methods/direct-debit.md
=> DOCS-3672: GitHub action fixes

content/integrations/woocommerce.md
=> DOCS-3669: Update WooCommerce payment methods

content/payment-methods/riverty.md
=> DOCS-3673: Riverty fix

content/payment-methods/in3.md
=> DOCS-3673-2: Weight fix

content/accounting/reports.md, content/payment-methods/uncaptured.md
=> DOCS-3673-4: Dead links

content/getting-started/getting-started-guide.md
=> DOCS-3683: Improve Getting started guide

content/integrations/our-integrations.md
=> DOCS-3680: Improve Our integrations

content/integrations/our-integrations.md
=> DOCS-3680-1: Fix Our Integrations

content/integrations/our-integrations.md
=> DOCS-3680-3: Tweak formatting

content/integrations/our-integrations.md
=> DOCS-3680-3: Reformat Our integrations

api/general/error-reference.md, content/developer/troubleshooting.md, content/integrations/handle-notifications.md, content/integrations/lightspeed.md, content/integrations/our-integrations.md, content/payment-methods/testing.md
=> DOCS-3685: Rename Offline actions

content/integrations/test.md, wordlist.txt
=> DOCS-3680-4: Experiment 1

api/general/introduction.md
=> DOCS-3260: Add API reference video tour

api/general/introduction.md
=> DOCS-3260-2: Remove thumbnail

api/general/introduction.md
=> DOCS-3260-3: API ref video tour embed

api/general/introduction.md
=> DOCS-3260-5: API video

content/payment-methods/e-invoicing.md, static/diagrams/src/e-invoicing-payment-flow.mmd
=> DOCS-2392: Document E-Invoicing 2

content/payment-methods/e-invoicing.md
=> DOCS-3693: Fix dead links

.github/archive/integration-team/integration-review-eng.md, .github/archive/integration-team/integration-review-nl.md
=> DOCS-3700: Fix dead links

content/integrations/handle-notifications.md
=> DOCS-3695: Update Resend notification

content/payment-methods/testing.md
=> DOCS-3699: Update Amex testing

content/payment-methods/amazon-pay.md
=> DOCS-3702: Link Amazon Pay to main domain

content/payment-methods/alipay-plus.md, content/payment-methods/alipay.md, content/payment-methods/amazon-pay.md, content/payment-methods/bank-transfer.md, content/payment-methods/betaalpermaand.md, content/payment-methods/card-payments.md, content/payment-methods/edenred.md, content/payment-methods/gift-cards.md, content/payment-methods/pay-after-delivery.md, content/payment-methods/riverty.md
=> DOCS-3710: Condense API examples

content/payment-methods/direct-debit.md
=> DOCS-3712: Update direct debit status

content/integrations/shopify.md
=> DOCS-3711: Update Shopify order expiration

content/integrations/shopware.md
=> DOCS-3698: Document Shopware 5 backend orders plugin

content/checkout/fastcheckout-shipping-options-request.md, content/developer/google-analytics.md, content/developer/http-errors.md, content/getting-started/getting-started-guide.md, content/getting-started/glossary.md, content/integrations/coppermine.md, content/integrations/cs-cart.md, content/integrations/odoo.md, content/integrations/self-made.md, content/integrations/webshop-access.md, content/my-account/sites.md, content/payment-methods/apple-pay.md
=> DOCS-3715: Rename Self-made integrations

content/checkout/fastcheckout.md, content/checkout/multiple.md, content/checkout/single.md, content/getting-started/fuhrmann2.md, content/getting-started/gdpr.md, content/getting-started/pci-dss.md, content/getting-started/psd2.md, content/getting-started/risk-and-fraud.md, content/getting-started/security-and-legal.md, content/getting-started/surcharges.md, content/integrations/api-integration.md, content/integrations/drupal.md, content/integrations/odoo.md, content/integrations/opencart.md, content/integrations/prestashop-1-7.md, content/my-account/currencies.md, content/my-account/email-styling.md, content/my-account/onboarding.md, content/payment-management/second-chance.md, content/payment-methods/bancontact.md, content/payment-methods/betaalpermaand.md, content/payment-methods/e-invoicing.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/pay-after-delivery.md, content/payment-methods/riverty.md, content/payment-methods/testing.md
=> DOCS-3717: Fix side menu weights

content/payment-methods/betaalpermaand.md, content/payment-methods/e-invoicing.md, content/payment-methods/klarna.md, content/payment-methods/wechatpay.md
=> DOCS-3718: Add B2B prohibition to WeChat Pay

content/integrations/shopify.md
=> DOCS-3720: Remove BNPL from Shopify

content/payment-management/second-chance.md
=> DOCS-3722: Update Second Chance

content/payment-methods/chargebacks.md
=> DOCS-3725: Document chargeback dashboard alert

api/general/error-reference.md, content/checkout/fastcheckout-shipping-options-request.md, content/developer/troubleshooting.md, content/payment-methods/betaalpermaand.md
=> DOCS-3724: Remove PSP ID and test side menu weight

content/payment-methods/apple-pay.md, content/payment-methods/google-pay.md
=> DOCS-3278: Clarify when Apple and Google pay display

content/getting-started/surcharges.md, content/my-account/create-account.md
=> DOCS-3729: Add PSP to glossary

content/getting-started/glossary.md
=> DOCS-3738: Add glossary terms

content/payment-methods/testing.md
=> DOCS-3740: Change maestro test card

content/payment-methods/pay-after-delivery.md
=> DOCS-3737: Add Uncleared status to PAD

content/integrations/woocommerce.md
=> DOCS-3558: Remove TranslatePress content

content/integrations/woocommerce.md
=> DOCS-3752: Add TranslatePress instructions

content/checkout/customization.md, content/checkout/payment-pages.md
=> Docs 3748: Document payment component styling via dashboard

content/my-account/payouts.md
=> DOCS-3754: Update payout processing times

content/my-account/invoices.md, content/payment-management/refunds.md
=> DOCS-3759: Document refund receipts

content/integrations/prestashop-1-7.md
=> DOCS-3762: Refunds with cart rule discounts are not supported

content/payment-methods/alipay-plus.md, content/payment-methods/alipay.md
=> DOCS-3761:Document Alipay+ migration

content/payment-methods/3ds2.md
=> DOCS-3768:Fix error SCA page

content/payment-methods/testing.md
=> DOCS-3771:Update Amex card number

content/integrations/prestashop-1-7.md
=> DOCS-3772: Update download link PrestaShop 1.7 to 5.6.0

content/integrations/woocommerce.md
=> DOCS-3773: Update download link WooCommerce to 5.1.1

content/integrations/magento-2.md
=> DOCS-3769:Fix Magento 2 Vault broken-link

content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md
=> Update PAD installment url

api/general/gateway-ids.md
=> DOCS-3777: Add PAD installments gateway id

content/payment-methods/amazon-pay.md
=> Corrections on Amazon pay

static/diagrams/src/sodexo-payment-flow.mmd
=> DOCS-3784:Update Sodexo diagram

content/integrations/cs-cart.md
=> PLGCSCS-139: Release of 1.6.1 of the CS-Cart plugin

content/integrations/prestashop-1-7.md
=> PRES-351: Release of the PrestaShop 1.7 plugin version 5.6.1

content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md
=> DOC-3791: Document extend expiration of order

content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md
=> DOCS-3786:Update broken links

content/integrations/woocommerce.md
This PR:
Update the download link of the WooCommerce plugin according a new release.
=> PLGWOOS-843: Release of 5.1.2 of the WooCommerce plugin

content/integrations/mijnwebwinkel.md
=> DOCS-3795:Fix Markdown check

content/integrations/mijnwebwinkel.md
=> DOCS-3795: Fix markdown check

content/integrations/mijnwebwinkel.md, content/payment-methods/pay-after-delivery-installments.md
=> DOCS-3798:Markdown daily check

content/integrations/oscommerce.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop-1-7.md, content/integrations/pwa-studio.md, content/integrations/scandipwa.md, content/integrations/shopify.md, content/integrations/shopware.md, content/integrations/virtuemart.md, content/integrations/vue-storefront.md, content/integrations/woocommerce.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> docs-3799: Update integrations order

content/payment-management/recurring-payments.md
=> DOCS-3793:Update Bancontact recurring specification

content/integrations/shopify.md
=>  DOCS-3794: Update Shopify order status

content/payment-methods/amazon-pay.md, content/payment-methods/apple-pay.md, content/payment-methods/bank-transfer.md, content/payment-methods/card-payments.md, content/payment-methods/cbc-kbc.md, content/payment-methods/direct-debit.md, content/payment-methods/gift-cards.md, content/payment-methods/giropay.md, content/payment-methods/google-pay.md, content/payment-methods/ideal.md, content/payment-methods/mybank.md, content/payment-methods/sofort.md, content/payment-methods/trustly.md, content/payment-methods/wechatpay.md
=> DOCS-3808: Change email adresses in Payment methods

content/integrations/prestashop-1-7.md
Change the download link of the plugin according a new version.
=> PRES-357: Release of 5.7.0 of the PrestaShop 1.7 plugin

content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md
=> DOCS-3775: Updating PAD terms and conditions

content/integrations/magento-1.md, content/payment-methods/sodexo.md, wordlist.txt
=> DOCS-3807: Update markdown broken link

content/payment-methods/ideal.md
=> DOCS-3803: Remove Handelsbanken from list

content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md
=> DOCS-3801: Update PAD docs

content/getting-started/glossary.md, content/payment-methods/moto.md
=> DOCS-3806: Add MOTO restriction

content/payment-management/recurring-payments.md
=> DOCS-3814: Add Direct debit requirement

content/integrations/woocommerce.md
Update download link of WooCommerce plugin.
=> PLGWOOS-851: Release of 5.2.1 of WooCommerce plugin

content/integrations/prestashop-1-7.md
This PR upgrades the download link of the plugin.  ~Do not merge until release process is completed.~
=> PRES-361:  Release of 5.8.0 of PrestaShop 1.7 plugin

content/integrations/prestashop-1-6.md
Update download link of the PrestaShop 1.6 plugin
=> PLGPRSS-483: Release of 3.10.0 of PrestaShop 1.6 plugin

content/payment-methods/paypal-direct.md, content/payment-methods/wechatpay.md
=> DOCS-3780: Document PayPal direct

content/payment-methods/paypal.md
=> Update PayPal link

content/accounting/accounting-integrations.md
=> DOCS-3862: Update Exact Online order

content/integrations/pwa-studio.md, wordlist.txt
This PR introduce some changes in the installation instructions and update the information about payment methods supported by this integration. 
~Please, don't merge until release is done. In the meantime it will be a draft PR.~
=> PWAS-31: Release of 1.1.0 of the PWA Studio integration

content/integrations/prestashop-1-7.md
=> Update PrestaShop documentation

landing-page/landing-page.html
=> DOCS-3879: Updated PAD logo on homepage

content/payment-methods/chargeback.md, content/payment-methods/chargebacks.md
=> DOCS:3887: Update Chargeback URL

content/my-account/payment-methods.md, content/payment-methods/paypal.md
=> DOCS-3888:Update PayPal Payment methods

content/payment-methods/trustly.md
=> DOCS-3898: Remove Shopify and Lightspeed from exceptions

content/integrations/magento-2.md, content/integrations/opencart.md
=> DOCS-3875:Add Magento 2 Hyva Checkout & Megawire modules

content/integrations/virtuemart-4.md
Update the link name for downloading the MultiSafepay plugin for VirtueMart 4
=> [Docs for Release 1.0.2] Change the plugin version in the download link

content/checkout/multiple.md, content/checkout/previous-release.md, content/checkout/single.md
=> DOCS-3901: Update payment component customer reference

content/payment-methods/card-errors.md, wordlist.txt
=> DOCS-3861:Update card errors

content/integrations/prestashop-1-7.md
This PR updates the download link of the PrestaShop 1.7 plugin
=> Release of the 5.10.0 of the PrestaShop 1.7 plugin

landing-page/landing-page.html
=> DOCS-3883: Remove Google Analytics from landing page

content/checkout/payment-links.md, content/integrations/virtuemart-4.md
=> DOCS-3969: Update Virtue Mart 4 change long

content/integrations/shopware.md
=> DOCS-3963: Add Amazon Pay and WeChat Pay to Shopware 6

content/integrations/lightspeed.md, content/payment-methods/monizze.md
=> DOCS-3921:Lightspeed explanation improvement

content/integrations/craft-commerce.md
=> DOCS-3983: Update craft commerce github link

content/payment-methods/card-errors.md
=> DOCS-3907: Authentication Errors Codes

content/point-of-sale/smartPOS-features.md, wordlist.txt
=> DOCS-3941: Create SmartPOS features doc

content/point-of-sale/smartPOS-features.md
=> DOCS-3988: Add correct category id

content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, content/point-of-sale/smartpos-solutions.md, content/point-of-sale/traditional-ctap.md, wordlist.txt
=> DOCS-3943: Document Traditional (CTAP) terminal

content/point-of-sale/smartpos-overview.md, content/point-of-sale/traditional-ctap.md
=> Docs 3944: Document SmartPOS overview

content/point-of-sale/event-notifications.md, content/point-of-sale/overview.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, content/point-of-sale/smartpos-overview.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-3989: Update :slug values

content/point-of-sale/event-notifications.md, content/point-of-sale/pos-overview.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, content/point-of-sale/smartpos-overview.md, content/point-of-sale/smartpos-solutions.md
This reverts commit e76267ddb4f773253e027939eca1060fa617fa43.
- Tested
=> Revert "DOCS-3989: Add /slug value"

content/point-of-sale/smartPOS-features.md
=> DOCS-4003: Fix SmartPOS-features front block

content/point-of-sale/smartPOS-features.md
=> DOCS-3991: Add cloud mode default PIN

api/general/gateway-ids.md
=> DOCS-4015: Add correct gateways ID for PAD

content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, wordlist.txt
=> DOCS-3987: Add IPEK validation

content/payment-methods/trustpay.md
=> DOCS-3967: Add supported countries for Trustly

content/point-of-sale/smartpos-solutions.md
=> DOCS-4016: Update Native-flow broken img

content/my-account/email-styling.md, content/payment-methods/klarna.md, wordlist.txt
=> DOCS-3965: Add new tokens for emails related to shipping data

content/my-account/payment-methods.md, content/payment-methods/alipay-plus.md, content/payment-methods/alipay.md, content/payment-methods/apple-pay.md, content/payment-methods/bancontact.md, content/payment-methods/bank-transfer.md, content/payment-methods/belfius.md, content/payment-methods/card-payments.md, content/payment-methods/cbc-kbc.md, content/payment-methods/direct-debit.md, content/payment-methods/dotpay.md, content/payment-methods/e-invoicing.md, content/payment-methods/eps.md, content/payment-methods/giropay.md, content/payment-methods/google-pay.md, content/payment-methods/ideal.md, content/payment-methods/in3.md, content/payment-methods/mybank.md, content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md, content/payment-methods/request-to-pay.md, content/payment-methods/riverty.md, content/payment-methods/sofort.md, content/payment-methods/trustly.md, content/payment-methods/trustpay.md, content/payment-methods/wechatpay.md, content/payment-methods/zinia.md
=> DOCS-4008: Update sites activation

content/payment-methods/paypal.md
=> DOCS-4019: Update PayPal activation

content/point-of-sale/event-notifications.md, content/point-of-sale/smartPOS-features.md
=> DOCS-4021: Add long press for Cloud mode

content/getting-started/account-balance.md, content/getting-started/account-users.md, content/getting-started/api-onboarding.md, content/getting-started/company-information.md, content/getting-started/create-account.md, content/getting-started/currencies.md, content/getting-started/email-styling.md, content/getting-started/getting-started-guide.md, content/getting-started/ibans.md, content/getting-started/invoices.md, content/getting-started/manage-my-account.md, content/getting-started/onboarding.md, content/getting-started/partner-primary-accounts.md, content/getting-started/payment-methods.md, content/getting-started/payouts.md, content/getting-started/prohibited-products-services.md, content/getting-started/security-and-legal.md, content/getting-started/sites.md
=> DOCS-4023: Merge getting started and my account

content/getting-started/api-onboarding.md, content/getting-started/prohibited-products-services.md
=> DOC-4029: Fix onboard account merge

content/getting-started/api-onboarding.md, content/getting-started/prohibited-products-services.md, content/point-of-sale/pos-overview.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-overview.md
=> DOCS-4030: add correct ParentDoc code

content/checkout/fastcheckout-shipping-options-request.md, content/checkout/fastcheckout.md, content/checkout/payment-links.md, content/checkout/payment-pages.md, content/developer/rounding-rule.md, content/payment-management/discounts.md, content/payment-management/second-chance.md, content/payment-management/split-payments.md, content/payment-management/success-pages.md, content/payment-methods/bancontact.md, content/payment-methods/betaalpermaand.md, content/payment-methods/cardholder-data.md, content/payment-methods/e-invoicing.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/manual-capture.md, content/payment-methods/moto.md, content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md, content/payment-methods/paypal.md, content/payment-methods/riverty.md, content/payment-methods/zero-authorization.md, content/point-of-sale/event-notifications.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-4025: Update Recipe link

content/payment-methods/klarna.md, content/payment-methods/riverty.md
=> DOCS-3971: Add  Lightspeed change of order status

content/accounting/accounting-integrations.md, content/accounting/reconciliation-via-api.md, content/accounting/reports.md, content/developer/email-authentication.md, content/developer/fastcheckout-android-sdk.md, content/developer/fastcheckout-ios-sdk.md, content/developer/rounding-rule.md, content/developer/troubleshooting.md
=> DOCS-4045: Update accounting and developer order

content/checkout/customization.md, content/checkout/fastcheckout-integration.md, content/checkout/fastcheckout-shipping-options-request.md, content/checkout/fastcheckout.md, content/checkout/multiple.md, content/checkout/payment-components.md, content/checkout/payment-links.md, content/checkout/payment-pages.md, content/checkout/previous-release.md, content/checkout/qr-payments.md, content/checkout/single.md
=> DOCS-4040: Update checkout order

content/payment-methods/alipay-plus.md, content/payment-methods/alipay.md, content/payment-methods/amazon-pay-integration.md, content/payment-methods/amazon-pay.md, content/payment-methods/apple-pay-direct.md, content/payment-methods/apple-pay.md, content/payment-methods/betaalpermaand.md, content/payment-methods/buy-now-pay-later.md, content/payment-methods/credit-debit-cards.md, content/payment-methods/e-invoicing.md, content/payment-methods/edenred.md, content/payment-methods/gift-cards.md, content/payment-methods/google-pay-direct.md, content/payment-methods/google-pay.md, content/payment-methods/in3.md, content/payment-methods/klarna.md, content/payment-methods/monizze.md, content/payment-methods/pay-after-delivery-installments.md, content/payment-methods/pay-after-delivery.md, content/payment-methods/paypal-direct.md, content/payment-methods/paypal.md, content/payment-methods/paysafecard.md, content/payment-methods/prepaid-cards.md, content/payment-methods/riverty.md, content/payment-methods/sodexo.md, content/payment-methods/testing.md, content/payment-methods/wallets.md, content/payment-methods/wechatpay.md, content/payment-methods/zinia.md
=> DOCS-4037:Update Wallet, Prepaid cards including Credit&debit cards

content/integrations/virtuemart-4.md
=> DOCS-4047: Release 2.0.1 for VirtueMart 4

content/point-of-sale/event-notifications.md
=> DOCS-4028: Update event notifications request

content/point-of-sale/smartpos-solutions.md
=> DOCS-4027: Pre-step for app2app and web2app

content/glossary/glossary.md
=> DOCS-4043: Add new category for glossary

content/integrations/shopware-6.md
=> DOCS-4054: Update Shopware 6 compatible versions

content/integrations/shopware-5.md
=> DOCS-3960: Add Shopware 5: Order flows

content/getting-started/currencies.md, content/getting-started/payouts.md
=> DOCS-4031: Update after Payouts section

content/payment-methods/google-pay-direct.md
=> DOCS-4010: Add customer.browser note

api/general/gateway-ids.md
=> DOCS-4062: Update Monizze gateway-ids

api/general/gateway-ids.md, content/getting-started/ibans.md, content/getting-started/invoices.md, content/getting-started/partner-primary-accounts-private.md, content/getting-started/sites.md
=> DOCS-4056: Add hidden partners to docs repo

content/getting-started/account-balance.md, content/getting-started/account-users.md, content/getting-started/company-information.md, content/getting-started/currencies.md, content/getting-started/email-styling.md, content/getting-started/ibans.md, content/getting-started/invoices.md, content/getting-started/partner-primary-accounts-private.md, content/getting-started/partner-primary-accounts.md, content/getting-started/payment-methods.md, content/getting-started/payouts.md, content/getting-started/sites.md
=> DOCS-4066: Add correct orderID

content/payment-methods/ideal.md
=> DOCS-4060: Add new iDeal issuers

content/integrations/prestashop-1-7.md
=> DOCS-4075: Additional step once PrestaShop 1.7 is installed

content/point-of-sale/hardware-setup.md, wordlist.txt
=> DOCS-4085: Create hardware-setup

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4089: Update POS troubleshooting email link

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4091: Update connectivity table

api/multisafepay-api/listbalances.md
=>  DOCS-4007: Add list balances

content/integrations/magento-2.md
=> DOCS-4093: Update MultiSafepay CatalogInventory module

content/integrations/prestashop-1-7.md
=> DOCS-4099: Update Prestashop 1.7

content/getting-started/onboarding-via-api.md
=> DOCS-3841: Add missing affiliates API

content/getting-started/payouts.md
=> DOCS-4110: Arrange manage my account order

content/payment-methods/bank-transfer.md, content/payment-methods/unmatched-payments-dutch.md, content/payment-methods/unmatched-payments-german.md
=> DOCS-3891: Fix resolving-unmatched-payments

content/developer/http-errors.md
=> DOCS-3998: Update the text typos

content/payment-methods/unmatched-payments-german.md
=> DOCS-4034: Fix markdown link error

content/payment-management/payment-statuses.md
=>  DOCS-4119: Update payment statusses

content/payment-methods/wallets.md
=> DOCS-4127:Fix integration broken link

content/point-of-sale/pos-overview.md
=> DOCS-4129: Update POS overview

content/getting-started/payouts.md
=> DOCS-4063: Add autopayout instructions report

content/payment-methods/interchange.md
=> DOCS-4131: Card payment pricing models

.gitignore, content/payment-methods/betaalpermaand.md, content/point-of-sale/event-notifications.md, content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, content/point-of-sale/smartpos-overview.md, content/point-of-sale/smartpos-solutions.md, content/point-of-sale/traditional-ctap.md, docs/archive/payment-methods.md
=> DOCS 4144 BPM discontinued

content/checkout/payment-pages.md
=> DOCS 4145 change localization instructions

api/general/transaction-expiration.md, content/payment-methods/klarna.md
=> DOCS 4140 change Klarna expiration time

content/payment-methods/in3.md
=> DOCS 4148 in3 amount limit

content/point-of-sale/smartpos-activation.md, content/point-of-sale/traditional-ctap.md
=> DOCS 4149 new instructions Terminal onboarding

content/payment-methods/card-payment-errors.md
=> DOCS-4135: Add 2 authorization error codes

content/payment-methods/card-payment-errors.md
=> DOCS-4135 Add 2 authorization error codes

content/accounting/accounting-integrations.md
=> DOCS-4052 Hide Exact

content/integrations/prestashop-1-7.md
=> DOCS-4160: Update the download link for PrestaShop 1.7 plugin

content/integrations/opencart-4.md
=> DOCS-4159: Fix supported versions of OpenCart 4 plugin

content/integrations/prestashop-1-7.md
Changing the download URL to our plugin for PrestaShop 1.7
=> DOCS-4177: Release of 5.13.0 for PrestaShop 1.7

content/payment-methods/amazon-pay.md
=> DOCS-4166 Amazonpay plugins

content/integrations/webshop-access.md
=> DOCS-4198: Integration Troubleshooting guide

content/point-of-sale/event-notifications.md, content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-overview.md, content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, content/point-of-sale/smartpos-overview.md, content/point-of-sale/smartpos-solutions.md, content/point-of-sale/traditional-ctap.md
=> DOCS-4209: POS modifications pilot and webhook

content/integrations/lightspeed.md
=> DOCS-4210: Lightspeed troubleshooting guide

content/integrations/partner-integrations.md
=> DOCS-4187: Add Pronamic Pay

content/point-of-sale/event-notifications.md
=> DOCS-4211: event notifications

content/payment-methods/sofort.md
=> DOCS-4164: Sofort

content/integrations/prestashop-1-7.md
=> [PrestaShop 1.7] Adding direct download link at GitHub

content/integrations/prestashop-1-6.md
=> DOCS-4218: Release of 3.13.0 of the PrestaShop 1.6 plugin

content/integrations/shopware-6.md
=> DOCS-4219: [Shopware 6] - Changes in the documentation: link, update info and versions

content/checkout/multiple.md
=> DOCS-4222 add example files comp

content/checkout/multiple.md
=> DOCS-4221 Component

content/checkout/multiple.md
=> DOCS-4221: Component

content/checkout/multiple.md
=> DOCS-4221: Components

content/accounting/accounting-integrations.md
=> DOCS-4175: Exact online

content/integrations/magento-2.md
=> DOCS-4245 Order save inspector

content/integrations/magento-2.md
=> DOCS-4260 M2 Troubleshooting guide

content/integrations/woocommerce.md
=> DOCS-4195 WooCommerce troubleshooting section

content/payment-methods/ideal.md
=> DOCS-4266: iDeal 2.0 migration - guide

content/payment-management/success-pages.md
=> DOCS-4268: Clarifications SP

content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-troubleshooting.md
=> DOCS-4279: Sunmi guides

content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-troubleshooting.md
=> DOCS-4280: Sunmi guides 2

content/integrations/partner-integrations.md
=> DOCS-4281: Pronamic links

content/integrations/partner-integrations.md
=> DOCS-4235: Gomage

content/integrations/prestashop-1-7.md
This PR update the download link for the new version.
=> DOCS-4282: Release of 5.14.2 of the PrestaShop plugin

content/payment-methods/pay-after-delivery.md
=> DOCS-4286 PAD gateway switch

content/payment-methods/giropay.md
=> DOCS-4269: Giropay July

api/general/introduction.md
=> DOCS-4289: video

content/point-of-sale/smartPOS-features.md
=> DOCS-4293: feature listing

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4294: RMA

content/integrations/ccv-shop.md, content/integrations/woocommerce.md, content/point-of-sale/pos-troubleshooting.md
=> DOCS-4292 Woo, CCV, 1000

content/payment-methods/request-to-pay.md
=> DOCS-4265: request to pay

content/integrations/webshop-access.md
=> DOCS-4299 Troubleshooting guide

content/payment-methods/card-payment-pricing-models.md
=> DOCS-4300 Fix duplicates

content/payment-methods/3ds2.md, content/payment-methods/card-payments.md, content/payment-methods/cardholder-data.md
=> DOCS-4304 required fields

content/point-of-sale/smartpos-solutions.md
=> DOCS-4306 deeplink features

content/point-of-sale/smartPOS-features.md
=> DOCS-4308 Add closing order flow

content/integrations/ccv-shop.md
This PR updates the documentation for the integration of CCV Shop with MultiSafepay.  
Changes made:  
- Added more information in the installation and configuration guide.
- Added in the user guide, a new section about sorting the payment methods.
These updates provide clearer and more detailed instructions for users integrating MultiSafepay with CCV Shop, improving the user experience and facilitating the configuration and use of the available functionalities.
=> DOCS-4311: Update CCV-Shop adding information about sorting the payment methods and how to get an API Key

content/point-of-sale/hardware-setup.md
=> DOCS-4312 security measures terminal

content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartPOS-features.md
=> DOCS-4315: POS Troubleshooting addition and closing order flow

content/accounting/reports.md, content/point-of-sale/smartpos-activation.md
=> DOCS-4316: API key POS & Acc Exp group

content/accounting/reports.md
=> DOCS-4317: Reporting troubleshooting section

content/payment-methods/in3.md
=> DOCS-4318: Amount limits in3

content/integrations/lightspeed.md
=> DOCS-4309: enable lightspeed payment methods

content/integrations/lightspeed.md, content/payment-methods/gift-cards.md, content/payment-methods/in3.md
=> DOCS-4310: Coupon refunds

content/payment-methods/in3.md
=> DOCS-4320:Add information in3 B2B

content/integrations/magento-2.md, content/integrations/webshop-access.md
=> DOCS-4305: M2 Vault/ Integration Guide

content/payment-methods/in3.md
=> DOCS-4330: Broken image fixes

content/payment-methods/trustly.md
=> DOCS-4179: Trustly allowed countries

content/payment-methods/betaalpermaand.md, content/payment-methods/giropay.md, content/payment-methods/sofort.md
=> DOCS-4338: add deprecated status to outdated payment methods/int

content/integrations/opencart-4.md
=> DOCS-4335: Fix glossary element not showing pop-up (backend)

content/checkout/multiple.md
=> DOCS-4341: Format issues at checkout > multiple payment methods

content/checkout/multiple.md
=> DOCS-4343: format fix checkout page

content/payment-methods-test/card-payment-pricing-models.md
=> DOCS-4346: Card payment pricing page duplication

content/payment-methods/card-payment-pricing-models-test.md
=> DOCS-TEST3

content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/prestashop-1-7.md, content/integrations/shopware-5.md, content/integrations/shopware-6.md, content/integrations/virtuemart-3.md, content/integrations/virtuemart-4.md
=> DOCS-4350: modification to our integrations page

content/integrations/prestashop-1-7.md
=> DOCS-TESTZ

content/integrations/drupal.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop.md
=> DOCS-4352: remove php version info in Drupal page

content/payment-methods/card-payment-pricing-models-2.md
=> DOCS-TESTV

content/point-of-sale/smartPOS-features.md
=> DOCS-4351: info closing balance

content/integrations/shopify-beta.md
Add the Direct Debit app to Shopify page
=> DOCS-4355: Add the Direct Debit app to Shopify page

content/payment-management/chargebacks.md, content/payment-methods/3ds2.md, content/payment-methods/card-payment-errors.md, content/payment-methods/card-payment-pricing-models.md, content/payment-methods/card-payments.md, content/payment-methods/card-refunds.md, content/payment-methods/cardholder-data.md, content/payment-methods/giropay.md, content/payment-methods/manual-capture.md, content/payment-methods/mbway.md, content/payment-methods/moto.md, content/payment-methods/multibanco.md, content/payment-methods/mybank.md, content/payment-methods/request-to-pay.md, content/payment-methods/sofort.md, content/payment-methods/trustly.md, content/payment-methods/trustpay.md, content/payment-methods/uncleared.md, content/payment-methods/zero-authorization.md
=> DOCS-4353: fix order

content/payment-methods/ideal.md
=> DOCS-4362: ideal qr change broken link

content/payment-methods/in3.md
=> DOCS-4365: in3 to iDEAL in3

content/integrations/prestashop.md, content/payment-methods/amazon-pay.md, content/payment-methods/cbc-kbc.md, content/payment-methods/edenred.md, content/payment-methods/in3.md, content/payment-methods/monizze.md, content/payment-methods/paypal.md, content/payment-methods/paysafecard.md, content/payment-methods/riverty.md, content/payment-methods/sodexo.md, content/payment-methods/wechatpay.md
=> DOCS-4366: Fix broken URL's for PrestaShop

content/integrations/partner-integrations.md, content/payment-methods/in3.md
=> DOCS-4367: Update supported payment methods logic4

content/integrations/webshop-access.md
=> DOCS-4368: corrections on Integration Troubleshooting Guide page

content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-overview.md, content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-4364: Add POS guides

content/integrations/webshop-access.md, content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartpos-overview.md, content/point-of-sale/traditional-ctap.md
=> DOCS-4369: Move hardware under SmartPOS

content/integrations/webshop-access.md
=> DOCS-4368A: small corrections integration troubleshooting

content/integrations/webshop-access.md
=> DOCS-4371A: icon addition, change

content/integrations/webshop-access.md
=> DOCS-4324: Small adjustments to the integration troubleshooting guide

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4370: IPEK

content/payment-methods/card-payment-errors.md
=> DOCS-4285: Add response code 3100 to card payment errors

content/payment-methods/apple-pay-direct.md
=> DOCS-4283: Remove komma in text-line validation_irl: calidationUrl,

content/payment-methods/card-payment-errors.md
=> DOCS-4258A: remove response code 3100 to card payment errors

content/point-of-sale/pos-overview.md
=> DOCS-4377C: remove deprecated images POS features

content/point-of-sale/pos-overview.md
=> DOCS-4377d: remove deprecated images POS features

content/point-of-sale/pos-overview.md
=> Docs 4377 e

content/point-of-sale/pos-overview.md
=> Docs 4377 f

api/general/introduction.md
=> Docs 4183 a

api/general/introduction.md, content/point-of-sale/pos-overview.md
=> Docs 4377 g

landing-page/landing-page.html
=> DOCS-4383: testing on dark mode docs main page

landing-page/landing-page.html
=> Docs 4383 a

landing-page/landing-page.html
=> Docs 4383 c

content/point-of-sale/smartPOS-features.md
=> DOCS-4387: Closing balance

content/payment-methods/bizum.md, content/payment-methods/cbc-kbc.md, content/payment-methods/direct-debit.md, content/payment-methods/dotpay.md, content/payment-methods/eps.md, content/payment-methods/giropay.md, content/payment-methods/ideal.md, content/payment-methods/mbway.md, content/payment-methods/mybank.md, content/payment-methods/request-to-pay.md, content/payment-methods/sofort.md, content/payment-methods/trustly.md, content/payment-methods/trustpay.md
=> DOCS-4388: Create Bizum docs page. Reorder banking methods

content/point-of-sale/smartpos-activation.md
=> DOCS-4389: add logo

content/point-of-sale/hardware-setup.md, content/point-of-sale/smartPOS-features.md
=> DOCS-4392 Add POS screenshots

content/point-of-sale/smartPOS-features.md
=> DOCS-4392: Add POS screenshots. Modifications position

content/point-of-sale/smartpos-solutions.md
=> Docs 4194 a

content/point-of-sale/event-notifications.md, content/point-of-sale/hardware-setup.md, content/point-of-sale/pos-overview.md, content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-activation.md, content/point-of-sale/smartpos-overview.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-4401: POS countries

landing-page/landing-page.html
=> DOCS-4383B: testing on dark mode docs main page

content/payment-methods/klarna.md
=> DOCS-4402: Klarna refund guide

content/accounting/accounting-integrations.md
=> DOCS-4189: Update URL Bookkeeping

content/payment-methods/bancontact.md, content/payment-methods/testing.md
=> DOCS-4397: Bancontact direct not available

content/payment-methods/credit-debit-cards.md
=> DOCS-4405: update mastercard logo.

content/integrations/shopify.md
=> DOCS-4152: Add payment methods

content/payment-methods/testing.md
=> DOCS-4174: Add MBWAY - MULTIBANCO testing information in docs.

content/integrations/shopify-beta.md, wordlist.txt
This pull request includes a small update to the `content/integrations/shopify-beta.md` file. The change adds a new payment method link:
* Added a link for Bizum payment method to the list of available payment options.
=> DOCS-4445: Add Bizum Shopify app link to the Shopify document

content/integrations/shopify-beta.md
This pull request includes updates to the Shopify integration documentation. The changes focus on adding detailed instructions for processing refunds and troubleshooting common issues.
* [`content/integrations/shopify-beta.md`](diffhunk://#diff-7e883a2acfe468f4adefd1b9f83c96436d1967a2247d4776de8710695c243387L95-R136): Added a detailed section on how to process refunds in the Shopify backend, including step-by-step instructions and important notes on refund limitations and status updates.
* [`content/integrations/shopify-beta.md`](diffhunk://#diff-7e883a2acfe468f4adefd1b9f83c96436d1967a2247d4776de8710695c243387L95-R136): Introduced a new troubleshooting section with instructions on how to find the Payment Order ID in Shopify to assist with order and refund status issues.
=> DOCS-4446: Add information related to refunds in Shopify document

content/payment-management/webhook.md, content/payment-methods/bancontact.md
=> DOCS-4431: webhook response

content/integrations/magento-2.md
=> DOCS-4305: Fix Magento Vault section

content/integrations/shopify-payment-apps.md
This pull request includes a small change to the `content/integrations/shopify-payment-apps.md` file. The change adds a new payment option to the list of Shopify Payments Apps.
* Added Multibanco payment option to the list of Shopify Payments Apps.
=> DOCS-4490: Add link of the Multibanco Shopify app

content/point-of-sale/hardware-setup.md
=> DOCS-4497: Set update time for terminal app

api/general/gateway-ids.md
=> DOCS-4420: add Beauty Cadeau gift card

content/payment-methods/in3.md
=> DOCS-4467: in3 order expiry

api/general/error-reference.md, api/multisafepay-api/createaffiliate.md, content/developer/troubleshooting.md
=> DOCS-4248: Clarify auth bearer

content/point-of-sale/smartPOS-features.md
=> DOCS-4494: New items POS draft. Tipping and hide MSP logo

content/getting-started/account-users.md
=> DOCS-4486: Add info permissions to manage SmartPOS terminals

content/getting-started/payouts.md
=> DOCS-4512: Update currency list for payouts

content/accounting/reconciliation-via-api.md
=> DOCS-4513: Update API Reconciliation page. Add list transactions

api/multisafepay-api/getubo.md, api/multisafepay-api/listubos.md
=> DOCS-4444: Missing information about UBO IDs

content/checkout/customization.md, content/checkout/payment-pages.md, content/getting-started/sites.md
=> DOCS-4523: New MCP Website design

content/point-of-sale/smartPOS-features.md
=> DOCS-4363: Check closing balance

content/point-of-sale/smartpos-overview.md
=> DOCS-4538: Integration guide POS. SmartPOS terminals page done

content/payment-methods/paypal-direct.md
=> DOCS-4540: PayPal; smart button renamed

.github/workflows/spellchecker.yml, content/getting-started/onboarding-via-api.md, content/payment-methods/billink.md, content/payment-methods/testing.md
=> DOCS-4550: Add how to test Billink to docs

content/checkout/payment-links.md, content/payment-methods/manual-capture.md
=> DOCS-4551: New features for MCP: Manual Capture and notification options for payment links.

content/payment-methods/billink.md
=> DOCS-4553: Add information about tax restrictions Billink

content/developer/tls-protocols.md
=> DOCS-4555: Add link to TLS protocols

content/point-of-sale/hardware-setup.md
=> DOCS-4557: Automatic PCI Reboot for terminals

content/integrations/lightspeed.md
=> DOCS-4560: Lightspeed -- Include note about payment method amount limits

content/developer/tls-protocols.md
=> DOCS-4573: Add TLS 1.3

content/point-of-sale/pos-card-payment-flow.md
=> DOCS-4580: New page for POS card payment flow

content/payment-methods/apple-pay-direct.md
=> DOCS-4544: Applepay direct guide

content/integrations/archived-plugins.md, content/integrations/craft-commerce.md, content/integrations/drupal.md, content/integrations/lightspeed.md, content/integrations/magento-1.md, content/integrations/magento-2.md, content/integrations/odoo.md, content/integrations/opencart-4.md, content/integrations/oscommerce.md, content/integrations/our-integrations.md, content/integrations/prestashop-1-6.md, content/integrations/prestashop.md, content/integrations/scandipwa.md, content/integrations/shopify-payment-apps.md, content/integrations/shopify.md, content/integrations/shopware-5.md, content/integrations/shopware-6.md, content/integrations/virtuemart-3.md, content/integrations/virtuemart-4.md, content/integrations/vue-storefront.md, content/integrations/woocommerce.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> DOCS-4532: Deprecated plugin solutions

content/payment-methods/mbway.md, content/payment-methods/multibanco.md
=> DOCS-4587: Refunds for MB WAY and Multibanco limited to 3 months

content/payment-methods/testing.md
=> DOCS-4585: Delete 3d enrolled test details 00009

content/payment-methods/billink.md
=> DOCS-4588: Updates on API refund and Billink payment method

content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-4584: Enable digital keypad on SmartPard

api/multisafepay-api/getsite.md
=> DOCS-4594: Add auth info

content/checkout/payment-links.md
=> DOCS-4603: Add status declined on docs for payment links

content/checkout/payment-links.md, content/payment-methods/apple-pay-direct.md
=> DOCS-4604: Fix links for Apple Pay direct

content/payment-methods/buy-now-pay-later.md, content/point-of-sale/smartPOS-features.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-4599: Add Order ID validation rules to the POS docs

api/multisafepay-api/listaffiliates.md
=> DOCS-4606: Add query parameters for List affiliates endpoint

api/multisafepay-api/createorder.md, api/multisafepay-api/getorder.md, api/multisafepay-api/updateorder.md
=> DOCS-4583: Review use of Merchant transaction id >> PSP ID

content/integrations/archived-plugins.md
=> DOCS-4609: fix broken links archived plugins

api/general/introduction.md, content/developer/wrappers-and-sdks.md
=> DOCS-4614: Replace Python wrapper with Python SDK

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4370A: POS chrome & IPEK

content/point-of-sale/pos-troubleshooting.md
This reverts commit 75326692785017cfb0fbfcf3ef8cc6098904a1d6.
- Tested
=> Revert "DOCS-4370A: POS chrome & IPEK (#3308)"

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4370A: POS Chrome and IPEK

content/point-of-sale/pos-troubleshooting.md
=> DOCS-4370B: POS Chrome and IPEK

content/payment-management/chargebacks.md
=> DOCS-4525: Chargeback documentation update

content/payment-management/chargebacks.md, content/payment-methods/google-pay-direct.md, content/point-of-sale/pos-troubleshooting.md
=> DOCS-4181: Add information about activation in Google environment

content/integrations/archived-plugins.md, content/integrations/odoo.md, content/integrations/oscommerce.md
=> DOCS-4622: Odoo 13 is end-of-life

api/multisafepay-api/chargeaffiliate.md, api/multisafepay-api/createaffiliate.md, api/multisafepay-api/getterminalgroups.md, api/multisafepay-api/listaffiliates.md, api/multisafepay-api/listterminals.md
=> DOCS-4627: Auth bearer for POS and affiliate endpoints

content/payment-management/webhook.md
=> DOCS-4635: Specify POST method for orders with webhook set in MCP

content/getting-started/payouts.md, content/point-of-sale/unreferenced-refunds.md
=> DOCS-4637: Cloud POS unreferenced

content/integrations/woocommerce.md
=> DOCS-4640: Woocomerce: Payment component QR activation instructions

content/point-of-sale/pos-troubleshooting.md, content/point-of-sale/smartPOS-features.md
=> DOCS-4435: 10008 error sunmi

content/payment-methods/alipay-plus.md, content/point-of-sale/pos-overview.md
=> DOCS-4647: Alipay + POS. ACtivation and enable.

content/getting-started/sites.md, content/point-of-sale/smartpos-solutions.md
=> DOCS-4645: api key instructions pos order creation

api/general/error-reference.md, content/integrations/webshop-access.md
=> DOCS-4649: Remove part of the explanation for error 1034

content/integrations/our-integrations.md, content/integrations/prestashop.md, content/payment-methods/google-pay-direct.md, content/payment-methods/google-pay.md
=> DOCS-4643: Review Googlepay instructions Plugins

content/point-of-sale/smartpos-activation.md
=> DOCS-4650: fix broken anchor link

content/integrations/lightspeed.md
=> DOCS-4662: Remove upgrade notice in Lightspeed docs page

content/getting-started/sites.md, content/point-of-sale/unreferenced-refunds.md
=> DOCS-4674: Unreferenced refunds: final version

.github/workflows/actions_checkout_v3.code-search, .github/workflows/banned-words.yml, .github/workflows/create-diagrams.yml, .github/workflows/external-urls.yml, .github/workflows/mail checker.yml, .github/workflows/manual.yml, .github/workflows/markdown-link-check-daily.yml, .github/workflows/readme-docs-sync.yml, .github/workflows/spellchecker-weekly.yml, .github/workflows/spellchecker.yml, .github/workflows/urlchecker.yml
=> DOCS-4673: ReadMe migration to v10: Refactored

content/getting-started/account-users.md
=> DOCS-4675: testing repo for refactored

content/getting-started/company-information.md, content/payment-methods/zinia.md
=> DOCS-4673B: fixing repo

content/integrations/archived-plugins.md, content/integrations/craft-commerce.md, content/integrations/odoo.md, content/integrations/oscommerce.md, content/integrations/scandipwa.md, content/integrations/virtuemart-3.md, content/integrations/vue-storefront.md, content/integrations/x-cart.md, content/integrations/zen-cart.md
=> DOCS-4680B: debugging readme v10

content/test/unreferenced-refunds.md
=> DOCS-4683A

.github/workflows/readme-docs-sync.yml
=> DOCS-4694: DOCS repo: update workflow

openapi/components/schemas/Status.yaml
=> DOCS-4692: Get order - add chargeback as possible status for order
