MultiSafepay/docs

- content/api/payment_methods/post-order-banktrans.md
> DOCS: added bt code to code block

- content/payment-methods/banks/dotpay/dotpay-how-does-it-work.md
- static/css/main.css
> DOCS: mobile

- content/payment-methods/wallet/paypal/activate-paypal.md
> DOCS: resized paypal images

- content/api/payment_methods/post_order_gift_card.md
- content/integrations/plugins/magento1/manual.md
- content/integrations/plugins/magento2/manual.md
- content/payment-methods/prepaid-cards/gift-cards/which-gift-cards-are-accepted-by-multisafepay.md
- static/.htaccess
> DOCS: Fixes for critical moz notices

- static/.htaccess
> DOCS: Update .htaccess

- static/css/api.css
- static/css/main.css
> DOCS-789: better tables

- content/faq/general/which-currencies-are-supported-by-multisafepay.md
- content/payment-methods/credit-cards/creditcards/credit-card-how-does-it-work.md
> DOCS-736: Added all currencies available for Visa, MC and Maestro

- content/api/payment_methods/post-order-banktrans-redirect.md
- content/api/payment_methods/post-order-banktrans.md
> DOCS-808: realigned redict banktransfer code

- content/integrations/plugins/cs-cart/faq/available-payment-methods-cs-cart.md
- content/integrations/plugins/drupal7/faq/available-payment-methods-drupal.md
- content/integrations/plugins/drupal8/faq/available-payment-methods-drupal8.md
- content/integrations/plugins/magento1/faq/available-payment-methods-magento1.md
- content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md
- content/integrations/plugins/opencart/faq/available-payment-methods-opencart.md
- content/integrations/plugins/prestashop-1-6/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md
- content/integrations/plugins/shopware6/faq/available-payment-methods-shopware5.md
- content/integrations/plugins/virtuemart/faq/available-payment-methods-virtuemart.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
- content/integrations/plugins/x-cart/faq/available-payment-methods-x-cart.md
- content/integrations/plugins/zencart/faq/available-payment-methods-zen-cart.md
> DOCS: payment-methods are now up to date till 8th of january

- content/integrations/hosted/shoptrader/_index.md
- content/integrations/hosted/shoptrader/faq/does-globecharge-support-multisafepay.md
- content/integrations/hosted/shoptrader/faq/refunding-shoptrader.md
- content/integrations/hosted/shoptrader/manual.md
> DOCS-797: checked and fixed shoptrader names in shoptrader section

- content/integrations/hosted/shoptrader/_index.md
- content/integrations/hosted/shoptrader/faq/does-globecharge-support-multisafepay.md
- content/integrations/hosted/shoptrader/faq/refunding-shoptrader.md
- content/integrations/hosted/shoptrader/manual.md
- static/css/main.css
> DOCS-797: Shoptrader text

- content/integrations/plugins/prestashop-1-7/_index.md
> DOCS-810: Updated downloaded version presta 1.7

- layouts/_default/baseof.html
> DOCS-805: added-cookieconsent

- .github/CODEOWNERS
> DOCS: Update CODEOWNERS

- layouts/index.html
- static/css/main.css
> DOCS: Added ssl alert on home page

- content/payment-methods/banks/sofort-banking/what-is-sofort-banking.md
> DOCS-741 : Updated - fix typo

- content/faq/gdpr/can-customers-request-to-have-data-delete-removed-in-accordance-with-the-right-privacy-by-design.md
- content/faq/gdpr/who-can-access.md
> DOCS-817: Fix broken FAQ GDPR links

- layouts/index.html
> DOCS-841: Remove ssl msg

- content/integrations/plugins/drupal8/_index.md
- content/integrations/plugins/shopware6/_index.md
> DOCS-822: Add missing Shopware 6 and Drupal 8 plug-ins

- content/integrations/plugins/shopware6/_index.md
> DOCS-820: Shopware6 remove beta sentence

- content/integrations/plugins/drupal8/manual.md
- content/integrations/plugins/magento1/manual.md
- content/integrations/plugins/magento2/manual.md
- layouts/_default/baseof.html
> DOCS-824: added contact info in plugin where missing

- content/tools/tokenization/tokenization-api-level.md
> DOCS-829: Change Tokenization link

- static/css/main.css
> DOCS-798: payment table styling

- static/css/main.css
> DOCS-793: fix-uneven-arrow

- content/integrations/sdk/fastcheckout-android/manual.md
- layouts/shortcodes/zoom_able.html
- static/css/main.css
> DOCS-799: zoom without modal

- .github/banned_words.txt
> INTGRTN-1380: Add MultiSafepay Control Panel to banned words list

- layouts/partials/call_to_action.html
> DOCS-850: Make Google and iOS banner clickable

- layouts/partials/single-faq.html
> DOCS-909: url > anchor

- content/faq/finance/set-up-exact-online-platform.md
> DOCS-786: Update exact online instructions

- content/api/gateways/get_issuers.md
> DOCS-934: Correct spelling

- layouts/_default/list.html
> DOCS-951: Added extra button

- layouts/partials/edit-page.html
> DOCS-851: added-trim-index_md

- static/css/api.css
> DOCS: added tab-size to api json

- content/api/_index.md
- content/faq/PSD2/can-I-apply-surcharges-to-consumers-outside-the-European-Union.md
- content/integrations/hosted/dynamicweb/_index.md
- content/integrations/hosted/easywebshop/_index.md
- content/integrations/plugins/magento1/_index.md
- content/integrations/plugins/magento2/_index.md
- content/integrations/plugins/oscommerce/_index.md
- content/integrations/sdk/fastcheckout-android/_index.md
- content/integrations/sdk/fastcheckout-ios/_index.md
> DOCS-879: seo metadata fixes

- content/faq/general/ip-ranges.md
> DOCS-986: added-read-more

- content/faq/api/google-analytics-tracking.md
- content/faq/api/xml-api.md
- content/faq/errors-explained/iframe.md
- content/faq/risk-and-fraud/change-of-company-details.md
- content/faq/risk-and-fraud/new-bank-account.md
- content/integrations/accounting and bookkeeping/AFAS/_index.md
- content/integrations/hosted/lightspeed/faq/lightspeed-orderid.md
- content/integrations/plugins/cs-cart/manual.md
- content/integrations/plugins/magento2/manual.md
- content/payment-methods/banks/idealqr/what-is-idealqr.md
- content/payment-methods/banks/trustly/what-is-trustly.md
- content/payment-methods/billing-suite/pay-after-delivery/refund-pay-after-delivery.md
- content/tools/recurring-payments/recurring-payments-how-does-it-work.md
- layouts/shortcodes/introduction_hosted.html
- layouts/shortcodes/introduction_plugin.html
> DOCS-972: added-line-break-after-links

- content/api/payment_methods/post-order-bancontact.md
- content/api/payment_methods/post-order-bancontactqr.md
> DOCS-1002: fixed-bancontact-url-api

- layouts/_default/faqdetail.html
- layouts/_default/paymentdetail.html
- layouts/_default/single.html
- layouts/api/list.html
- static/css/main.css
- static/js/scroll-menu.js
- static/js/scroll-offset.js
> DOCS-837: Anchor below header

- content/faq/finance/VAT-general-questions.md
- content/faq/getting-started/i-want-to-process-payments-using-multisafepay-but-i-still-have-a-contract-with-a-different-psp.md
- content/integrations/_index.md
- content/integrations/community/_index.md
- content/integrations/hosted/_index.md
- content/integrations/hosted/shoptrader/faq/does-globecharge-support-multisafepay.md
- content/integrations/plugins/drupal8/faq/refunding-drupal.md
- content/integrations/plugins/magento2/faq/payment-links-in-order-confirmation-for-backend-orders.md
- content/integrations/plugins/opencart/faq/how-can-i-update-the-plugin-for-opencart.md
- content/integrations/plugins/oscommerce/faq/refunding-oscommerce.md
- content/integrations/plugins/prestashop-1-6/faq/refunding-prestashop.md
- content/integrations/plugins/prestashop-1-7/faq/refunding-prestashop.md
- content/integrations/plugins/zencart/faq/how-can-i-update-the-plugin-for-zen-cart.md
- content/integrations/sdk/_index.md
- content/integrations/wrappers/_index.md
- content/payment-methods/credit-and-debit-cards/creditcards/what-is-a-chargeback.md
- content/tools/email-template/basic-information-on-email-template.md
- content/tools/email-template/body-and-html.md
- content/tools/multisafepay-control/add-website.md
> DOCS-880: seo content duplicates

- content/payment-methods/banks/bank-transfer/how-does-bank-transfer-work.md
> DOCS-1019: added-missing-word

- static/css/main.css
> DOCS-839: hide-cookie-button-on-consent

- content/payment-methods/credit-and-debit-cards/creditcards/chargebacks/dispute-chargeback.md
- layouts/shortcodes/alert-notice.html
- static/css/main.css
> DOCS: anchor disputes

- layouts/api/list.html
- layouts/partials/manual.html
- static/css/main.css
- static/js/scroll-menu.js
- static/js/scroll-offset.js
> DOCS: Scroll offsett main pages

- content/integrations/plugins/x-cart/_index.md
- content/integrations/plugins/x-cart/changelog.md
- content/integrations/plugins/x-cart/manual.md
> Release of X-Cart plugin 2.3.0

- content/faq/getting-started/can-i-test-with-multisafepay.md
- content/faq/getting-started/test-payment-details.md
- content/payment-methods/billing-suite/klarna/refund-klarna.md
- content/payment-methods/wallet/alipay/alipay-how-does-it-work.md
- content/tools/recurring-payments/recurring-payments-how-does-it-work.md
> DOCS-1005: added alert blocks

- layouts/_default/baseof.html
> DOCS-864: added-hotjar

- layouts/_default/baseof.html
- static/css/main.css
> DOCS-805: styling-cookie-popup

- static/css/main.css
> DOCS: change cookie color

- content/integrations/plugins/cs-cart/_index.md
- content/integrations/plugins/cs-cart/changelog.md
- content/integrations/plugins/cs-cart/faq/available-payment-methods-cs-cart.md
> CS-Cart plugin 1.5.0 release

- content/integrations/plugins/drupal8/_index.md
- content/integrations/plugins/drupal8/changelog.md
- content/integrations/plugins/drupal8/faq/available-payment-methods-drupal8.md
> Release of Drupal 8 1.1

- content/integrations/plugins/drupal7/_index.md
- content/integrations/plugins/drupal7/changelog.md
- content/integrations/plugins/drupal7/faq/available-payment-methods-drupal.md
> Release of Drupal 7 2.2.0

- content/integrations/plugins/magento2/_index.md
- content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md
> Release of Magento2 1.11.0

- content/integrations/plugins/shopware6/_index.md
- content/integrations/plugins/shopware6/faq/available-payment-methods-shopware6.md
> Release of Shopware 6 1.2.0

- content/integrations/plugins/opencart/_index.md
- content/integrations/plugins/opencart/changelog.md
- content/integrations/plugins/opencart/faq/available-payment-methods-opencart.md
> Release of OpenCart 2.3.0

- config.toml
This PR fix the missing PWA integration section on the navbar
> DOCS-1105: Add missing PWA on navbar

- content/integrations/pwa/vue-storefront/_index.md
This PR hide the subscribe newsletter section on vue storefront page.
http://localhost:1313/integrations/pwa/vue-storefront/
> DOCS-1119: Hide newsletter section on VSF page

- content/api/reference/tokenization-create-token-transaction.md
> DOCS-1124: updated create token transaction type

- content/api/discount/discount-order-rule.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-klarna.md
- content/api/payment_methods/post-order-payafter.md
- content/api/reference/plugin_info.md
On multiple sections we have http instead of https, so fixed those cases
> DOCS-1150: Fix multiple https

- content/api/payment_methods/post_order_applepay.md
> DOCS-1337: Makes sense now

- content/integrations/plugins/prestashop-1-7/_index.md
- content/integrations/plugins/prestashop-1-7/changelog.md
> Release of PrestaShop 1.7 4.6.1

- content/integrations/plugins/opencart/manual.md
> DOCS-1169: added Site Code AKA Secure Code for OpenCart

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
> Release of WooCommerce 3.5.1

- content/api/reference/tokenization-original-transaction.md
> DOCS-1137: added-tokenization-info

- content/api/tools/manual_capture_full.md
- content/api/tools/manual_capture_partial.md
> DOCS-1199: fixed-api-manual-capture-info

- content/api/tools/manual_capture_full.md
- content/api/tools/manual_capture_partial.md
> DOCS-1207: fixed-manual-capture-api2

- content/integrations/plugins/magento2/_index.md
> Release of Magento 2 1.12.0

- content/integrations/plugins/shopware6/_index.md
> Release Shopware 6 1.3.0

- content/integrations/plugins/shopware6/faq/how-to-refund-within-shopware6.md
> DOCS-1161: Add instructions for Shopware 6 refund

- content/integrations/plugins/magento1/manual.md
> DOCS-1272: Mage One info on M1 page

- content/integrations/plugins/magento1/manual.md
> DOCS-1296: changed-email-m1

- content/payment-methods/credit-and-debit-cards/vpay/activate-vpay.md
> DOCS-1298: vpay-activation-update

- content/faq/PSD2/can-I-still-apply-surcharges.md
- content/faq/api/locale.md
- content/integrations/plugins/magento2/faq/pending-payment-order-lifetime.md
- content/payment-methods/banks/bank-transfer/how-does-bank-transfer-work.md
- content/payment-methods/billing-suite/afterpay/how-does-afterpay-work.md
- content/payment-methods/billing-suite/pay-after-delivery/how-does-pay-after-delivery-work.md
- content/payment-methods/wallet/alipay/alipay-how-does-it-work.md
- content/tools/multisafepay-control-app/how-to-download-the-app.md
> INTGRTN-1367: . after url

- content/integrations/plugins/shopware6/_index.md
- content/integrations/plugins/shopware6/faq/enable-tokenization-within-shopware6.md
- content/tools/tokenization/tokenization-available-for-plugins.md
> Release Shopware 1.4.0

- .github/banned_words.txt
- content/api/api/authentication.md
- content/api/api/environments.md
- content/faq/getting-started/can-i-test-with-multisafepay.md
- content/integrations/sdk/fastcheckout-android/manual.md
- content/integrations/sdk/fastcheckout-ios/manual.md
> DOCS-1305: changed-api-key-uppercases

- content/payment-methods/banks/direct-bank-transfer/what-is-direct-bank-transfer.md
> DOCS-1306: added-belgium-dbt

- content/faq/general/styleguide.md
> INTGRTN-1581: added-logo-page

- content/api/discount/discount-order-rule.md
- layouts/api/list.html
- static/css/api.css
> DOCS-912: API breakpoints

- layouts/_default/baseof.html
> DOCS-1332: add-footer-all-pages

- static/robots.txt
> DOCS-1087: hide-easywebshop-page

- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-dirdeb.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-kbc.md
- content/api/payment_methods/post-order-klarna.md
- content/api/payment_methods/post-order-payafter.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-sofort.md
- content/api/payment_methods/post_order_afterpay.md
> DOCS-1258: fixed-menu-api-clicks

- content/integrations/hosted/shopify/faq/available-payment-methods-shopify.md
> DOCS-1667: added DBRTP to Shopify

- content/faq/general/where-find-logo-payment-methods.md
> DOCS-1198: added-faq-payment-logos

- content/integration-team/integration-review-nl.md
> DOCS-1313: direct-link-to-review

- static/.htaccess
> DOCS-1320: add-redirect-301

- content/how-to-find-us/malaga-office-location.md
- static/.htaccess
> DOCS-1694: correct-name-office

- content/payment-methods/billing-suite/betaalplan/activate-betaalplan.md
> DOCS-1346: change max amount betaalplan

- static/css/main.css
> DOCS-1326: removed-preview-searchbar

- content/api/tools/manual_capture_cancel_authorization_reservation.md
- content/api/tools/manual_capture_order_status_authorised_transaction.md
> DOCS-1364: added-orderid-info-manual-capture

- static/robots.txt
> DOCS-1087: removed-page-from-robots

- static/.htaccess
> DOCS-1320: fix-moz-crawl-error3

- content/integrations/plugins/magento2/_index.md
> [plugin] Release of Magento2 plugin update

- content/api/transactions/create_refund_pad.md
> DOCS-1347: removes-questionmark

- content/integrations/plugins/magento2/manual.md
> DOCS-1348: added-updates-section-m2

- content/api/gateways/get_gateway.md
- content/api/gateways/get_issuers.md
- content/api/gateways/get_multiplegiftcards.md
> INTGRTN-1739: changed-tables-api-gateways

- content/api/orders/get_order.md
- content/api/orders/patch_order.md
- content/api/orders/post_order.md
- content/api/orders/post_order_direct.md
- content/api/orders/post_order_recurring.md
- content/api/orders/post_order_template.md
- content/api/orders/split_payments_request.md
> DOCS-1389: changed-tables-api-orders

- content/api/payment_methods/post-order-dotpay.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-eps.md
- content/api/payment_methods/post_order_direct_bank_transfer.md
> DOCS-1366: sort-order-dbt

- .github/banned_words.txt
- content/faq/general/where-find-logo-payment-methods.md
- content/integrations/community/GO/_index.md
- content/integrations/community/Laravel/_index.md
- content/integrations/community/craft/_index.md
- content/integrations/community/django/_index.md
- content/integrations/community/ofbiz/_index.md
- content/integrations/community/omnipay/_index.md
- content/integrations/pwa/pwa-studio/manual.md
- content/integrations/pwa/vue-storefront/manual.md
- content/integrations/wrappers/java/_index.md
- content/integrations/wrappers/net/_index.md
- content/integrations/wrappers/nodejs/_index.md
- content/integrations/wrappers/php/_index.md
- content/integrations/wrappers/python/_index.md
- layouts/_default/single.html
- layouts/partials/changelog.html
- layouts/shortcodes/introduction_plugin.html
> INTGRTN-1725: updated-github-name

- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-american-express.md
- content/api/payment_methods/post-order-bancontact.md
- content/api/payment_methods/post-order-bancontactqr.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-creditcard.md
- content/api/payment_methods/post_order_branded.md
- content/api/payment_methods/post_order_direct_bank_transfer.md
> DOCS-1390: changed-tables-api-payments-oneofthree

- content/api/payment_methods/post-order-dirdeb.md
- content/api/payment_methods/post-order-dotpay.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-eps.md
- content/api/payment_methods/post-order-giropay.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-idealqr.md
- content/api/payment_methods/post_order_afterpay.md
- content/api/payment_methods/post_order_applepay.md
- content/api/payment_methods/post_order_gift_card.md
> DOCS-1398: changed-tables-api-payments-twoofthree 

- content/api/payment_methods/post-order-dirdeb.md
- content/api/payment_methods/post-order-dotpay.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-eps.md
- content/api/payment_methods/post-order-giropay.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-kbc.md
- content/api/payment_methods/post-order-klarna.md
- content/api/payment_methods/post-order-payafter.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sofort.md
- content/api/payment_methods/post_order_maestro.md
- content/api/payment_methods/post_order_mastercard.md
- content/api/payment_methods/post_order_trustly.md
- content/api/payment_methods/post_order_trustpay.md
- content/api/payment_methods/post_order_visa.md
> DOCS-1399: changed-tables-api-payments-threeofthree

- content/api/transactions/create_refund.md
- content/api/transactions/create_refund_pad.md
> DOCS-1391: changed-tables-api-transactions

- content/api/other_requests/chargeback.md
> DOCS-1392: changed-tables-api-other-request

- content/api/reference/customer.md
- content/api/reference/days_active.md
- content/api/reference/order-specifications.md
- content/api/reference/payment_options.md
- content/api/reference/plugin_info.md
- content/api/reference/second_chance.md
- content/api/reference/tokenization-create-token-transaction.md
- content/api/reference/tokenization-delete-token.md
- content/api/reference/tokenization-get-order-details.md
- content/api/reference/tokenization-get-token-info.md
- content/api/reference/tokenization-list-all-tokens.md
- content/api/reference/tokenization-original-transaction.md
> DOCS-1393: changed-tables-api-reference

- content/api/partners/create-a-merchant-account.md
- content/api/partners/create-website.md
> DOCS-1394: changed-tables-api-partners

- content/api/tools/3d-enabled-request.md
- content/api/tools/credit-cards-server-to-server.md
- content/api/tools/generate-payment-link.md
- content/api/tools/manual-capture.md
- content/api/tools/manual_capture_cancel_authorization_reservation.md
- content/api/tools/manual_capture_full.md
- content/api/tools/manual_capture_order_status_authorised_transaction.md
- content/api/tools/manual_capture_order_status_captured_transaction.md
- content/api/tools/manual_capture_partial.md
- content/api/tools/non-3d-request.md
- content/api/tools/post_order_direct_flexible_3d_enabled.md
- content/api/tools/post_order_direct_flexible_3d_s2s_enabled.md
- content/api/tools/post_order_redirect_flexible_3d_disabled.md
- content/api/tools/post_order_redirect_flexible_3d_enabled.md
- content/api/tools/zero-authorization-order-status.md
- content/api/tools/zero-authorization.md
> DOCS-1395: changed-tables-api-tools

- content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
- content/integrations/hosted/lightspeed_app/manual.md
> DOCS-1357: add lightspeed migration instructions

- static/.htaccess
> DOCS-1353: fixed-htaccess

- content/faq/general/styleguide.md
> INTGRTN-1717: added-better-description

- content/tools/split-payments/how-do-i-get-split-payments.md
> DOCS-1349: add-empty-space

- content/integrations/hosted/lightspeed_app/manual.md
- content/integrations/hosted/lightspeed_core/_index.md
- content/integrations/plugins/shopware6/manual.md
> DOCS-1420: fix lightspeed issues

- content/integrations/plugins/prestashop-1-7/faq/payment-fee-surcharges.md
- content/integrations/reservation management/Planyo/_index.md
> DOCS-1354: prestashop surcharge update

- content/integrations/plugins/magento2/faq/refunding-magento2.md
> DOCS-1363: updated-m2-refund

- content/api/reference/second_chance.md
> DOCS-1402: added-second-chance-api-info

- content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> DOCS: update refund lightspeed

- content/integrations/plugins/zencart/_index.md
- content/integrations/plugins/zencart/changelog.md
- content/integrations/plugins/zencart/faq/available-payment-methods-zen-cart.md
> [plugin] Release of Zen Cart plugin update

- content/faq/api/how-does-the-notification-url-work.md
> INTGRTN-1697: Describe push notifications

- content/integrations/community/craft/_index.md
- content/integrations/plugins/craftcommerce/_index.md
> Docs 1413 - Remove Craft from community and add Craft to plugins

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
> [plugin] Release of Woocommerce plugin update

- content/faq/getting-started/test-payment-details.md
> DOCS-1365: added-cbc-payment-test

- content/integrations/plugins/shopware6/_index.md
- content/integrations/plugins/shopware6/faq/available-payment-methods-shopware6.md
> [plugin] Release of Shopware6 plugin update

- content/faq/getting-started/test-payment-details.md
> DOCS-1404: added-dtb-test

- layouts/_default/baseof.html
> DOCS-1083: added-css-baseof

- content/integrations/community/Community integration requirements/_index.md
- layouts/_default/baseof.html
> DOCS-1083: restored-file-community

- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
> DOCS-1491: removed-creditcards

- content/integrations/plugins/magento2/_index.md
> DOCS: Add new download link for latest Magento 2 release 

- content/payment-methods/billing-suite/klarna/what-is-klarna.md
> DOCS-1530: Belgium and Finland to Klarna

- content/integrations/hosted/lightspeed_app/manual.md
> PLGLTS-95: added cache info

- content/tools/payment-link/manually-generating-a-payment-link.md
> DOCS-1400: added-qr-code-explanation1

- content/integrations/plugins/zencart/changelog.md
- content/payment-methods/prepaid-cards/_index.md
- content/payment-methods/prepaid-cards/gift-cards/_index.md
> DOCS-1412: updated-giftcard-name

- content/integrations/plugins/magento2/_index.md
- content/integrations/plugins/magento2/beta.md
- layouts/_default/single-beta-button.html
@Atiq-MultiSafepay Please provide some feedback on the english and grammar and such
**Edit: Converted to draft because it should not be merged until the repo's are made public**
> DOCS-1515: Add new Magento 2 plugin page

- content/payment-methods/banks/sepa-direct-debit/how-does-sepa-direct-debit-work.md
> DOCS-1429: fixed-misspelling

- content/tools/server2server/server-to-server-flow.md
> DOCS-1454: updated-s2s-3d

- content/tools/server2server/server-to-server-flow.md
> DOCS-1454: fix-shell

- content/faq/general/analytics-track-payment-pages.md
> DOCS-1501: changed-link

- content/tools/second-chance/how-does-it-work.md
> DOCS-1485: removed-pending-status-pl

- content/integrations/plugins/magento2/_index.md
- content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md
> Release of Magento2 1.14.0

- content/integrations/wrappers/laravel/_index.md
> Add Laravel API release

- content/integrations/hosted/shopify/faq/available-payment-methods-shopify.md
> DOCS-1551: removed-nexi-shopify

- content/api/payment_methods/post_order_trustpay.md
> DOCS-1487: added-trustpay-gateway-api

- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-sofort.md
> DOCS-1536: added-correct-currency-sofort-ideal

- content/integrations/plugins/shopware6/manual.md
> DOCS-1425: updated-text-api-shopware

- content/integrations/plugins/opencart/faq/how-can-i-update-the-plugin-for-opencart.md
- content/integrations/plugins/opencart/faq/payment-fee-surcharges.md
- content/integrations/plugins/opencart/faq/supported-opencart-checkouts.md
- content/integrations/plugins/opencart/manual.md
> Replace extension word, by plugin, where is possible

- content/tools/partner-account-control/merchant-agreement.md
- content/tools/partner-account-control/partner-reimbursement-invoice.md
> DOCS-1494: added-readmore

- content/payment-methods/billing-suite/afterpay/refund-afterpay.md
> DOCS-1502: fixed-discount-checklist-afterpay

- content/payment-methods/banks/bancontact/activate-bancontact.md
> DOCS-1499: fixed-bancontact-text

- content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> DOCS: Update refunding-lightspeed.md

- content/tools/reports/report-validity.md
> DOCS-1424: Report validity

- content/tools/multisafepay-control/delete-website.md
> DOCS-1461: Adds delete a website to MSP Control Tools section

- content/integrations/cash register software/MplusKASSA/_index.md
> DOCS-1570: Spelling fix

- content/payment-methods/billing-suite/klarna/refund-klarna.md
> DOCS-1509: Changes Klarna contact address

- static/.htaccess
> DOCS-1556: Redirects for Request to Pay

- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
> DOCS-1345: Fixes Integration review page NL/ENG

- content/payment-methods/banks/request-to-pay/what-is-request-to-pay.md
> DOCS-1577: Mentioning of DBT on RTP page

- content/integrations/plugins/opencart/changelog.md
> INTGRTN-1892: Update CHANGELOG for OpenCart plugin related to release 3.2.0

- content/integrations/plugins/magento2/manual.md
> DOCS-1422: specified-configuration-button

- content/tools/payment-pages/what-is-payv2.md
> DOCS-1528: added-available-pm-v2

- content/payment-methods/banks/ideal/how-does-ideal-work.md
> DOCS-1410: Adjusts refund status of iDEAL

- content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> DOCS: Add lightspeed

- content/api/payment_methods/post_order_gift_card.md
- content/integrations/plugins/craftcommerce/faq/available-payment-methods-magento2.md
- content/integrations/plugins/cs-cart/faq/available-payment-methods-cs-cart.md
- content/integrations/plugins/drupal8/faq/available-payment-methods-drupal8.md
- content/integrations/plugins/magento1/faq/available-payment-methods-magento1.md
- content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md
- content/integrations/plugins/opencart/faq/available-payment-methods-opencart.md
- content/integrations/plugins/oscommerce/faq/available-payment-methods-oscommerce.md
- content/integrations/plugins/prestashop-1-6/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md
- content/integrations/plugins/shopware6/faq/available-payment-methods-shopware6.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
- content/integrations/plugins/x-cart/faq/available-payment-methods-x-cart.md
- content/integrations/plugins/zencart/faq/available-payment-methods-zen-cart.md
- content/payment-methods/prepaid-cards/gift-cards/activate-gift-cards.md
- content/payment-methods/prepaid-cards/gift-cards/branded-personalized-gift-card.md
- content/payment-methods/prepaid-cards/gift-cards/which-gift-cards-are-accepted-by-multisafepay.md
> DOCS-1466: Removes Givacard and Goodcard from DOCS

- content/integrations/hosted/dynamicweb/_index.md
> DOCS-1549: fixed-url-contact

- content/integrations/plugins/magento2/beta.md
> DOCS-1540: m2 plugin beta docs feedback

- content/faq/finance/uncleared-payments.md
- content/faq/general/bank-holidays.md
- content/integrations/hosted/lightspeed_app/faq/available-payment-methods-lightspeed.md
- content/integrations/hosted/lightspeed_app/faq/change-environment.md
- content/integrations/hosted/lightspeed_app/faq/disable-payment-methods.md
- content/integrations/hosted/lightspeed_app/faq/inline-buy-button.md
- content/integrations/hosted/lightspeed_app/faq/inline-news-letter.md
- content/integrations/hosted/lightspeed_app/faq/lightspeed-orderid.md
- content/integrations/hosted/lightspeed_app/faq/maximal-order-amount.md
- content/integrations/hosted/lightspeed_app/faq/migrate-to-app.md
- content/integrations/hosted/lightspeed_app/faq/minimal-order-amount.md
- content/integrations/hosted/lightspeed_app/faq/order-payment-methods.md
- content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
- content/integrations/hosted/lightspeed_app/faq/shop_id.md
- content/integrations/hosted/lightspeed_core/_index.md
- content/integrations/hosted/lightspeed_core/faq/_index.md
- content/integrations/hosted/lightspeed_core/faq/lightspeed-orderid.md
- content/tools/multisafepay-test-environment/partner-test-merchant-account.md
> DOCS-1311: fixed-duplicated-meta-titles

- content/faq/general/multisafepay-status-page.md
- layouts/partials/footer.html
> DOCS-1356: Adds info to status page + footer

- content/faq/getting-started/glossary.md
- content/payment-methods/prepaid-cards/gift-cards/open-loop-vs-closed-loop.md
> DOCS-1534: Open loop vs closed loop gift cards

- content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md
> Release of Shopware5 2.5.0

- content/tools/multisafepay-control/autowithdrawl-updates.md
> DOCS-1585: Autowithdrawal feature

- content/integrations/hosted/shopify/faq/available-payment-methods-shopify.md
> DOCS-1535: Spelling fix Bancontact

- content/integrations/wrappers/php/_index.md
> [chore] Promote php sdk

- content/payment-methods/billing-suite/klarna/what-is-klarna.md
> DOCS-1574: KPM to Klarna notice

- content/integrations/plugins/craftcommerce/manual.md
> INTGRTN-1949 - Add features to Craft Commerce page

- content/integrations/plugins/craftcommerce/faq/available-payment-methods-craft-commerce.md
- content/integrations/plugins/cs-cart/faq/available-payment-methods-cs-cart.md
- content/integrations/plugins/drupal7/faq/available-payment-methods-drupal.md
- content/integrations/plugins/drupal8/faq/available-payment-methods-drupal8.md
- content/integrations/plugins/magento1/faq/available-payment-methods-magento1.md
- content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md
- content/integrations/plugins/opencart/faq/available-payment-methods-opencart.md
- content/integrations/plugins/oscommerce/faq/available-payment-methods-oscommerce.md
- content/integrations/plugins/prestashop-1-6/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md
- content/integrations/plugins/shopware6/faq/available-payment-methods-shopware6.md
- content/integrations/plugins/virtuemart/faq/available-payment-methods-virtuemart.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
- content/integrations/plugins/x-cart/faq/available-payment-methods-x-cart.md
- content/integrations/plugins/zencart/faq/available-payment-methods-zen-cart.md
> DOCS-1600: Adds vpay to plugins

- content/tools/partner-account-control/invoice-structure.md
> DOCS-1409: Adds invoice info to Partner control docs

- content/payment-methods/banks/sofort-banking/_index.md
- content/tools/payment-pages/what-is-payv2.md
> DOCS-1596: DBT to RTP name change on Payv2 page

- layouts/partials/bottom-block.html
> DOCS-1546: Grammar correction

- content/api/reference/days_active.md
> DOCS-1472: Days and seconds active info on API Docs

- content/payment-methods/banks/request-to-pay/how-to-activate-request-to-pay.md
> DOCS-1553: Removes pilot phase info Request to Pay Docs

- content/payment-methods/credit-and-debit-cards/nexi/nexi.md
> DOCS-1576: note-cartasi

- content/payment-methods/banks/request-to-pay/what-is-request-to-pay.md
> DOCS-1490: Changes RTP operating country

- content/faq/risk-and-fraud/what-do-i-need-to-know-about-credit-card-payments.md
- content/tools/payment-pages/payment-page-templates.md
> DOCS-1511: Spelling fix of Payment pages

- content/tools/multisafepay-control/autowithdrawl-updates.md
> DOCS-1367: added-payment-reference-standard

- content/integrations/plugins/craftcommerce/manual.md
> DOCS-1616: Craft commerce spelling fixes

- content/payment-methods/billing-suite/pay-after-delivery/how-does-pay-after-delivery-work.md
> DOCS-1519: Adds product rule to Pay After Delivery

- content/api/payment_methods/post_order_request_to_pay.md
> DOCS-1279: Adds header for Request to Pay in API section

- content/faq/api/maximum-length-of-order-id.md
> DOCS-1550: Adds info to API FAQ about max char. of order_id

- content/payment-methods/billing-suite/klarna/activate-klarna.md
- content/payment-methods/billing-suite/klarna/how-does-klarna-work.md
> DOCS-1526: Corrects Klarna contact info on DOCS

- config.toml
> DOCS-1567: Adds integration buttons to menu

- content/faq/getting-started/test-payment-details.md
> DOCS-1586: Changes test info for Bancontact

- content/integrations/plugins/opencart/changelog.md
- content/integrations/plugins/opencart/manual.md
> INTGRTN-1997: Update docs for OpenCart extension 3.3.0 release

- layouts/_default/baseof.html
- layouts/_default/communitylist.html
- static/css/main.css
> DOCS-1590: hide-last-element-community

- content/payment-methods/prepaid-cards/gift-cards/branded-personalized-gift-card.md
- content/payment-methods/prepaid-cards/gift-cards/which-gift-cards-are-accepted-by-multisafepay.md
> DOCS-1632: Adds Klantkaart as a personalized gift card provider + Removes in gift card list

- content/integrations/plugins/magento1/manual.md
> DOCS-1568: Magento 1 breach notice on Magento 1 plugin page

- content/payment-methods/billing-suite/klarna/how-does-klarna-work.md
> DOCS-1563: Adjustment to Klarna integration process

- content/integrations/plugins/prestashop-1-7/_index.md
- content/integrations/plugins/prestashop-1-7/changelog.md
- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
> [release] PrestaShop 1.7 4.7.0

- content/integrations/plugins/magento2/manual.md
> [fix] Add Magento2 2.4 compatible

- content/tools/multisafepay-control/autowithdrawl-updates.md
> DOCS-1367: added-payment-reference-standard-blank-space

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
> Release of WooCommerce 3.8.0

- content/payment-methods/billing-suite/afterpay/what-is-afterpay.md
> DOCS-1666: Space on page, test deployment

- content/payment-methods/billing-suite/afterpay/what-is-afterpay.md
> DOCS-1666: Test deployment

- content/payment-methods/billing-suite/afterpay/what-is-afterpay.md
> DOCS-1666: Test

- content/api/payment_methods/post_order_afterpay.md
> DOCS-1641: Adjusts Afterpay birthday parameter

- content/payment-methods/banks/belfius/how-does-belfius-work.md
> DOCS-1317: Belfius transaction expiration added to product rules

- content/integrations/plugins/magento1/manual.md
> DOCS-1643: Changes step 1 API key info on Magento 1 page

- content/integrations/community/Community integration requirements/_index.md
> INTGRTN-1723: updated-text-community-integration

- content/integrations/community/Community integration requirements/_index.md
> DOCS-1682: Adjusts content on Submit a community integration page

- content/integrations/hosted/shopify/faq/available-payment-methods-shopify.md
- content/integrations/hosted/shopify/manual.md
> Shopify: Improve installation manual

- content/integrations/accounting and bookkeeping/test/_index.md
> DOCS: test page

- content/integrations/plugins/magento2/_index.md
- content/integrations/plugins/magento2/beta.md
- content/integrations/plugins/magento2/manual.md
- content/integrations/plugins/magento2/old.md
- layouts/_default/single-old-button.html
> DOCS: Change Magento 2 to show new plugin on main page

- content/integrations/plugins/magento2/old.md
> Release of Magento2msp 1.14.1

- content/integrations/plugins/magento2/manual.md
> DOCS: Fix PHP Requirements Magento 2

- content/integrations/hosted/lightspeed_app/faq/footer-icons.md
> DOCS: update PLGLTS-148

- content/integrations/plugins/opencart/_index.md
- content/integrations/plugins/opencart/changelog.md
- content/integrations/plugins/opencart/faq/how-can-i-update-the-plugin-for-opencart.md
- content/integrations/plugins/opencart/manual.md
> PLGOPNS-349: Change in docs upgrade instructions

- content/integrations/plugins/opencart/_index.md
> PLGOPNS-356: Update download link

- content/tools/payment-link/_index.md
Previously Payment link used same icon as Recurring Payments.
- Use Italics for buttons, clicks, paths, etc. Do mind to close …
> DOCS-1742: Change icon tools/payment-link

- content/integrations/plugins/magento2/faq/payment-links-in-order-confirmation-for-backend-orders.md
> DOCS: Add updated payment link code for newer Magento versions

- layouts/partials/whats-new.html
> DOCS-1755: Typo fix in 'What's new'

- content/api/orders/post_order_direct.md
CREDITCARDS has been changed into CREDITCARD
KLARNA_ACC has been removed
- Use Italics for buttons, clicks, paths, etc. Do …
> DOCS-1751: Update payment methods (API)

- content/faq/getting-started/glossary.md
> DOCS-1749: Typos glossary

- content/faq/api/how-does-the-notification-url-work.md
> DOCS-1426: added-multisafepayok

- content/faq/api/how-does-the-notification-url-work.md
> DOCS-1426b: fixed-underscore

- content/faq/api/lifetime-of-a-payment-link.md
> DOCS-1770: Fix shortcode bracket

- layouts/_default/baseof.html
> DOCS-0000: Change main.css version

- content/faq/Payment Regulations/3D-secure.md
> DOCS-0000: Fix unordered list

- content/integrations/plugins/magento2/old.md
> DOCS-1748: Add Changelog Magento2 V1

- content/integrations/plugins/prestashop-1-7/_index.md
> Release of PrestaShop 4.7.1

- content/integrations/plugins/magento2/_index.md
Magento2 changelog link redirected to specific version.
Now it redirects to /blob/master/CHANGELOG.md which shows
the full version history of the repository.
- Use single quotation marks in your Markdown code …
> DOCS-1779: Changelog Magento2

- content/integrations/plugins/magento2/manual.md
> DOCS: edit composer update command for Magento 2

- content/integrations/plugins/magento2/manual.md
- content/integrations/plugins/magento2/old/faq/_index.md
Recently, FAQ items were moved from the new plugin page to the old plugin page.
The notice alerts users of this change and redirects if needed.
- Use single quotation marks in your Markdown code (example title: …
> DOCS-1809: Add notice to Magento 2 plugin

- content/integrations/plugins/woocommerce/faq/refunding-woocommerce.md
> DOCS-1722: Add partial refunds WooCommerce

- content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md
> Release of Shopware5 - 2.7.0

- content/payment-methods/billing-suite/klarna/activate-klarna.md
> DOCS-1817: Fix activate link on Klarna page

- content/integrations/hosted/shopify/faq/available-payment-methods-shopify.md
- content/integrations/hosted/zilvercms/faq/available-payment-methods-zilvercms.md
- content/integrations/plugins/craftcommerce/faq/available-payment-methods-craft-commerce.md
- content/integrations/plugins/cs-cart/faq/available-payment-methods-cs-cart.md
- content/integrations/plugins/drupal7/faq/available-payment-methods-drupal.md
- content/integrations/plugins/drupal8/faq/available-payment-methods-drupal8.md
- content/integrations/plugins/magento1/faq/available-payment-methods-magento1.md
- content/integrations/plugins/magento2/old/faq/available-payment-methods-magento2.md
- content/integrations/plugins/odoo/faq/available-payment-methods.md
- content/integrations/plugins/opencart/faq/available-payment-methods-opencart.md
- content/integrations/plugins/oscommerce/faq/available-payment-methods-oscommerce.md
- content/integrations/plugins/prestashop-1-6/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
- content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md
- content/integrations/plugins/shopware6/faq/available-payment-methods-shopware6.md
- content/integrations/plugins/virtuemart/faq/available-payment-methods-virtuemart.md
- content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md
- content/integrations/plugins/x-cart/faq/available-payment-methods-x-cart.md
- content/integrations/plugins/zencart/faq/available-payment-methods-zen-cart.md
> DOCS-1806: Fix hyperlinks Cartes Bancaires & Dankort

- content/payment-methods/wallet/paypal/how-does-paypal-work.md
> DOCS-0000: Unnest header

- content/api/gateways/get_issuers.md
> DOCS-1780: Add revolut as issuer API

- content/tools/recurring-payments/recurring-payments-how-does-it-work.md
> DOCS-1758: Fix hyperlink to API - Recurring Payments

- content/integrations/plugins/drupal8/manual.md
> DOCS-1773: Add notice drupal 8.9 and support changes

- content/api/payment_methods/post-order-dotpay.md
> DOCS-1839: Fix hyperlink Dotpay

- content/integrations/plugins/magento2/old/faq/payment-links-in-order-confirmation-for-backend-orders.md
> DOCS-1826: Change hyperlink to old plugin manual

- .github/CODEOWNERS
> DOCS-0000: Add Kris-MultiSafepay to CODEOWNERS

- content/faq/general/where-find-logo-payment-methods.md
- content/payment-methods/credit-and-debit-cards/cartes-bancaires/cartes-bancaires.md
- content/payment-methods/credit-and-debit-cards/dankort/dankort.md
- content/payment-methods/credit-and-debit-cards/postepay/postepay.md
> DOCS-1717: Fix hyperlinks to payment method icons

- content/tools/multisafepay-control/two-factor-authentication.md
> DOCS-0000: Fix list

- content/api/reference/customer.md
> DOCS-1407: Swap user_agent and referrer

- content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md
- content/integrations/plugins/magento2/faq/does-the-plugin-support-Magento-2-Commerce.md
- content/integrations/plugins/magento2/faq/how-can-i-generate-a-payment-link.md
- content/integrations/plugins/magento2/faq/how-can-i-update-the-plugin-for-magento2.md
- content/integrations/plugins/magento2/faq/payment-fee-surcharges.md
- content/integrations/plugins/magento2/faq/payment-links-in-order-confirmation-for-backend-orders.md
- content/integrations/plugins/magento2/faq/refunding-magento2.md
- content/integrations/plugins/magento2/faq/supported-magento2-checkouts.md
- content/integrations/plugins/magento2/old/faq/supported-magento2-checkouts.md
> DOCS: Add FAQ articles for new Magento 2 plugin

- content/integrations/hosted/lightspeed_app/faq/multiple-accounts.md
> DOCS: lsp faq multiple account

- config.toml
- content/guides/_index.md
- content/guides/getting-started/_index.md
- layouts/shortcodes/button.html
- layouts/shortcodes/buttons.html
This commit contains the MVD for getting started, including a menu icon
and shortcode for on-page bottons.
- Use Italics for …
> DOCS-1696: Getting Started MVD

- content/guides/getting-started/_index.md
> DOCS-0000: Fix ordered list

- content/tools/credit-card-component/_index.md
> DOCS-0000: Shorten URL and uniform naming

- content/integrations/hosted/lightspeed_app/manual.md
> DOCS: PLGLTS-127

- content/faq/general/add-spf-dns-records.md
> DOCS-1906: Adds notice of name of file on SPF DNS records page

- layouts/partials/footer.html
> DOCS-2022: Renew hyperlink to getting started in footer

- .github/PULL_REQUEST_TEMPLATE.md
> DOCS-1656: Add information about Hugo aliases

- content/integrations/plugins/prestashop-1-7/_index.md
- content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md
> Release of PrestaShop 1.7 4.8.0

- content/integrations/plugins/magento2/old/faq/payment-links-in-order-confirmation-for-backend-orders.md
> DOCS: Update payment link info for old Magento 2 plugin

- content/api/api/environments.md
- static/css/main.css
> DOCS-2058: Update styling code snippets

- content/integrations/plugins/magento2/manual.md
> DOCS: Add GraphQL module to Magento 2 manual

- content/integrations/plugins/magento2/manual.md
> DOCS: Fix missing whitespace GraphQL Magento 2

- content/integrations/hosted/lightspeed_app/faq/available-payment-methods-lightspeed.md
> Lightspeed: FAQ: Update payment methods

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
> Release 4.1.1

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
> Release of WooCommerce 4.1.2

- content/integrations/plugins/magento2/manual.md
> DOCS: Add meta-package dependency info for Magento MSI

- content/integrations/hosted/lightspeed_app/manual.md
> DOCS-1907: Remove beta from Lightspeed app

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
- content/integrations/plugins/woocommerce/manual.md
- Update download link release 4.1.5.
- Update installation instructions. 
- Update changelog.md release 4.1.5
> WooCommerce release 4.1.5

- content/integrations/plugins/magento1/_index.md
> DOCS-2081: Fix download Magento 1

- .github/mlc_config.json
- content/integrations/plugins/prestashop-1-6/_index.md
- content/payment-methods/credit-and-debit-cards/maestro/maestro-testing.md
> DOCS-2024: Modify broken-links Github Action config

- content/api/orders/post_order_recurring.md
> DOCS-0000: Fix locale code

- content/integrations/plugins/woocommerce/_index.md
- content/integrations/plugins/woocommerce/changelog.md
> Release of WooCommerce plugin 4.1.6

- .github/banned_words.txt
- content/faq/finance/uncleared-payments.md
> DOCS-1631: Fix banned words Github Actions

- content/integrations/ecommerce integrations/lightspeed_app/faq/how-to-login.md
> DOCS-2116: Fix path images

- content/integrations/ecommerce integrations/lightspeed_app/faq/_index.md
- content/integrations/ecommerce integrations/lightspeed_app/faq/how-to-login.md
- content/integrations/ecommerce integrations/lightspeed_app/faq/refunding-lightspeed.md
> DOCS-2117: Add aliases to Lightspeed FAQs

- content/integrations/ecommerce integrations/woocommerce/_index.md
- content/integrations/ecommerce integrations/woocommerce/changelog.md
> WooCommerce plugin release of 4.1.7

- content/integrations/ecommerce integrations/woocommerce/_index.md
- content/integrations/ecommerce integrations/woocommerce/changelog.md
> Release of WooCommerce plugin 4.1.8

- content/integrations/plugins/magento2/faq/custom-order-totals.md
> PLGMAG2V2-59: Add FAQ for Magento 2 custom totals

- content/integrations/ecommerce integrations/magento1/faq/ship-automatically-in-magento1.md
> DOCS-1945: Automatic shipped status

- content/integrations/ecommerce integrations/woocommerce/_index.md
- content/integrations/ecommerce integrations/woocommerce/changelog.md
> Release of WooCommerce plugin 4.2.0

- content/integrations/ecommerce integrations/woocommerce/changelog.md
> Fix bulletpoints within CHANGELOG

- content/payment-methods/billing-suite/klarna/what-is-klarna.md
> DOCS-2112: Update Klarna currencies/countries supported

- content/faq/general/descriptor-bank-statement.md
> DOCS-2110: Clarifies descriptor on bank statement

- content/payment-methods/billing-suite/in3/how-does-in3-work.md
> DOCS-2015: Valid amounts in3

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> Release of WooCommerce plugin 4.2.1

- content/integrations/ecommerce-integrations/shopware5/manual.md
> DOCS-2100: Change installation steps Shopware 5

- content/integrations/ecommerce-integrations/magento1/manual.md
- content/integrations/ecommerce-integrations/magento2/manual.md
> DOCS-2002: Add notice Magento features

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> Release of WooCommerce plugin 4.2.2

- content/integrations/ecommerce-integrations/ccvshop/_index.md
- content/integrations/ecommerce-integrations/ccvshop/manual.md
- content/integrations/ecommerce-integrations/dynamicweb/_index.md
- content/integrations/ecommerce-integrations/easywebshop/_index.md
- content/integrations/ecommerce-integrations/lightspeed_app/manual.md
- content/integrations/ecommerce-integrations/logivert/_index.md
- content/integrations/ecommerce-integrations/logivert/manual.md
- content/integrations/ecommerce-integrations/mijnwebwinkel/_index.md
- content/integrations/ecommerce-integrations/mijnwebwinkel/manual.md
- content/integrations/ecommerce-integrations/myshop/_index.md
- content/integrations/ecommerce-integrations/myshop/manual.md
- content/integrations/ecommerce-integrations/sanacommerce/_index.md
- content/integrations/ecommerce-integrations/shopify/manual.md
- content/integrations/ecommerce-integrations/zilvercms/_index.md
- layouts/shortcodes/introduction_app.html
> DOCS-2122: Change introduction and meta_titles of apps

- content/tools/credit-card-component/_index.md
> DOCS-2126: Change JSON response for API token request

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> DOCS-2164: Release of WooCommerce plugin 4.3.0

- content/integrations/ecommerce-integrations/magento1/manual.md
- content/integrations/ecommerce-integrations/magento2/manual.md
- content/integrations/ecommerce-integrations/magento2/old/_index.md
- content/integrations/ecommerce-integrations/opencart/changelog.md
- content/integrations/wrappers/fastcheckout-android/_index.md
- content/integrations/wrappers/fastcheckout-android/manual.md
- content/integrations/wrappers/fastcheckout-ios/_index.md
- content/integrations/wrappers/fastcheckout-ios/manual.md
> DOCS-2163: Rename Fastcheckout to FastCheckout

- content/integrations/ecommerce-integrations/drupal8/_index.md
> [release] Drupal 8-3.0.0 update download_url

- content/integrations/ecommerce-integrations/opencart/changelog.md
> DOCS-2168: Release of OpenCart plugin 3.9.0

- content/integrations/ecommerce-integrations/logic4/faq/available-payment-methods-logic4.md
> DOCS-2167: Add in3 payment method to Logic4

- content/integrations/plugins/magento2/faq/generic-gateways-magento2.md
> DOCS: Add generic gateway for Magento 2

- content/faq/general/generic-gateways.md
- content/integrations/plugins/opencart/faq/generic-gateways.md
- content/integrations/plugins/woocommerce/faq/generic-gateways.md
This PR includes a short FAQ article for OpenCart and WooCommerce plugins on generic gateways.
The base branch is a generic gateway started by @Thomas-MultiSafepay to unite all the changes related to this concept and submit a PR to master at the right moment.
> FAQ item for OpenCart and WooCommerce generic gateway

- content/faq/general/generic-gateways.md
- content/integrations/plugins/craftcommerce/faq/generic-gateways.md
> Add FAQ item for Craft Commerce

- content/faq/getting-started/are-there-any-products-or-services-that-cannot-be-sold.md
> DOCS-2181: Add reference to alcohol sales conditions

- .github/workflows/PR Lint.yml
> Update PR Lint.yml

- content/tools/multisafepay-control/set-your-notification-url.md
> PLGWOOS-641: Update notification URL for WooCommerce plugin

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> Release of WooCommerce plugin 4.4.0

- content/integrations/ecommerce-integrations/magento2/faq/pending-payment-order-lifetime.md
> DOCS-1937: Add back pending_payment order lifetime FAQ

- content/integrations/ecommerce-integrations/shopware6/_index.md
> [release] Shopware6 2.3.0 - update download_url

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> Release of WooCommerce plugin 4.4.1

- content/integrations/ecommerce-integrations/lightspeed_app/faq/order-payment-methods.md
> DOCS-2147: Clarify payment method order Lightspeed

- content/tools/multisafepay-control/two-factor-authentication.md
- layouts/shortcodes/collapse-h2.html
- static/css/main.css
> DOCS-1880: Add collapse to 2FA FAQ

- .github/banned_words.txt
> DOCS-2123: Update banned_words.txt

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> PLGWOOS-660: Release of WooCommerce plugin 4.5.0

- content/integrations/ecommerce-integrations/woocommerce/faq/generic-gateways.md
> DOCS-2194: WooCommerce Generic Gateway FAQ item

- content/integrations/ecommerce-integrations/shopware5/changelog.md
- content/integrations/ecommerce-integrations/shopware5/faq/available-payment-methods-shopware5.md
> Release of Shopware5 2.8.0

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> PLGWOOS-662: Release of WooCommerce plugin 4.5.1

- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
> DOCS-000: Add Francesca to Integration Team

- content/integrations/pwa/pwa-studio/_index.md
- content/integrations/pwa/pwa-studio/manual.md
> added information about PWA studio integration

- content/integrations/ecommerce-integrations/lightspeed_app/faq/footer-icons.md
- remove release notice
- added alias for old links
- When renaming or deleting a page, add an alias of the …
> Docs: Update footer-icons

- content/tools/multisafepay-control/set-your-notification-url.md
> DOCS-2229: Remove mention of HikiShop

- content/api/gateways/get_issuers.md
- content/faq/general/google-analytics-referral-exclusions.md
> DOCS-2233: Remove mentions of Moneyou

- content/integrations/ecommerce-integrations/lightspeed_app/faq/refunding-lightspeed.md
> DOCS: refund "not paid"

- layouts/_default/baseof.html
> DOCS-2238: Change Bootstrap CSS file version

- content/integrations/ecommerce-integrations/shopware6/_index.md
> Release of Shopware6 2.3.1

- content/integrations/accounting and bookkeeping/dealer4dealer/_index.md
> DOCS: Add info about dealer4dealer Reconcilliation 2.0

- content/integrations/wrappers/fastcheckout-android/manual.md
- content/integrations/wrappers/fastcheckout-ios/manual.md
> DOCS-2249: Fix image paths

- content/integrations/accounting and bookkeeping/dealer4dealer/_index.md
> DOCS-2250: Add video and change hyperlink dealer4dealer

- content/integrations/ecommerce-integrations/magento2/faq/migrating-to-new-plugin.md
- content/integrations/ecommerce-integrations/magento2/faq/refunding-magento2.md
> DOCS: Make better clear refunds can be done via MCP

- README.md
> DOCS-2237: Update the readme

- content/faq/chargebacks/_index.md
- content/faq/chargebacks/about-chargebacks.md
- content/faq/chargebacks/disputing-chargebacks.md
> DOCS-2213: Tidy titles FAQ - Chargebacks

- content/faq/gdpr/_index.md
- content/faq/gdpr/accessing-and-viewing-data.md
- content/faq/gdpr/anonymizing-stored-data.md
- content/faq/gdpr/can-customers-request-to-have-data-delete-removed-in-accordance-with-the-right-privacy-by-design.md
- content/faq/gdpr/deleting-customer-data.md
- content/faq/gdpr/destroying-expired-data.md
- content/faq/gdpr/does-multisafepay-have-a-data-protection-officer.md
- content/faq/gdpr/does-multisafepay-have-a-standard-processing-agreement.md
- content/faq/gdpr/does-multisafepay-perform-a-pen-test-regularly-in-order-to-test-security-measures.md
- content/faq/gdpr/ensuring-data-protection.md
- content/faq/gdpr/is-the-acquired-data-used-for-commercial-purposes.md
- content/faq/gdpr/multisafepay-data-protection-officer.md
- content/faq/gdpr/multisafepay-gdpr-addendum.md
- content/faq/gdpr/storing-data.md
- content/faq/gdpr/testing-security.md
- content/faq/gdpr/using-customer-data.md
- content/faq/gdpr/what-happens-with-the-data-after-it-is-no-longer-used.md
- content/faq/gdpr/what-steps-does-multisafepay-take-to-ensure-data-protection.md
> DOCS-2214: Tidy titles FAQ - GDPR

- content/faq/finance/adding-funds-to-your-multisafepay-balance.md
- content/faq/refunds/delays-in-processing-refunds.md
- content/payment-methods/wallet/applepay/apple-pay-how-does-it-work.md
> DOCS-2199: Add Safari browser to Apple Pay product rules

- content/faq/getting-started/test-payment-details.md
> Docs 1707: Technical edit of page

- content/faq/getting-started/switching-to-multisafepay.md
> DOCS-1884: Add information about token transfers

- content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> Add FAQ for recommended tax settings inside Magento 2

- content/integrations/ecommerce-integrations/shopware6/_index.md
- content/integrations/ecommerce-integrations/shopware6/manual.md
> Release of Shopware6 2.4.0

- content/faq/finance/paying-out-funds-from-your-multisafepay-control.md
> Fixed list format

- content/integrations/ecommerce-integrations/opencart/changelog.md
> PLGOPNS-402: Release of OpenCart 3.10.0

- content/faq/api/notification-url.md
> DOCS-2280: Update instructions POST notification URL

- content/tools/server2server/3d-dynamics.md
> DOCS-2176: Rework Dynamic 3D Secure page

- content/faq/general/generic-gateways.md
- content/faq/getting-started/onboarding-new-merchants.md
- content/guides/getting-started/_index.md
- content/tools/flexible_3d/_index.md
- content/tools/mail-order-telephone-order/_index.md
- layouts/_default/baseof.html
- layouts/_default/list.html
- static/css/main.css
> DOCS-2263: Update CSS of headings plus random fixes

- content/api/orders/post_order_direct.md
- content/api/orders/post_order_recurring.md
- content/api/payment_methods/post-order-dirdeb.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-inghome.md
- content/faq/api/masking-iban-numbers.md
> DOCS-2245: Add page about unmasking IBAN

- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
> DOCS-2257: Fix broken M2 marketplace link

- content/faq/general/generic-gateways.md
> DOCS-2279: Add WooCommerce to Generic Gateways

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> PLGWOOS-698: Release of WooCommerce plugin 4.6.0

- content/integrations/ecommerce-integrations/lightspeed_app/faq/footer-icons.md
> DOCS-2289: Fix typos

- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
> DOCS-2257: Fix Magento 2 link and line breaks

- content/tools/payment-pages/dynamic-styling-payment-pages.md
- content/tools/payment-pages/styling-payment-pages.md
> DOCS-2288: Fix broken link

- content/integrations/ecommerce-integrations/ccvshop/faq/available-payment-methods-ccv-shop.md
> DOCS-2290: Add AfterPay and Klarna to payment methods

- content/tools/zero-authorization/what-is-zero-authorization.md
> DOCS-2299: Fix cross-ref and link to Zero Authorization

- content/payment-methods/billing-suite/klarna/how-does-klarna-work.md
> DOCS-2298: Update Klarna countries

- content/payment-methods/prepaid-cards/gift-cards/which-gift-cards-are-accepted-by-multisafepay.md
> DOCS-2308: Fix link to Custom gift cards

- content/faq/testing/test-payment-details.md
> DOCS-2200: Add information about AfterPay sandbox account

- content/api/payment_methods/post-order-american-express.md
> DOCS-2223: Add missing brace in AMEX JSON

- content/integrations/ecommerce-integrations/shopware6/_index.md
> Release of Shopware6 2.4.1

- layouts/partials/menu.html
> DOCS-0000: Fix API Reference sidemenu

- content/payment-methods/billing-suite/klarna/how-does-klarna-work.md
> DOCS-2173: Reconcile Klarna countries with Confluence

- content/payment-methods/wallet/alipay/alipay-what-is-it.md
> DOCS-2187: Alipay description change

- content/payment-methods/billing-suite/klarna/what-is-klarna.md
> DOCS-2206: Add currencies to Klarna

- content/integrations/ecommerce-integrations/shopware5/faq/configuring-generic-gateways.md
> DOCS-2162: Expand Configuring generic gateways

- content/payment-methods/billing-suite/klarna/what-is-klarna.md
> DOCS-2316: Update Klarna countries

- content/integrations/ecommerce-integrations/magento2/manual.md
> DOCS-1887: Add note to uninstall old plugin first

- data/changelog.json
- layouts/partials/whats-new.html
> DOCS-2326: Add changelog to 'What's new' partial on homepage

- content/integrations/accounting-integrations/_index.md
- content/integrations/cash register software/_index.md
- layouts/partials/blocklist.html
> DOCS-0000: Add accounting integrations button to integrations

- layouts/partials/menu.html
> DOCS-2381: Remove buttons from side menu

- content/payment-methods/billing-suite/betaalpermaand/how-does-betaalplan-work.md
> DOCS-2132: Betaal per maand rejection information for order/transaction status

- content/api/payment_methods/post_order_afterpay.md
> DOCS-1294: Remove duplication in item description

- content/api/payment_methods/post_order_applepay.md
> DOCS-2291: Fixes Apple Pay format

- content/api/orders/get_order.md
- content/api/orders/post_order.md
- content/api/orders/post_order_direct.md
> DOCS-1836:Add company_name to Post - /orders

- content/integrations/ecommerce-integrations/magento2/manual.md
> Magento Commerce changed to Adobe Commerce

- content/integrations/ecommerce-integrations/shopware5/faq/transaction-number-order-number.md
> DOCS-2093: Clarify Shopware 5 order and transaction nos

- content/tools/accounting/reports/financial-report.md
> DOCS-2416: Remove link

- content/integrations/wrappers/fastcheckout-android/manual.md
> updated fastcheckout-android manual

- content/faq/general/supported-currencies.md
> DOCS-2422: Add payout currencies

- content/payment-methods/billing-suite/afterpay/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/betaalpermaand/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/e-invoicing/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/in3/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/pay-after-delivery/user-guide/processing-refunds.md
> DOCS-2424: Clarify processing refunds in backend

- layouts/partials/section-navigation.html
- layouts/payment-methods/child.html
> DOCS-0000: Add on-page navigation to payment method pages

- content/payment-methods/billing-suite/afterpay/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/betaalpermaand/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/e-invoicing/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/in3/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/pay-after-delivery/user-guide/processing-refunds.md
> DOCS-2437: Reformat processing refunds in Billing Suite

- content/integrations/accounting-integrations/_index.md
- content/integrations/cash register software/_index.md
- content/integrations/community/_index.md
- content/integrations/credit and subscription management/_index.md
- content/integrations/ecommerce-integrations/_index.md
- content/integrations/payment-components/_index.md
- content/integrations/payment-components/customizing-payment-components.md
- content/integrations/payment-components/integrating-multiple-payment-methods.md
- content/integrations/payment-components/integrating-single-payment-method.md
- content/integrations/pwa/_index.md
- content/integrations/reservation management/_index.md
- content/integrations/wrappers/_index.md
> DOCS-2441: Improve short descriptions for Integrations

- content/integrations/payment-components/integrating-multiple-payment-methods.md
- content/integrations/payment-components/integrating-single-payment-method.md
> DOCS-2435: Fix typos in Payment component manuals

- content/integrations/ecommerce-integrations/opencart/changelog.md
> Release of 3.10.4 OpenCart plugin

- content/integrations/ecommerce-integrations/woocommerce/_index.md
- content/integrations/ecommerce-integrations/woocommerce/changelog.md
> Release of 4.7.0 WooCommerce plugin

- content/payment-methods/billing-suite/e-invoicing/activation.md
> DOCS-2443: Expand E-Invoicing activation

- content/integrations/payment-components/integrating-multiple-payment-methods.md
- content/integrations/payment-components/integrating-single-payment-method.md
> DOCS-2442: Fix MSP

- content/payment-methods/banks/bancontact-qr/user-guide/processing-refunds.md
- content/payment-methods/banks/bancontact/user-guide/processing-refunds.md
- content/payment-methods/banks/bank-transfer/user-guide/processing-refunds.md
- content/payment-methods/banks/ideal/user-guide/processing-refunds.md
- content/payment-methods/banks/idealqr/user-guide/processing-refunds.md
- content/payment-methods/banks/ing-home-pay/user-guide/processing-refunds.md
- content/payment-methods/banks/sofort-banking/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/afterpay/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/betaalpermaand/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/e-invoicing/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/in3/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
- content/payment-methods/billing-suite/pay-after-delivery/user-guide/processing-refunds.md
> DOCS-2445: Add payment method name to refund rules dropdown

- content/payment-methods/billing-suite/klarna/about.md
> DOCS-2433: Remove UK from Klarna countries

- content/payment-methods/billing-suite/pay-after-delivery/user-guide/changing-order-status-to-shipped.md
> DOCS-2270: Add shipping policy links to Pay After Delivery

- content/integrations/ecommerce-integrations/woocommerce/faq/rest-endpoint-is-blocked.md
> PLGWOOS-717: Add FAQ item related with non processed post notifications due rest endpoint blocked

- content/faq/payment-regulations/about-3D-secure.md
- content/payment-methods/credit-and-debit-cards/american-express/user-guide/chargebacks.md
- content/payment-methods/credit-and-debit-cards/american-express/user-guide/processing-refunds.md
- content/payment-methods/credit-and-debit-cards/user-guide/3d-secure.md
> DOCS-2457: Add chargebacks to Amex user guide

- content/tools/accounting/reports/financial-summary.md
- content/tools/accounting/reports/transaction-summary.md
> DOCS-2458: Fix broken link in Transaction report

- content/integrations/ecommerce-integrations/magento2/faq/activating-credit-card-component.md
> DOCS-0000: Add user guide for Credit Card Component in Magento 2

- content/payment-methods/billing-suite/klarna/about.md
- content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
> DOCS-2432: Clarify Klarna discounts

- content/payment-methods/credit-and-debit-cards/dankort/_index.md
- content/payment-methods/credit-and-debit-cards/dankort/activation.md
- content/payment-methods/credit-and-debit-cards/dankort/dankort.md
- content/payment-methods/credit-and-debit-cards/dankort/processing-refunds.md
- content/payment-methods/credit-and-debit-cards/dankort/testing.md
> DOCS-2363: Restructure and tech edit Dankort

- content/integrations/ecommerce-integrations/magento1/_index.md
- content/integrations/ecommerce-integrations/prestashop-1-6/_index.md
- content/integrations/ecommerce-integrations/prestashop-1-7/_index.md
- content/integrations/ecommerce-integrations/shopify/_index.md
- content/integrations/ecommerce-integrations/shopware5/_index.md
- content/integrations/ecommerce-integrations/shopware6/_index.md
- content/integrations/ecommerce-integrations/woocommerce/_index.md
> DOCS-2431: Remove ecommerce platform release newsletters

- layouts/partials/block-faq-intro.html
> DOCS-0000: Change size of user guide button payment types

- content/payment-methods/prepaid-cards/gift-cards/about.md
- content/payment-methods/prepaid-cards/gift-cards/payment-flow.md
- content/payment-methods/prepaid-cards/gift-cards/user-guide/processing-refunds.md
- content/payment-methods/prepaid-cards/paysafecard/about.md
- content/payment-methods/prepaid-cards/paysafecard/processing-refunds.md
> DOCS-2470: Clarify prepaid card collection and refunds

- content/getting-started/glossary/_index.md
> DOCS-2471: Deploy glossary

- content/api/introduction.md
> DOCS-2468: Fix link in API Reference intro

- content/api/introduction.md
- content/integrations/ecommerce-integrations/lightspeed_app/faq/processing-refunds.md
> DOCS-2469: Add known error to Lightspeed

- content/payment-methods/prepaid-cards/gift-cards/about.md
- content/payment-methods/prepaid-cards/gift-cards/user-guide/about-open-closed-loop.md
- content/payment-methods/wallet/applepay/_index.md
- content/payment-methods/wallet/applepay/about.md
- content/payment-methods/wallet/applepay/activation.md
- content/payment-methods/wallet/applepay/integration-and-testing.md
> DOCS-2447: Clarify Apple Pay page

- content/payment-methods/wallet/paypal/activation.md
> DOCS-1760: Add account information to PayPal

- content/payment-methods/prepaid-cards/gift-cards/about.md
> DOCS-1992: Add Klus Cadeau to Gift cards

- content/payment-methods/wallet/paypal/activation.md
> DOCS-2477: Clarify PayPal account information

- content/payment-methods/fastcheckout/_index.md
- content/payment-methods/fastcheckout/about-fastcheckout.md
> DOCS-2478: Fix FastCheckout capitalization

- content/payment-methods/prepaid-cards/gift-cards/about.md
> DOCS-1996: Add Sports Gift Card to Gift cards page

- content/faq/finance/evaluating-uncleared-card-transactions.md
- content/faq/finance/viewing-your-daily-balance.md
- content/faq/finance/viewing-your-uncleared-balance.md
> DOCS-2479: Document Uncleared balance report

- content/payment-methods/wallet/paypal/user-guide/processing-refunds.md
> DOCS-608: Clarify PayPal refund status

- content/payment-methods/billing-suite/betaalpermaand/user-guide/changing-order-status-to-shipped.md
- content/payment-methods/billing-suite/e-invoicing/payment-flow.md
- content/payment-methods/billing-suite/e-invoicing/user-guide/changing-order-status-to-shipped.md
- content/payment-methods/billing-suite/in3/payment-flow.md
- content/payment-methods/billing-suite/in3/user-guide/changing-order-status-to-shipped.md
- content/payment-methods/billing-suite/klarna/user-guide/changing-order-status-to-shipped.md
- content/payment-methods/billing-suite/pay-after-delivery/user-guide/changing-order-status-to-shipped.md
> DOCS-2429: Clarify changing to shipped status

- .github/banned_words.txt
- content/tools/partner-account-control/partner-compensation.md
> DOCS-0000: banned_words - working days

- content/getting-started/glossary/_index.md
- content/payment-methods/credit-and-debit-cards/_index.md
- content/payment-methods/credit-and-debit-cards/user-guide/glossary.md
> DOCS-2411: Add About and Glossary to Credit cards

- content/payment-methods/wallet/alipay/about.md
> DOCS-2474: Update Alipay product rules

- content/how-to-find-us/amsterdam-office-location.md
> DOCS-2476: Update parking instructions

- content/payment-methods/credit-and-debit-cards/user-guide/about-chargebacks.md
- content/payment-methods/credit-and-debit-cards/user-guide/chargeback-reasons-and-required-evidence.md
- content/payment-methods/credit-and-debit-cards/user-guide/disputing-chargebacks.md
- content/payment-methods/credit-and-debit-cards/user-guide/evaluating-uncleared-transactions.md
- content/payment-methods/credit-and-debit-cards/user-guide/minimizing-chargebacks.md
- content/payment-methods/credit-and-debit-cards/user-guide/pci-dss-compliance.md
> DOCS-2484: Tech edit chargebacks

- content/account/multisafepay-account/adding-descriptors-to-customer-bank-statements.md
- content/account/multisafepay-account/paying-out-funds-from-your-multisafepay-balance.md
- content/tools/email-template/_index.md
> DOCS-2524: Move Tokens to Email templates

- content/integrations/ecommerce-integrations/craftcommerce/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/cs-cart/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/drupal7/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/drupal8/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/magento1/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/magento2/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/opencart/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/oscommerce/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/prestashop-1-6/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/prestashop-1-7/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/shopware5/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/shopware6/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/virtuemart/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/woocommerce/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/x-cart/faq/processing-refunds.md
- content/integrations/ecommerce-integrations/zencart/faq/processing-refunds.md
> DOCS-2092: Clarify refund rules for plugins

- content/integrations/ecommerce-integrations/magento2/faq/enabling-tokenization.md
- content/integrations/ecommerce-integrations/prestashop-1-6/faq/enabling-tokenization.md
- content/integrations/ecommerce-integrations/prestashop-1-7/faq/enabling-tokenization.md
- content/integrations/ecommerce-integrations/shopware6/faq/enabling-tokenization.md
- content/integrations/ecommerce-integrations/woocommerce/faq/enabling-tokenization.md
> DOCS-2113: Clarify tokenization in plugin manuals

- content/account/api-onboarding/_index.md
- content/account/partner-account-control/about-account-types.md
- content/account/partner-account-control/about-partner-invoices.md
- content/account/partner-account-control/creating-affiliate-accounts.md
- content/account/partner-account-control/customizing-welcome-email.md
- content/account/partner-account-control/managing-affiliate-accounts.md
- content/account/partner-account-control/managing-commissions.md
- content/getting-started/create-a-test-account/_index.md
> DOCS-2264: Document account types

- content/security-and-legal/gdpr/_index.md
- content/security-and-legal/payment-regulations/3d-secure-2.md
- content/security-and-legal/payment-regulations/about-3D-secure.md
- content/security-and-legal/payment-regulations/about-payment-service-directive-2.md
- content/security-and-legal/payment-regulations/about-pcidss.md
- content/security-and-legal/payment-regulations/about-strong-customer-authentication.md
- content/security-and-legal/payment-regulations/about-surcharges.md
> DOCS-2528: Merge GDPR and create PCI DSS page

- content/security-and-legal/payment-regulations/about-pcidss.md
> DOCS-2531: Update PCI DSS

- content/business/order-management/_index.md
- content/business/website/_index.md
- content/business/website/duda/_index.md
- content/business/website/mijndomein/_index.md
> DOCS-1145: Add Duda and MijnDomein

- content/business/growth/Sherpaan/_index.md
> DOCS-1869-2: Add svg logos to Picqer and Sherpaan

- content/payments/methods/billing-suite/afterpay/about.md
- content/payments/methods/billing-suite/betaalpermaand/about.md
- content/payments/methods/billing-suite/e-invoicing/about.md
- content/payments/methods/billing-suite/in3/about.md
- content/payments/methods/billing-suite/klarna/about.md
> DOCS-1944: Add MultiFactor shipping policy to billing suite

- content/account/multisafepay-account/_index.md
- content/account/multisafepay-account/adding-descriptors-to-customer-bank-statements.md
- content/account/multisafepay-account/adding-funds-to-your-multisafepay-balance.md
- content/account/multisafepay-account/enabling-converting-currencies.md
- content/account/multisafepay-account/multisafepay-vat.md
- content/account/multisafepay-account/paying-out-funds-from-your-multisafepay-balance.md
- content/account/multisafepay-account/viewing-your-daily-balance.md
- content/account/multisafepay-account/viewing-your-uncleared-balance.md
- content/getting-started/set-up-your-account/_index.md
- content/getting-started/set-up-your-account/user-guide/adding-users.md
- content/getting-started/set-up-your-account/user-guide/adding-your-financial-email-address.md
- content/getting-started/set-up-your-account/user-guide/multisafepay-app.md
- content/getting-started/set-up-your-account/user-guide/setting-your-notification-url.md
> DOCS-2537: Move Adding users to Set up account

- content/developer/general/excluding-referrals-in-google-analytics.md
> DOCS-2083: Remove call for testing Magento 2 Google Analytics

- content/api/payment_methods/post_order_afterpay.md
- content/api/payment_methods/post_order_applepay.md
> DOCS-2530: Add maximum character limit to AfterPay order ID

- content/payments/methods/billing-suite/afterpay/_index.md
- content/payments/methods/billing-suite/afterpay/about.md
> DOCS-2544: Update AfterPay in Belgium

- content/payments/integrations/ecommerce-platforms/magento1/_index.md
> DOCS-2541: Remove MarketPlace from Magento 1

- content/payments/methods/prepaid-cards/gift-cards/user-guide/creating-custom-gift-cards.md
> DOCS-2543: Add closed-open loop to custom gift cards

- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/synchronizing-multisafepay-payment-links.md
> DOCS-2259: Clarify Lightspeed order id

- content/payments/integrations/ecommerce-platforms/magento2/old/_index.md
> DOCS-1860: Add end-of-life message to deprecated M2 plugin

- content/api/reference/dynamic-styling.md
- content/payments/integrations/ecommerce-platforms/opencart/faq/supported-checkouts-themes.md
- content/payments/integrations/ecommerce-platforms/zilvercms/faq/_index.md
- content/payments/integrations/ecommerce-platforms/zilvercms/faq/supported-payment-methods.md
- content/security-and-legal/risk-and-fraud/adding-and-deactivating-business-bank-accounts.md
- layouts/partials/meta/opengraph.html
> DOCS-2545: Fix missed meta-descriptions

- content/account/api-onboarding/add-bank-accounts.md
- content/account/api-onboarding/add-ubos.md
- content/account/api-onboarding/add-websites.md
- content/account/api-onboarding/create-account.md
- content/api/api/authentication.md
- content/business/reservation-management/_index.md
- content/getting-started/set-up-your-account/user-guide/viewing-your-api-key.md
- content/payments/integrations/ecommerce-platforms/ccvshop/_index.md
- content/payments/integrations/ecommerce-platforms/shopify/_index.md
- content/payments/integrations/ecommerce-platforms/virtuemart/_index.md
> DOCS-767: Clarify site API key for Shopify

- content/api/other_requests/chargeback.md
- content/getting-started/glossary/_index.md
- content/payments/methods/credit-and-debit-cards/user-guide/glossary.md
- content/payments/refunds-and-chargebacks/chargebacks/about-chargebacks.md
- content/payments/refunds-and-chargebacks/chargebacks/chargeback-reasons-and-required-evidence.md
- content/payments/refunds-and-chargebacks/chargebacks/disputing-chargebacks.md
> DOCS-2546: Fixes to Chargebacks

- content/business/accounting/reports/accountant-export.md
- content/business/accounting/reports/advanced-reporting.md
- content/business/accounting/reports/financial-report.md
- content/business/accounting/reports/financial-summary.md
- content/business/accounting/reports/payout-report.md
- content/business/accounting/reports/transaction-summary.md
> DOCS-2328: Document reports

- content/payments/integrations/ecommerce-platforms/magento2/_index.md
- content/payments/integrations/ecommerce-platforms/magento2/faq/changes-to-new-plugin.md
> DOCS: Add broken Magento 2 aliases

- content/business/accounting/integrations/Exact/integrations/denovit.md
- content/business/accounting/integrations/Snelstart/integrations/premarc.md
- content/business/accounting/integrations/e-boekhouden/_index.md
- content/business/subscription-management/Twikey/_index.md
> DOCS-1492: Clarify MultiSafepay payment links in accounting integrations

- content/payments/integrations/ecommerce-platforms/magento2/_index.md
> DOCS-2547: Fix broken link on Magento 2 manual

- content/payments/integrations/ecommerce-platforms/craftcommerce/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/cs-cart/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/drupal7/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/drupal8/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/magento1/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/magento2/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/opencart/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/oscommerce/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/prestashop-1-7/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/shopify/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/shopware5/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/shopware6/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/virtuemart/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/x-cart/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/zencart/faq/processing-refunds.md
> DOCS-2550: Clarify refunding more than original amount in plugin manuals

- content/integration-team/integration-review-nl.md
> DOCS-2560: Make pronouns consistent in Integration Team page

- content/payments/integrations/ecommerce-platforms/magento2/_index.md
> DOCS-2562: Clarify stock handling command in M2 manual

- content/payments/methods/wallet/paypal/payment-flow.md
> DOCS-2567: Fix PayPal payment flow

- content/api/payment_methods/post-order-giropay.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-idealqr.md
> DOCS-2571: Tech edit API Reference 3

- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-cbc.md
- content/api/payment_methods/post-order-dirdeb.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-kbc.md
- content/api/payment_methods/post-order-klarna.md
- content/api/payment_methods/post-order-payafter.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-sofort.md
- content/api/payment_methods/post_order_afterpay.md
- content/api/payment_methods/post_order_in3.md
- content/api/payment_methods/post_order_request_to_pay.md
> DOCS-2582: Fix API payment method redirect and direct anchors

- content/payments/integrations/ecommerce-platforms/woocommerce/_index.md
- content/payments/integrations/ecommerce-platforms/woocommerce/changelog.md
Release of 4.8.0 WooCommerce plugin
> Release of 4.8.0 WooCommerce plugin

- content/payments/checkout/payment-pages/activating-payv2.md
- content/payments/checkout/payment-pages/classic-payment-page.md
- content/payments/checkout/payment-pages/displaying-all-payment-methods.md
- content/payments/checkout/payment-pages/dynamic-styling-payment-pages.md
- content/payments/checkout/payment-pages/requirements-for-visa.md
- content/payments/checkout/payment-pages/styling-payment-pages.md
> DOCS-2589: Remove Activating PayV2 video

- content/payments/methods/billing-suite/pay-after-delivery/_index.md
> DOCS-2277: Add search terms to PAD

- content/security-and-legal/payment-regulations/3D-secure.md
- content/security-and-legal/payment-regulations/about-surcharges.md
- content/security-and-legal/payment-regulations/dynamic-3d.md
- content/security-and-legal/payment-regulations/pci-dss.md
- content/security-and-legal/payment-regulations/psd2.md
- content/security-and-legal/payment-regulations/sca.md
> DOCS-2592: Restore Dynamic 3D Secure

- content/security-and-legal/payment-regulations/about-3D-secure.md
- content/security-and-legal/payment-regulations/versions-3d-secure.md
> DOCS-2591-2: Fix 3D Secure dropdowns

- content/api/gateways/get_issuers.md
> DOCS-2256: Add note to Retrieve gateway issuers

- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/processing-refunds.md
> DOCS-2590: Add partial refunds to Lightspeed app

- content/payments/methods/wallet/paypal/payment-flow.md
> DOCS-2587: Remove step 5 from PayPal payment flow

- content/payments/integrations/ecommerce-platforms/lightspeed_app/_index.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/adding-inline-buy-buttons.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/adding-inline-newsletter-checkboxes.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/adding-payment-method-footer-icons.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/adding-payment-method-logos.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/changing-api-key-and-environment.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/disabling-payment-methods.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/logging-in.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/multiple-accounts.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/supported-payment-methods.md
> DOCS-2581: Update Lightspeed app sign in details

- content/api/orders/create-tokenization-order.md
- content/api/orders/post_order_recurring.md
- content/api/orders/specify-recurring-model.md
- content/api/reference/payment_details.md
- content/payments/features/tokenization/_index.md
> DOCS-2258-2: Link API recurring_model to Tokenization

- content/api/orders/get_order.md
- content/api/reference/costs-object.md
> DOCS-2594: Clarify PSP ID

- content/payments/integrations/ecommerce-platforms/magento2/_index.md
- content/payments/integrations/ecommerce-platforms/magento2/old/_index.md
> deleted all connections between old one and new one plugin

- content/payments/integrations/ecommerce-platforms/woocommerce/_index.md
- content/payments/integrations/ecommerce-platforms/woocommerce/changelog.md
> Release of 4.8.1 WooCommerce plugin

- content/payments/features/recurring-payments/about-recurring-payments.md
- content/payments/methods/banks/bancontact-qr/about.md
- content/payments/methods/banks/bancontact/about.md
- content/payments/methods/banks/bank-transfer/about.md
- content/payments/methods/banks/belfius/about.md
- content/payments/methods/banks/cbc/about.md
- content/payments/methods/banks/dotpay/about.md
- content/payments/methods/banks/eps/about.md
- content/payments/methods/banks/giropay/about.md
- content/payments/methods/banks/ideal/about.md
- content/payments/methods/banks/idealqr/about.md
- content/payments/methods/banks/ing-home-pay/about.md
- content/payments/methods/banks/kbc/about.md
- content/payments/methods/banks/request-to-pay/about.md
- content/payments/methods/banks/sepa-direct-debit/about.md
- content/payments/methods/banks/sofort-banking/about.md
- content/payments/methods/banks/trustly/about.md
- content/payments/methods/banks/trustpay/about.md
- content/payments/methods/billing-suite/afterpay/about.md
- content/payments/methods/billing-suite/betaalpermaand/about.md
- content/payments/methods/billing-suite/e-invoicing/about.md
- content/payments/methods/billing-suite/in3/about.md
- content/payments/methods/billing-suite/klarna/about.md
- content/payments/methods/prepaid-cards/gift-cards/about.md
- content/payments/methods/prepaid-cards/paysafecard/about.md
- content/payments/methods/wallet/alipay/about.md
- content/payments/methods/wallet/applepay/about.md
> DOCS-2597: Clarify SEPA Direct Debit recurring payments

- content/business/order-management/_index.md
> DOCS-1871: Document iDEAL status check for MplusKASSA

- content/payments/methods/wallet/paypal/activation.md
> DOCS-2451: Update PayPal activation

- content/payments/methods/wallet/paypal/activation.md
> DOCS-2451-2: Further PayPal activation clarification

- content/api/reference/payment_options.md
- content/developer/api/google-analytics-tracking.md
- content/developer/api/masking-iban-numbers.md
- content/developer/api/notification-url.md
- content/developer/api/redirect-url.md
- content/developer/api/required-transaction-details.md
- content/developer/api/using-locale-parameters.md
- content/developer/api/validating-customer-ip-address.md
- content/developer/api/xml-api.md
> DOCS-1895: Document redirect URL

- content/payments/testing/test-payment-details.md
> DOCS-2607: Fix AfterPay sign in link

- content/payments/testing/test-payment-details.md
> DOCS-2606: Add rejection testing to AfterPay

- content/payments/features/tokenization/_index.md
> DOCS-1537-2: Clarify recurring models used in SDKs and plugins

- content/api/accounts/payouts.md
- content/api/orders/cancel-order.md
- content/api/orders/cancel_authorized_reserved-order.md
- content/api/orders/create-tokenization-order.md
- content/api/orders/direct_flexible_3d_disabled.md
- content/api/orders/direct_flexible_3d_enabled.md
- content/api/orders/get-tokenization-order-details.md
- content/api/orders/get_order.md
- content/api/orders/order_status_authorised_transaction.md
- content/api/orders/order_status_captured_transaction.md
- content/api/orders/post_order_direct.md
- content/api/orders/zero-authorization-order-status.md
- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-cbc.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-ideal.md
- content/api/reference/costs-object.md
- content/api/reference/payment_methods-object.md
> DOCS-2609: Fixes to cancel order request

- content/api/payment_methods/post-order-afterpay.md
> DOCS-2606-2: Change email address in AfterPay direct request

- content/payments/methods/billing-suite/klarna/payment-flow.md
> DOCS-2610: Fix Klarna payment flow

- content/payments/methods/billing-suite/betaalpermaand/payment-flow.md
> DOCS-2132-2: Add when merchants can cancel orders to Betaal per Maand

- content/integration-team/connectjs.md
- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
- content/integration-team/webshop-access.md
> DOCS-2564: Tidy Integration Team LinkedIn

- content/payments/methods/billing-suite/pay-after-delivery/about.md
> DOCS-0000: Remove period after email address

- content/payments/methods/banks/bancontact-qr/integration-and-testing.md
- content/payments/methods/banks/bancontact/integration-and-testing.md
- content/payments/methods/banks/bank-transfer/integration-and-testing.md
- content/payments/methods/banks/belfius/integration-and-testing.md
- content/payments/methods/banks/cbc/integration-and-testing.md
- content/payments/methods/banks/dotpay/integration-and-testing.md
- content/payments/methods/banks/eps/integration-and-testing.md
- content/payments/methods/banks/giropay/integration-and-testing.md
- content/payments/methods/banks/ideal/integration-and-testing.md
- content/payments/methods/banks/idealqr/integration-and-testing.md
- content/payments/methods/banks/kbc/integration-and-testing.md
- content/payments/methods/banks/request-to-pay/integration-and-testing.md
- content/payments/methods/banks/sepa-direct-debit/integration-and-testing.md
- content/payments/methods/banks/sofort-banking/integration-and-testing.md
- content/payments/methods/banks/trustly/integration-and-testing.md
- content/payments/methods/banks/trustpay/integration-and-testing.md
- content/payments/methods/billing-suite/afterpay/integration-and-testing.md
- content/payments/methods/billing-suite/betaalpermaand/integration-and-testing.md
- content/payments/methods/billing-suite/in3/integration-and-testing.md
- content/payments/methods/billing-suite/klarna/integration-and-testing.md
- content/payments/methods/billing-suite/pay-after-delivery/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/dankort/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/maestro/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/postepay/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/vpay/integration-and-testing.md
- content/payments/methods/prepaid-cards/gift-cards/integration-and-testing.md
- content/payments/methods/wallet/alipay/integration-and-testing.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
> DOCS-2637: Rephrase API integration for payment methods

- content/account/account-setup/deleting-websites.md
- content/account/account-setup/setting-account-language.md
- content/getting-started/set-up-your-account/_index.md
> DOCS-2642: Document setting your account language

- content/api/orders/cancel_authorized_reserved-order.md
- content/api/orders/manual-capture.md
- content/api/orders/manual_capture_full.md
- content/api/orders/manual_capture_partial.md
> DOCS-2640: Update manual capture API reference

- content/api/introduction.md
- content/payments/features/recurring-payments/processing-recurring-payments.md
- content/payments/features/tokenization/_index.md
> DOCS-2604: Fix recurring-payment URLs

- content/account/api-onboarding/_index.md
- content/account/api-onboarding/add-ubos.md
- content/account/onboarding/onboarding-process.md
- content/account/onboarding/ultimate-beneficial-owner-form.md
- layouts/shortcodes/collapse.html
- static/css/main.css
- Decapitalize all instances of Ultimate Beneficial Owner
- Fix hyperlinks of api-onboarding pages
- Update collapse shortcode
- Change CSS of details (summary is now only blue on hover)
- Tested
> DOCS-0000: Update collapse shortcode

- content/getting-started/glossary/_index.md
> DOCS-2650: Update payment definition

- content/business/accounting/transactions-api-endpoint/_index.md
- content/payments/about-payments/about-MultiSafepay-statuses.md
> DOCS-2639: Fix links on Transactions API endpoint page

- content/payments/methods/banks/trustpay/_index.md
- content/payments/methods/banks/trustpay/about.md
> DOCS-2653: Fix TrustPage - content not displaying

- content/api/orders/cancel-authorized-reserved-order.md
- content/api/orders/create-direct-order.md
- content/api/orders/create-tokenization-order.md
- content/api/orders/flexible-3d-disabled-direct.md
- content/api/orders/flexible-3d-enabled-direct.md
- content/api/orders/get-order-details.md
- content/api/orders/get-tokenization-order-details.md
- content/api/orders/manual-capture-full.md
- content/api/orders/manual-capture-partial.md
- content/api/orders/order-status-authorised-transaction.md
- content/api/orders/order-status-captured-transaction.md
- content/api/orders/server-to-server-credit-cards.md
- content/api/orders/update-order.md
- content/api/orders/zero-authorization-order-status.md
- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-cbc.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-in3.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-kbc.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-request-to-pay.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-sofort.md
> DOCS-2659: Clarify reason parameter

- content/business/accounting/transactions-api-endpoint/_index.md
- content/developer/api/google-analytics-tracking.md
- content/developer/api/masking-iban-numbers.md
- content/developer/api/notification-url.md
- content/developer/api/pagination.md
- content/developer/api/redirect-url.md
- content/developer/api/xml-api.md
> DOCS-2663: Move pagination content to Developer - About

- content/api/other_requests/retrieve-transactions.md
- content/api/other_requests/retrieve-website-categories.md
- content/business/accounting/transactions-api-endpoint/_index.md
> DOCS-2662: Move transactions endpoint content to API Reference

- .github/banned_words.py
- .github/banned_words.txt
> DOCS-2664: Update banned_words.py to ignore front matter

- content/payments/checkout/payment-pages/activating-payv2.md
- content/payments/checkout/payment-pages/dynamic-styling-payment-pages.md
- content/payments/checkout/payment-pages/styling-payment-pages.md
> DOCS-2669: Add mobile responsive to PayV2

- content/payments/integrations/ecommerce-platforms/magento2/faq/hyva-themes-checkout.md
- content/payments/integrations/ecommerce-platforms/magento2/faq/supported-magento2-checkouts.md
> DOCS-2574: Add Hyva page to Magento 2 user guide

- content/payments/integrations/ecommerce-platforms/shopware5/faq/missing-session-data.md
> Add information about missing session data within Shopware5

- content/payments/integrations/ecommerce-platforms/woocommerce/_index.md
- content/payments/integrations/ecommerce-platforms/woocommerce/changelog.md
Release of 4.8.2 WooCommerce plugin
> Release of 4.8.2 WooCommerce plugin

- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
> DOCS-0000: remove LinkedIn profile from integration team page

- content/payments/integrations/ecommerce-platforms/ccvshop/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/craftcommerce/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/cs-cart/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/drupal7/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/drupal8/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/ecwid/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/logic4/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/logivert/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/magento1/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/magento2/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/magento2/old/faq/available-payment-methods-magento2.md
- content/payments/integrations/ecommerce-platforms/mijnwebwinkel/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/myshop/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/odoo/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/opencart/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/oscommerce/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/prestashop-1-6/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/prestashop-1-7/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/shopify/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/shopware5/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/shopware6/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/virtuemart/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/woocommerce/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/x-cart/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/zencart/faq/supported-payment-methods.md
- content/payments/integrations/ecommerce-platforms/zilvercms/faq/supported-payment-methods.md
- content/payments/methods/banks/_index.md
- content/payments/testing/test-payment-details.md
> DOCS-2686: Changing Banks to Banking methods

- content/account/account-setup/adding-websites.md
> DOCS-2681: Clarify where website names appear

- content/payments/integrations/ecommerce-platforms/woocommerce/_index.md
- content/payments/integrations/ecommerce-platforms/woocommerce/changelog.md
Release of 4.8.3 WooCommerce plugin
> Release of 4.8.3 WooCommerce plugin

- content/developer/general/generic-gateways.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/_index.md
- content/payments/methods/credit-and-debit-cards/dankort/_index.md
> DOCS-2502: Document integrating co-branded cards with generic gateway

- content/payments/integrations/ecommerce-platforms/magento2/faq/updating-the-plugin.md
> Update the composer update command

- content/payments/methods/billing-suite/klarna/payment-flow.md
> DOCS-2610-2: Adjust Klarna payment flow

- content/payments/testing/test-payment-details.md
> DOCS-2607-2: Clarify getting AfterPay test API key

- content/payments/integrations/ecommerce-platforms/magento2/faq/applying-surcharges.md
- content/payments/integrations/ecommerce-platforms/woocommerce/faq/applying-surcharges.md
> DOCS-2601: add applying surcharges section to woocommerce user guide

- content/payments/methods/billing-suite/klarna/payment-flow.md
> DOCS-2700: Clarify Klarna settlement period

- content/security-and-legal/payment-regulations/psd2.md
> DOCS-2698: remove alert from PSD2 statement

- content/payments/integrations/ecommerce-platforms/woocommerce/faq/applying-surcharges.md
> DOCS-2601: correct woocommerce surcharge statement

- content/api/orders/apply-dynamic-template.md
- content/api/orders/create-direct-order.md
- content/api/orders/create-tokenization-order.md
- content/api/orders/flexible-3d-disabled-direct.md
- content/api/orders/flexible-3d-enabled-direct.md
- content/api/orders/get-order-details.md
- content/api/orders/get-tokenization-order-details.md
- content/api/orders/order-status-authorised-transaction.md
- content/api/orders/order-status-captured-transaction.md
- content/api/orders/server-to-server-credit-cards.md
- content/api/orders/zero-authorization-order-status.md
- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-cbc.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-in3.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-kbc.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-request-to-pay.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-sofort.md
- content/api/reference/payment-details-object.md
- content/api/reference/payment-methods-object.md
- content/api/reference/payment-options-object.md
- content/api/reference/settings-object.md
- content/api/reference/shopping-cart-object.md
> DOCS-2695: correct dead links

- content/api/orders/adjust-payment-link-lifetime.md
> DOCS-2672: clarify location of payment link lifetime in POST request

- content/api/reference/variables.md
> DOCS-2709: Add reference page for var 1 2 3

- content/api/orders/create-direct-order.md
- content/api/orders/create-redirect-order.md
> DOCS-2708: Add shopping_cart to direct and redirect order requests

- content/payments/integrations/ecommerce-platforms/magento2/faq/activating-magento-vault.md
> DOCS-2703: Link to Magento Vault docs

- content/account/api-onboarding/create-account.md
- contact_person replaced by user object
- Tested
> Update /signup-account request

- content/payments/methods/banks/ing-home-pay/activation.md
> DOCS-2559: Clarify ING Home Pay activation

- content/payments/integrations/ecommerce-platforms/magento2/_index.md
- content/payments/integrations/ecommerce-platforms/magento2/faq/supported-magento2-checkouts.md
> PLGMAG2V2-287: Officially support OneStepCheckout.com

- content/payments/integrations/ecommerce-platforms/opencart/changelog.md
Changelog entries related with 3.10.5 OpenCart plugin
> Release of 3.10.5 OpenCart plugin

- content/payments/methods/wallet/googlepay/activation.md
- content/payments/methods/wallet/googlepay/integration-and-testing.md
- content/payments/methods/wallet/googlepay/payment-flow.md
- content/payments/methods/wallet/googlepay/product-rules.md
> DOCS-2726: Review Google Pay

- content/api/reference/payment-options-object.md
> DOCS-2467: change format of payment options object

- content/api/payment_methods/post-order-branded.md
> DOCS-2728: Fix co-branded cards in API ToC

- content/api/payment_methods/post-order-afterpay.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-in3.md
- content/api/payment_methods/post-order-inghome.md
> DOCS-2729: Make redirect-direct order consistent

- content/developer/errors-explained/multisafepay-ip-ranges.md
- content/payments/integrations/ecommerce-platforms/woocommerce/faq/rest-endpoint-is-blocked.md
> DOCS-2665: remove banned words

- content/api/orders/create-direct-order.md
- content/api/orders/create-tokenization-order.md
- content/api/orders/flexible-3d-disabled-direct.md
- content/api/orders/flexible-3d-enabled-direct.md
- content/api/orders/get-order-details.md
- content/api/orders/get-tokenization-order-details.md
- content/api/orders/order-status-authorised-transaction.md
- content/api/orders/order-status-captured-transaction.md
- content/api/orders/server-to-server-credit-cards.md
- content/api/orders/zero-authorization-order-status.md
- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-cbc-kbc.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-in3.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-request-to-pay.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-sofort.md
> DOCS-2734: Remove FastCheckout links from API

- content/api/orders/refund-with-shopping-cart.md
> DOCS-2572: Add duplicate object in Refund with shopping cart example

- content/api/introduction.md
- content/api/orders/create-redirect-order.md
- content/api/other_requests/retrieve-transactions.md
- content/api/payment_methods/post-order-afterpay.md
- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-american-express.md
- content/api/payment_methods/post-order-applepay.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-branded.md
- content/api/payment_methods/post-order-cbc-kbc.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-googlepay.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-idealqr.md
- content/api/payment_methods/post-order-in3.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-klarna.md
- content/api/payment_methods/post-order-maestro.md
- content/api/payment_methods/post-order-mastercard.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-request-to-pay.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-sofort.md
- content/api/payment_methods/post-order-trustly.md
- content/api/payment_methods/post-order-trustpay.md
- content/api/reference/payment-details-object.md
- content/payments/checkout/payment-link/generating-payment-links.md
- content/payments/features/tokenization/_index.md
> DOCS-2737: Fit type parameter to direct/redirect

- content/account/manage-your-balance/making-payouts.md
> DOCS-2735: update manual payout steps

- content/api/orders/create-redirect-order.md
- content/api/orders/generate-payment-link.md
- content/api/orders/manual-capture.md
- content/api/orders/split-payments.md
- content/api/orders/zero-authorization.md
- content/api/payment_methods/post-order-alipay.md
- content/api/payment_methods/post-order-bancontact.md
- content/api/payment_methods/post-order-bancontactqr.md
- content/api/payment_methods/post-order-banktrans.md
- content/api/payment_methods/post-order-belfius.md
- content/api/payment_methods/post-order-branded.md
- content/api/payment_methods/post-order-cbc-kbc.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-trustly.md
> DOCS-2739: Remove checkout parameter and clarify paymentlink

- content/api/other_requests/specify-vouchers.md
> DOCS-2467: correct specify vouchers API typo

- content/api/orders/tokenization-orders.md
- content/api/orders/validate-shopping-cart.md
- content/api/orders/zero-authorization-order-status.md
- content/api/other_requests/delete-token.md
- content/api/other_requests/pad-pre-check.md
- content/api/other_requests/retrieve-customer-tokens.md
- content/api/other_requests/retrieve-token-details.md
- content/api/other_requests/retrieve-website-categories.md
- content/api/other_requests/update-card-expiry-date.md
- content/api/payment_methods/post-order-cbc-kbc.md
> DOCS-2721: Fix Netlify deploys

- content/account/api-onboarding/add-websites.md
> DOCS-2742: Fix /accounts endpoint

- content/payments/methods/banks/sofort/_index.md
- content/payments/methods/banks/sofort/activation.md
- content/payments/methods/banks/sofort/integration-and-testing.md
- content/payments/methods/banks/sofort/payment-flow.md
- content/payments/methods/banks/sofort/product-rules.md
> DOCS-2730: fix sofort svg image

- content/payments/checkout/payment-components/multiple/multiple-1.md
- content/payments/checkout/payment-components/multiple/multiple-3.md
- content/payments/checkout/payment-components/multiple/multiple-4.md
- content/payments/checkout/payment-components/single/single-1.md
- content/payments/checkout/payment-components/single/single-3.md
- content/payments/checkout/payment-components/single/single-4.md
> DOCS-2748-2: Update payment component version in pathways

- content/payments/checkout/payment-components/single/single-2.md
> DOCS-2722-2: Add gateway codes to Payment Component

- content/payments/checkout/payment-components/_index.md
> DOCS-2723: Update introduction page with new features

- content/payments/checkout/payment-components/multiple/multiple-2.md
- content/payments/checkout/payment-components/single/single-2.md
> DOCS-2736: Document GET /gateways request in multiple

- content/payments/checkout/payment-components/multiple/multiple-3.md
- content/payments/checkout/payment-components/single/single-3.md
> DOCS-2677: Document Bank Transfer flow

- content/payments/checkout/payment-components/multiple/multiple-2.md
- content/payments/checkout/payment-components/single/single-2.md
> DOCS-2738: Document passing credit card gateway object

- content/api/orders/manual-capture.md
- content/api/orders/payment-component-order.md
- content/api/orders/recurring-payments.md
- content/api/orders/server-to-server.md
- content/api/orders/split-payments.md
- content/api/orders/tokenization-order.md
- content/api/orders/zero-authorization.md
- content/payments/checkout/payment-components/multiple/multiple-3.md
- content/payments/checkout/payment-components/single/single-3.md
> DOCS-2622: Create Payment Component API reference

- content/payments/methods/billing-suite/klarna/user-guide/changing-order-status-to-shipped.md
> DOCS-2429-2: Clarify changing Klarna order status

- content/integration-team/connectjs.md
- content/payments/checkout/payment-pages/activating-multisafepay-payment-pages.md
- content/payments/checkout/payment-pages/classic-payment-page.md
- content/payments/methods/banks/belfius/payment-flow.md
- content/payments/methods/banks/idealqr/integration-and-testing.md
- content/payments/methods/wallet/wechatpay/integration-and-testing.md
- content/payments/testing/test-payment-details.md
> DOCS-2753: Remove references to PayV2

- content/payments/methods/billing-suite/betaalpermaand/payment-flow.md
> DOCS-2380: Add email address for cancelling Betaal per Maand orders

- content/payments/methods/wallet/wechatpay/integration-and-testing.md
> DOCS-2643: remove third party mention in wechat pay

- content/payments/checkout/payment-components/multiple/multiple-4.md
- content/payments/checkout/payment-components/single/single-4.md
> DOCS-2755: Fix API pathway

- content/payments/methods/credit-and-debit-cards/american-express/product-rules.md
> DOCS-2756: replace merchant ID with merchant account number

- content/payments/checkout/payment-components/_index.md
> DOCS-2624: Add PCI DSS compliance

- content/security-and-legal/payment-regulations/sca.md
> DOCS-2691: Document TRA and LVP SCA exemptions

- content/api/reference/shopping-cart-object.md
> DOCS-2765: Update shopping_cart object example

- content/api/orders/cancel-order.md
> DOCS-2452: correct exclude_order in cancel-order.md

- content/payments/methods/billing-suite/betaalpermaand/activation.md
- content/payments/methods/billing-suite/betaalpermaand/product-rules.md
> DOCS-2763: Reformat Betaal per Maand eligibility criteria

- content/payments/methods/billing-suite/afterpay/activation.md
> DOCS-2768: Remove dropbox from AfterPay Activation

- content/api/payment_methods/post-order-american-express.md
- content/api/payment_methods/post-order-bancontactqr.md
- content/api/payment_methods/post-order-branded.md
- content/api/payment_methods/post-order-dotpay.md
- content/api/payment_methods/post-order-edenred.md
- content/api/payment_methods/post-order-einvoicing.md
- content/api/payment_methods/post-order-eps.md
- content/api/payment_methods/post-order-gift-card.md
- content/api/payment_methods/post-order-giropay.md
- content/api/payment_methods/post-order-googlepay.md
- content/api/payment_methods/post-order-ideal.md
- content/api/payment_methods/post-order-idealqr.md
- content/api/payment_methods/post-order-in3.md
- content/api/payment_methods/post-order-inghome.md
- content/api/payment_methods/post-order-klarna.md
- content/api/payment_methods/post-order-maestro.md
- content/api/payment_methods/post-order-mastercard.md
- content/api/payment_methods/post-order-payafter.md
- content/api/payment_methods/post-order-paypal.md
- content/api/payment_methods/post-order-request-to-pay.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-sofort.md
- content/api/payment_methods/post-order-trustly.md
- content/api/payment_methods/post-order-trustpay.md
- content/api/payment_methods/post-order-visa.md
- content/api/payment_methods/post-order-wechatpay.md
> DOCS-2771: Group credit cards in API reference

- content/payments/features/tokenization/_index.md
> DOCS-2773: Update tokenization intro

- content/payments/methods/credit-and-debit-cards/american-express/_index.md
- content/payments/methods/credit-and-debit-cards/mastercard/_index.md
- content/payments/methods/credit-and-debit-cards/visa/_index.md
- content/payments/methods/credit-and-debit-cards/vpay/_index.md
> DOCS-2777: Fix weight on credit card page

- content/payments/methods/billing-suite/afterpay/payment-flow.md
- content/payments/methods/billing-suite/betaalpermaand/payment-flow.md
- content/payments/methods/billing-suite/e-invoicing/payment-flow.md
- content/payments/methods/billing-suite/in3/payment-flow.md
- content/payments/methods/billing-suite/klarna/payment-flow.md
- content/payments/methods/credit-and-debit-cards/american-express/payment-flow.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/payment-flow.md
- content/payments/methods/credit-and-debit-cards/dankort/payment-flow.md
- content/payments/methods/credit-and-debit-cards/maestro/payment-flow.md
- content/payments/methods/credit-and-debit-cards/mastercard/payment-flow.md
- content/payments/methods/credit-and-debit-cards/visa/payment-flow.md
- content/payments/methods/credit-and-debit-cards/vpay/payment-flow.md
- content/payments/methods/prepaid-cards/gift-cards/payment-flow.md
- content/payments/methods/prepaid-cards/paysafecard/payment-flow.md
- content/payments/methods/wallet/alipay/payment-flow.md
- content/payments/methods/wallet/applepay/payment-flow.md
- content/payments/methods/wallet/googlepay/payment-flow.md
- content/payments/methods/wallet/paypal/payment-flow.md
- content/payments/methods/wallet/wechatpay/payment-flow.md
> DOCS-2778: Update payment flow step 1

- content/payments/integrations/ecommerce-platforms/magento2/faq/support-for-vue-storefront.md
> DOCS-2770: Document support for Vue Storefront

- content/payments/methods/banks/trustpay/payment-flow.md
> DOCS-2780: Fix TrustPay payment flow

- content/payments/methods/banks/trustpay/payment-flow.md
> DOCS-2780-2: Remove old content

- content/payments/methods/banks/ing-home-pay/payment-flow.md
> DOCS-2782: Fix ING Home Pay payment flow

- content/account/api-onboarding/_index.md
> DOCS-2774: Hide FAQ buttons in Affiliate onboarding

- config.toml
> DOCS-2801: Remove Boost your integration from Payments ToC

- content/payments/integrations/ecommerce-platforms/prestashop-1-6/_index.md
> DOCS-2808: Prestashop 1.6 support

- layouts/_default/baseof.html
- layouts/partials/meta/opengraph.html
> DOCS-2826: Make canonical URLs relative

- content/api/payment_methods/post-order-edenred.md
> DOCS-2840: Fix typo in Edenred API example

- content/payments/methods/credit-and-debit-cards/cartes-bancaires/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/dankort/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/vpay/integration-and-testing.md
> DOCS-2599: Cross-ref generic gateways in Cartes Bancaires

- content/payments/integrations/ecommerce-platforms/magento1/faq/supported-checkouts.md
- content/payments/integrations/ecommerce-platforms/magento2/faq/supported-checkouts.md
- content/payments/integrations/ecommerce-platforms/magento2/old/faq/supported-magento2-checkouts.md
> DOCS-1777: Clarify testing OneStepCheckout with Magento plugins

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
> DOCS-2198: update paypal test details

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/pay-later/afterpay/integration-and-testing.md
- content/payments/methods/pay-later/in3/integration-and-testing.md
- content/payments/methods/pay-later/klarna/integration-and-testing.md
> DOCS-2153: Update  Klarna and AfterPay testing instructions

- content/payments/methods/banks/bank-transfer/product-rules.md
- content/payments/methods/banks/belfius/product-rules.md
- content/payments/methods/banks/ideal/product-rules.md
- content/payments/methods/banks/ing-home-pay/product-rules.md
- content/payments/methods/banks/request-to-pay/product-rules.md
- content/payments/methods/banks/sepa-direct-debit/product-rules.md
- content/payments/methods/banks/sofort/product-rules.md
- content/payments/methods/pay-later/afterpay/product-rules.md
- content/payments/methods/pay-later/e-invoicing/product-rules.md
- content/payments/methods/pay-later/in3/product-rules.md
- content/payments/methods/pay-later/klarna/product-rules.md
- content/payments/methods/pay-later/pay-after-delivery/product-rules.md
- content/payments/methods/wallet/alipay/product-rules.md
- content/payments/methods/wallet/applepay/product-rules.md
- content/payments/methods/wallet/paypal/product-rules.md
DOCS-2841: fix ing home pay
- Tested
> DOCS-2841: correct payment method page API links

- layouts/_default/baseof.html
> DOCS-2843: Remove tracking

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/banks/bank-transfer/integration-and-testing.md
- content/payments/methods/banks/bank-transfer/product-rules.md
DOCS-2449: detail bank transfer direct api request testing limitations
- Tested
> DOCS-2449: update IBAN testing details for bank transfer

- content/_index.md
- layouts/index.html
- layouts/partials/buttons-homepage.html
Change the partial from blocklist to buttons-homepage.
The buttons on the homepage are now hardcoded, including:
- Title
- Description
- Icon
- URL
- Tested
> DOCS-2409: Change buttons of homepage

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/banks/bank-transfer/integration-and-testing.md
> DOCS-2449: change bank transfer expiration from 5 minutes to days

- content/payments/methods/wallet/googlepay/direct-integration/_index.md
- content/payments/methods/wallet/googlepay/integration-and-testing.md
- content/payments/methods/wallet/googlepay/payment-flow.md
- content/payments/methods/wallet/googlepay/product-rules.md
> Googlepay review dmitry

- content/payments/methods/banks/request-to-pay/_index.md
> DOCS-2849: Add note about Request to Pay availability

- content/payments/methods/wallet/applepay/activation.md
> DOCS-0000: Tech edit Apple Pay activation

- content/payments/methods/wallet/googlepay/_index.md
- content/payments/methods/wallet/googlepay/activation.md
- content/payments/methods/wallet/googlepay/direct-integration/_index.md
- content/payments/methods/wallet/googlepay/integration-and-testing.md
- content/payments/methods/wallet/googlepay/product-rules.md
> DOCS-2855: Fran linguistic review

- content/api/orders/refund-order.md
- content/api/orders/refund-with-shopping-cart.md
- content/payments/refunds-and-chargebacks/refunds/_index.md
> DOCS-0000: Update refunds page

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/banks/bank-transfer/integration-and-testing.md
- content/payments/methods/banks/belfius/integration-and-testing.md
- content/payments/methods/banks/cbc-kbc/integration-and-testing.md
- content/payments/methods/banks/dotpay/integration-and-testing.md
- content/payments/methods/banks/eps/integration-and-testing.md
- content/payments/methods/banks/giropay/integration-and-testing.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
> DOCS-2844: update belfius cbc kbc dotpay eps giropay testing details

- content/api/payment_methods/post-order-postepay.md
- content/api/payment_methods/post-order-request-to-pay.md
- content/api/payment_methods/post-order-santander.md
- content/api/payment_methods/post-order-sepa.md
- content/api/payment_methods/post-order-sofort.md
- content/api/payment_methods/post-order-trustly.md
- content/api/payment_methods/post-order-wechatpay.md
- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/banks/bancontact/integration-and-testing.md
- content/payments/methods/banks/bank-transfer/integration-and-testing.md
- content/payments/methods/banks/ideal/integration-and-testing.md
- content/payments/methods/banks/trustpay/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/visa/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/vpay/_index.md
- content/payments/methods/credit-and-debit-cards/vpay/activation.md
- content/payments/methods/credit-and-debit-cards/vpay/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/vpay/product-rules.md
- content/payments/methods/prepaid-cards/postepay/integration-and-testing.md
- content/payments/methods/prepaid-cards/postepay/product-rules.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
> DOCS-2055: update bancontact postepay visa vpay testing details

- layouts/partials/buttons-homepage.html
> Change buttons on homepage

- content/payments/checkout/payment-pages/deprecated-payment-page.md
- content/payments/checkout/payment-pages/displaying-all-payment-methods.md
- content/payments/checkout/payment-pages/hiding-VAT-amounts.md
- content/payments/checkout/payment-pages/hiding-shopping-cart.md
> DOCS-2317: Add Hiding shopping cart details

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/banks/bancontact/integration-and-testing.md
- content/payments/methods/banks/belfius/integration-and-testing.md
- content/payments/methods/banks/cbc-kbc/integration-and-testing.md
- content/payments/methods/banks/dotpay/integration-and-testing.md
- content/payments/methods/banks/eps/integration-and-testing.md
- content/payments/methods/banks/giropay/integration-and-testing.md
- content/payments/methods/banks/ideal/integration-and-testing.md
- content/payments/methods/banks/ing-home-pay/integration-and-testing.md
- content/payments/methods/banks/request-to-pay/integration-and-testing.md
- content/payments/methods/banks/sepa-direct-debit/integration-and-testing.md
- content/payments/methods/banks/sofort/integration-and-testing.md
- content/payments/methods/banks/trustly/integration-and-testing.md
- content/payments/methods/banks/trustpay/integration-and-testing.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
> DOCS-2844: iDEAL, ING Home Pay, Request to Pay, Sofort, Trustly, TrustPay testing details

- content/payments/methods/pay-later/klarna/activation.md
- content/payments/methods/pay-later/klarna/integration-and-testing.md
> DOCS-2864: Clarify Klarna activation and integration

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/credit-and-debit-cards/american-express/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/product-rules.md
- content/payments/methods/credit-and-debit-cards/dankort/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/dankort/product-rules.md
- content/payments/methods/credit-and-debit-cards/maestro/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/mastercard/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/visa/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/vpay/integration-and-testing.md
> DOCS-2846: update american express cartes bancaires dankort maestro mastercard visa testing details

- content/payments/integrations/ecommerce-platforms/magento2/faq/custom-order-totals.md
@Stanislau-MultiSafepay Please check if information is correct
@FrancescaCook Please check for spelling and grammar improvements
> PLGMAG2V2-301: Add Magento 2 custom totals FAQ

- content/payments/methods/banks/sepa-direct-debit/payment-flow.md
> DOCS-2867: update sepa direct debit settlement times

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/prepaid-cards/edenred/Integration-and-testing.md
- content/payments/methods/prepaid-cards/gift-cards/integration-and-testing.md
- content/payments/methods/prepaid-cards/postepay/integration-and-testing.md
> DOCS-2847: update prepaid cards testing details

- content/payments/integrations/ecommerce-platforms/ccvshop/_index.md
> DOCS-1972: Update CCV Shop payment methods

- content/account/manage-your-balance/viewing-your-uncleared-balance.md
- content/api/orders/adjust-payment-link-lifetime.md
- content/api/orders/apply-dynamic-template.md
- content/payments/checkout/payment-pages/deprecated-payment-page.md
- content/payments/features/second-chance/_index.md
- content/payments/integrations/ecommerce-platforms/craftcommerce/_index.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/_index.md
- content/payments/integrations/ecommerce-platforms/lightspeed_app/lightspeed_core/faq/supported-payment-methods-.md
- content/payments/integrations/ecommerce-platforms/logic4/_index.md
- content/payments/integrations/ecommerce-platforms/magento1/_index.md
- content/payments/integrations/ecommerce-platforms/magento1/faq/processing-refunds.md
- content/payments/integrations/ecommerce-platforms/magento2/_index.md
- content/payments/integrations/ecommerce-platforms/magento2/old/faq/available-payment-methods-magento2.md
- content/payments/integrations/ecommerce-platforms/odoo/_index.md
- content/payments/integrations/ecommerce-platforms/opencart/_index.md
- content/payments/integrations/ecommerce-platforms/opencart/faq/configuring-generic-gateways.md
- content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
- content/payments/integrations/ecommerce-platforms/shopware5/_index.md
- content/payments/integrations/ecommerce-platforms/shopware6/_index.md
- content/payments/integrations/ecommerce-platforms/woocommerce/_index.md
- content/payments/integrations/ecommerce-platforms/woocommerce/faq/configuring-generic-gateways.md
- content/payments/integrations/ecommerce-platforms/woocommerce/faq/processing-refunds.md
- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/credit-and-debit-cards/user-guide/evaluating-uncleared-transactions.md
- content/payments/methods/pay-later/_index.md
- content/payments/methods/pay-later/in3/_index.md
- content/payments/methods/pay-later/in3/integration-and-testing.md
- content/payments/methods/pay-later/in3/product-rules.md
- content/payments/refunds-and-chargebacks/refunds/_index.md
> DOCS-1738: Pay later methods

- content/api/orders/split-payments.md
- content/payments/features/split-payments/_index.md
> Docs 2862: Update Split payments

- content/api/orders/3d-enabled-request.md
- content/api/orders/non-3d-request.md
- content/api/orders/server-to-server-credit-cards.md
- content/api/reference/payment-methods-object.md
> DOCS-2871: Clarify server to server card expiry date format

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/wallet/alipay/integration-and-testing.md
- content/payments/methods/wallet/applepay/integration-and-testing.md
- content/payments/methods/wallet/wechatpay/integration-and-testing.md
> DOCS-2847: update wallet testing details

- content/payments/integrations/ecommerce-platforms/magento2/_index.md
> DOCS-2868: Update Magento 2 payment methods

- content/developer/general/adding-spf-dns-records.md
> DOCS-2853: Clarify SPF records

- content/payments/methods/banks/sepa-direct-debit/activation.md
> DOCS-2869: Fix SEPA Direct Debit activation

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
> DOCS-2198: update paypal test scenarios

- content/payments/about-payments/MultiSafepay-statuses.md
- content/payments/features/server-to-server/payment-flow.md
- content/payments/methods/banks/sepa-direct-debit/payment-flow.md
- content/payments/methods/credit-and-debit-cards/american-express/payment-flow.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/payment-flow.md
- content/payments/methods/credit-and-debit-cards/dankort/payment-flow.md
- content/payments/methods/credit-and-debit-cards/maestro/payment-flow.md
- content/payments/methods/credit-and-debit-cards/mastercard/payment-flow.md
- content/payments/methods/credit-and-debit-cards/visa/payment-flow.md
- content/payments/methods/credit-and-debit-cards/vpay/payment-flow.md
- content/payments/methods/wallet/applepay/payment-flow.md
- content/payments/methods/wallet/googlepay/payment-flow.md
> DOCS-2880: Remove chargeback status

- content/payments/methods/pay-later/klarna/payment-flow.md
> DOCS-2886: Clarify declined Klarna orders

- content/payments/integrations/testing/test-payment-details.md
- content/payments/methods/banks/belfius/integration-and-testing.md
- content/payments/methods/banks/cbc-kbc/integration-and-testing.md
- content/payments/methods/banks/dotpay/integration-and-testing.md
> DOCS-2844: add cancellation steps for bank methods testing details

- content/payments/features/recurring-payments/_index.md
> Diagram recurring payments

- content/payments/integrations/ecommerce-platforms/shopware6/_index.md
> Release of Shopware6 2.5.2

- content/payments/methods/banks/ing-home-pay/_index.md
> DOCS-2889: Add notice about discontinuing ING Home Pay

- content/account/manage-your-balance/enabling-converting-currencies.md
- content/account/manage-your-balance/making-payouts.md
> DOCS-2882-2: Add zero decimal note to JPY

- content/payments/methods/banks/sepa-direct-debit/product-rules.md
- content/payments/refunds-and-chargebacks/chargebacks/about-chargebacks.md
> DOCS-2873: SEPA refund risks

- content/payments/methods/banks/ing-home-pay/_index.md
> DOCS-2891: Add instructions for stopping ING HomePay

- content/payments/methods/wallet/paypal/activation.md
> DOCS-2874: Update PayPal language encoding

- content/api/orders/payment-component-order.md
> Add IP address recommendation to Payment Component API request

- content/payments/methods/banks/ing-home-pay/_index.md
> DOCS-2893: Redirect ING sub-pages

- content/account/partner-account/creating-partner-account.md
> Add link to create test partner account

- content/api/orders/recurring-payments-initial.md
- content/api/orders/recurring-payments-orders.md
- content/api/orders/recurring-payments-subsequent.md
- content/api/reference/customer-object.md
> Clarify recurring payments API reference

- content/developer/general/generic-gateways.md
- content/payments/methods/prepaid-cards/gift-cards/user-guide/creating-custom-gift-cards.md
> DOCS-1903: Clarify generic gateways for gift cards

- content/account/manage-your-balance/making-payouts.md
> DOCS-2611: Clarify bank holidays

- content/payments/methods/pay-later/klarna/user-guide/handling-disputes.md
> Docs 2858: Document Klarna Disputes app

- content/payments/integrations/ready-made/prestashop-1-7/_index.md
Release of 5.1.1 PrestaShop plugin
> Release of 5.1.1 PrestaShop plugin 

- content/payments/methods/banks/request-to-pay/_index.md
- content/payments/methods/banks/request-to-pay/payment-flow.md
> DOCS-2898: Clarify RtP is a collecting payment method

- content/payments/methods/banks/ideal/overview.md
> DOCS-2903: Restore iDEAL QR content

- content/payments/methods/banks/bancontact/integration-and-testing.md
- content/payments/methods/banks/bank-transfer/integration-and-testing.md
- content/payments/methods/banks/belfius/integration-and-testing.md
- content/payments/methods/banks/eps/integration-and-testing.md
- content/payments/methods/banks/giropay/integration-and-testing.md
- content/payments/methods/banks/ideal/integration-and-testing.md
- content/payments/methods/banks/request-to-pay/integration-and-testing.md
- content/payments/methods/banks/sepa-direct-debit/integration-and-testing.md
- content/payments/methods/banks/sofort/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/american-express/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/cartes-bancaires/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/dankort/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/maestro/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/mastercard/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/postepay/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/visa/integration-and-testing.md
- content/payments/methods/credit-and-debit-cards/vpay/integration-and-testing.md
- content/payments/methods/pay-later/betaalpermaand/integration-and-testing.md
- content/payments/methods/pay-later/e-invoicing/integration-and-testing.md
- content/payments/methods/pay-later/klarna/integration-and-testing.md
- content/payments/methods/pay-later/pay-after-delivery/integration-and-testing.md
- content/payments/methods/prepaid-cards/gift-cards/integration-and-testing.md
- content/payments/methods/wallet/alipay/integration-and-testing.md
- content/payments/methods/wallet/applepay/integration-and-testing.md
- content/payments/methods/wallet/googlepay/integration-and-testing.md
- content/payments/methods/wallet/paypal/integration-and-testing.md
- content/payments/refunds-and-chargebacks/refunds/full-partial-refunds.md
> DOCS-2905: Update ready-made integrations URL

- content/payments/methods/wallet/paypal/activation.md
> DOCS-2906: Remove e.g. on PayPal activation

- content/developer/api/locale-parameter.md
> DOCS-2779: Provide example locale parameter values

- content/api/orders/cancel-order.md
- content/integration-team/connectjs.md
- content/integration/ready-made/magento1/changelog.md
- content/payments/methods/wallet/applepay/integration-and-testing.md
> DOCS-2769: Remove references to pretransactions

- content/integration-team/integration-review-eng.md
- content/integration-team/integration-review-nl.md
> DOCS-2909: Remove Berend from Integration Team list

- content/my-account/partner-account/creating-affiliate-accounts.md
> DOCS-2908: Fix API onboarding link

- content/payments/methods/wallet/googlepay/_index.md
- content/payments/methods/wallet/googlepay/activation.md
- content/payments/methods/wallet/googlepay/direct-integration/_index.md
- content/payments/methods/wallet/googlepay/integration-and-testing.md
- content/payments/methods/wallet/googlepay/overview.md
- content/payments/methods/wallet/googlepay/payment-flow.md
> Update Google Pay documentation

- content/payments/methods/banks/bank-transfer/user-guide/unmatched-payments-dutch.md
- content/payments/methods/banks/bank-transfer/user-guide/unmatched-payments-german.md
- content/payments/methods/banks/bank-transfer/user-guide/unmatched-payments.md
> DOCS-2861-3: Small fix

- content/developer/general/multisafepay-gateway.md
- content/integration/ready-made/ccvshop/_index.md
- content/integration/ready-made/craftcommerce/_index.md
- content/integration/ready-made/cs-cart/_index.md
- content/integration/ready-made/drupal7/_index.md
- content/integration/ready-made/drupal8/_index.md
- content/integration/ready-made/magento1/_index.md
- content/integration/ready-made/magento2/_index.md
- content/integration/ready-made/odoo/_index.md
- content/integration/ready-made/opencart/_index.md
- content/integration/ready-made/oscommerce/_index.md
- content/integration/ready-made/prestashop-1-6/_index.md
- content/integration/ready-made/prestashop-1-7/_index.md
- content/integration/ready-made/scandipwa/manual.md
- content/integration/ready-made/shopware5/_index.md
- content/integration/ready-made/shopware6/_index.md
- content/integration/ready-made/virtuemart/_index.md
- content/integration/ready-made/woocommerce/_index.md
- content/integration/ready-made/x-cart/_index.md
- content/integration/ready-made/zencart/_index.md
> DOCS-1995: Document MultiSafepay gateway

- content/developer/general/logos-and-icons.md
- content/payments/about-payments/displaying-payment-method-logos.md
> DOCS-2915: Document payment logo designer

- content/api/orders/create-redirect-order.md
> Add gateway options to redirect order API reference

- content/payments/methods/pay-later/pay-after-delivery/overview.md
- content/payments/methods/pay-later/pay-after-delivery/payment-flow.md
- content/payments/methods/pay-later/pay-after-delivery/user-guide/closing-transactions.md
- content/payments/methods/pay-later/pay-after-delivery/user-guide/refunds-discounts.md
> DOCS-2921: Clarify closing PAD transactions

- content/integration/ready-made/magento1/_index.md
> DOCS-2922: Fix Magento 1 change log link

- content/integration-team/integration-review-eng.md
- content/integration/ready-made/opencart/_index.md
> DOCS-2918: Add Opencart preview

- content/integration/ready-made/magento1/_index.md
> DOCS-2925: Remove Magento 1 changelog

- content/integration/ready-made/prestashop-1-7/faq/enabling-recurring-payments.md
> DOCS-2924: Update PrestaShop 1.7 recurring payments instructions
