layouts/_default/single.html
=> DOCS-791: mobile intergration pages are now full width

layouts/_default/baseof.html, layouts/api/list.html, static/css/main.css
=> DOCS-802: updated styling for allow wordbreaks in urls

layouts/404.html, static/css/main.css
=> DOCS-834: Added 404 styling

static/css/api.css
=> DOCS-828: language-shell-white-space

content/api/orders/patch_order.md, content/api/orders/post_order_direct.md, content/api/orders/post_order_recurring.md, static/css/api.css
=> DOCS-844: added auto layout tables

layouts/partials/edit-page.html
=> DOCS-1098: trim feedback url suffix only

content/integrations/plugins/magento2/faq/payment-fee-surcharges.md, content/integrations/plugins/magento2/faq/refunding-magento2.md
=> DOCS-1141: Refund not possible if Fooman surcharge is used

content/integrations/plugins/magento2/manual.md
=> DOCS-1423: duplicated magento2 text fix

content/faq/api/difference-between-status-and-transaction-status.md
=> DOCS-1548: fixed-grammar-mistake

content/integrations/plugins/craftcommerce/faq/available-payment-methods-craft-commerce.md, content/integrations/plugins/cs-cart/faq/available-payment-methods-cs-cart.md, content/integrations/plugins/drupal7/faq/available-payment-methods-drupal.md, content/integrations/plugins/drupal8/faq/available-payment-methods-drupal8.md, content/integrations/plugins/magento1/faq/available-payment-methods-magento1.md, content/integrations/plugins/magento2/faq/available-payment-methods-magento2.md, content/integrations/plugins/opencart/faq/available-payment-methods-opencart.md, content/integrations/plugins/oscommerce/faq/available-payment-methods-oscommerce.md, content/integrations/plugins/prestashop-1-6/faq/available-payment-methods-prestashop.md, content/integrations/plugins/prestashop-1-7/faq/available-payment-methods-prestashop.md, content/integrations/plugins/shopware5/faq/available-payment-methods-shopware5.md, content/integrations/plugins/shopware6/faq/available-payment-methods-shopware6.md, content/integrations/plugins/virtuemart/faq/available-payment-methods-virtuemart.md, content/integrations/plugins/woocommerce/faq/available-payment-methods-woocommerce.md, content/integrations/plugins/x-cart/faq/available-payment-methods-x-cart.md, content/integrations/plugins/zencart/faq/available-payment-methods-zen-cart.md
=> DOCS-1604: V Pay spelling correction across DOCS

layouts/partials/footer.html
=> DOCS-1388: added-link-github-footer

layouts/partials/menu.html
Contact page of main domain was changed. The contact-form is now nested.
In order to prevent users from looping between docs and contact,
the hyperlink on the 'Contact' button is changed from
https://www.multisafepay.com/contact to
https://www.multisafepay.com/contact/merchant-support
Signed-off-by: Kris Stallenberg <kris@MacBook-Pro-2.local>
- Paths are …
=> DOCS-1664: Changed hyperlink on 'Contact' button in sidebar

content/integrations/wrappers/_index.md
The field meta_title in file _index.md said 'Wrapper & SDA integration[...]'
Changed the field to 'Wrapper & SDK integration[...]'
Signed-off-by: Kris-MultiSafepay <kris@MacBook-Pro-2.local>
- …
=> DOCS-1665: Fixed typo in meta_title

layouts/_default/baseof.html, layouts/_default/faqdetail.html, layouts/_default/faqplugins.html, layouts/_default/paymentdetail.html, layouts/_default/single-beta-button.html, layouts/_default/single.html
=> DOCS-1615: added-feedback-lang-block-everywhere

content/integrations/plugins/odoo/_index.md, content/integrations/plugins/odoo/manual.md
For some reason the _index file in content/integrations/plugins/odoo
had a different lay-out causing it to be displayed incorrectly.
Additionally removed some trailing empty lines.
- Use single quotation marks in …
=> DOCS-1709: Fix Odoo Plugin page

content/api/payment_methods/post_order_in3.md, content/faq/general/where-find-logo-payment-methods.md, content/how-to-find-us/_index.md, content/how-to-find-us/amsterdam-office-location.md, content/how-to-find-us/malaga-office-location.md, content/integrations/accounting and bookkeeping/Snelstart reconciliation plugins by Premarc/_index.md, content/integrations/accounting and bookkeeping/Snelstart/_index.md, content/integrations/community/Community integration requirements/_index.md, content/integrations/hosted/lightspeed_app/faq/available-payment-methods-lightspeed.md, content/integrations/hosted/lightspeed_app/faq/change-environment.md, content/integrations/hosted/lightspeed_app/faq/disable-payment-methods.md, content/integrations/hosted/lightspeed_app/faq/inline-buy-button.md, content/integrations/hosted/lightspeed_app/faq/inline-news-letter.md, content/integrations/hosted/lightspeed_app/faq/lightspeed-orderid.md, content/integrations/hosted/lightspeed_app/faq/maximal-order-amount.md, content/integrations/hosted/lightspeed_app/faq/migrate-to-app.md, content/integrations/hosted/lightspeed_app/faq/minimal-order-amount.md, content/integrations/hosted/lightspeed_app/faq/order-payment-methods.md, content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md, content/integrations/hosted/lightspeed_app/faq/shop_id.md, content/payment-methods/billing-suite/in3/_index.md, content/payment-methods/billing-suite/in3/activate-in3.md, content/payment-methods/billing-suite/in3/how-does-in3-work.md, content/payment-methods/billing-suite/in3/in3-testing.md, content/payment-methods/billing-suite/in3/refund-in3.md, content/payment-methods/billing-suite/in3/what-is-in3.md, content/tools/reports/N-codes.md
Changed 27 more metatitles using the regex expression:
meta_title:(?!.*MultiSafepay Docs)
to find all meta_title suffixes that didn't match "- MultiSafepay Docs"
It seems like homepage is last page with different suffix as it uses:
"| MultiSafepay Docs". I can't find where this title is generated as it's
not listed in a markdown file, but probably a hugo config.
- Use bullets for numerations where the sort order doesn't matter. For chronological order, …
=> DOCS-1714: Uniform meta_titles

content/_index.md, content/faq/_index.md, content/how-to-find-us/_index.md, content/integration-team/_index.md, content/payment-methods/_index.md, content/tools/_index.md
Some _index pages have missing meta_title fields, causing automatically
generated html titles with suffix "| MultiSafepay". To prevent this,
explicit meta_titles must be created.
- Use single quotation marks in your …
=> DOCS-1732: Uniform meta_titles

content/payment-methods/billing-suite/in3/_index.md
Metatitle contained double suffix "In3 - MultiSafepay Documentation Center -
MultiSafepay Docs". This was generated in bulk rename. Delete first suffix.
- Use single quotation marks in your Markdown code (example …
=> DOCS-1759: Fix in3 meta_title

content/faq/api/how-does-the-notification-url-work.md
=> DOCS-1426b: added_blank_space

static/css/main.css
Problem lies in CSS. The updated CSS is in github repo, but not on server.
Hence the responsive rules do not apply. Made tiny typo fix to see if this will
override main.css on server.
- Use single quotation marks in …
=> DOCS-1771: Fix SCA Diagram

.github/mlc_config.json, .github/workflows/markdown-link-check.yml
=> DOCS-473: Add markdown-link-check to Github Actions

content/integrations/plugins/magento2/faq/payment-links-in-order-confirmation-for-backend-orders.md
=> DOCS: Add payment_link variable information for Magento 2 e-mail templates

content/integrations/plugins/magento2/manual.md, layouts/_default/baseof.html, layouts/_default/single-old-button.html, layouts/_default/single.html
=> DOCS-2064: Apply copy code button throughout docs

content/tools/credit-card-component/_index.md
=> DOCS-2098: Add preOrder documentation to Credit Card Component

content/payment-methods/billing-suite/e-invoicing/how-does-e-invoicing-work.md
=> DOCS-2042: Fix syntax @DUE_DATE@

content/integrations/ecommerce integrations/opencart/faq/_index.md, content/integrations/ecommerce integrations/woocommerce/faq/_index.md
=> DOCS-2118: Add alias for OpenCart and WooCommerce FAQ index page

content/integrations/ecommerce integrations/magento2/manual.md, layouts/_default/baseof.html, layouts/shortcodes/blue-notice.html, static/css/main.css
=> DOCS-2138: Add blue-notice shortcode for Magento 2 blogpost

content/tools/multisafepay-control/set-your-notification-url.md
Since WooCommerce plugin version 4.X.X the notification url in WooCommerce is dynamic and follow this format: 
[https://example.com/wc-api/multisafepay_{ID-OF-PAYMENT-METHOD}?transactionid={ORDER-NUMBER}&timestamp={TIME-STAMP}
Is hard to explain this in just a line, and that`s why I am changing the information to contact support team in case a merchant need it; in the same way other integrations do.
=> DOCS-2152: Remove notification URL for WooCommerce

content/tools/transactions-api-endpoint/_index.md
Two new query parameters have been added to the transactions endpoint.
The following changes have been made in the documentation:
- Completed_from is documented under parameters
- Completed_until is documented under parameters
- Start is renamed into created_from
- End is renamed into created_until
- Created_from and created_until can both be specified either as Unix time or ISO-8601
- 'Payout specification' usecase is deleted, as it wasn't working and duplicated reconciliation
- Mentions of 'end' and 'start' are removed from text
- Reconciliation use case is updated with new parameters
- The terminology used must …
=> DOCS-2177: Add completed_from and completed_until

content/integrations/ecommerce-integrations/magento2/manual.md
=> DOCS: Remove double line about deprecated plugin FAQ on the M2 Manual Page

content/api/payment_methods/post-order-einvoicing.md, content/api/payment_methods/post-order-klarna.md, content/api/payment_methods/post-order-payafter.md, content/api/payment_methods/post_order_afterpay.md
Previous branch had merge conflicts.
- When renaming or deleting a page, add an alias of the deprecated URL to …
=> DOCS-1998: Move shopping_cart notice for PAD in API reference

content/integrations/ecommerce-integrations/woocommerce/faq/configuring-generic-gateways.md
There was a typo in the texts of the generic gateway, within the WooCommerce section.  Also change a little bit the format.
=> DOCS-2446: Fix typos in WooCommerce generic gateway FAQ item texts

content/api/transactions/create_refund_pad.md
=> DOCS-2534: Clarify API refund is for post-payment methods

content/payments/methods/billing-suite/afterpay/activation.md
=> DOCS-2612: Add LightSpeed to AfterPay Activation

content/payments/integrations/ecommerce-platforms/ccvshop/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/craftcommerce/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/cs-cart/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/drupal7/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/drupal8/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/ecwid/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/lightspeed_app/lightspeed_core/faq/supported-payment-methods-.md, content/payments/integrations/ecommerce-platforms/logic4/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/logivert/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/magento1/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/magento2/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/magento2/old/faq/available-payment-methods-magento2.md, content/payments/integrations/ecommerce-platforms/mijnwebwinkel/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/myshop/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/odoo/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/opencart/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/oscommerce/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/prestashop-1-6/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/prestashop-1-7/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/shopify/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/shopware5/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/shopware6/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/virtuemart/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/woocommerce/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/x-cart/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/zencart/faq/supported-payment-methods.md, content/payments/integrations/ecommerce-platforms/zilvercms/faq/supported-payment-methods.md
=> DOCS-2710: Remove SEPA from Shopify payment methods

layouts/shortcodes/details.html
To link to a <details> element with title="Foo":
[Text with hyperlink](#details-foo)
Note how the title is converted to lowercase.
- Tested
=> Make <details> elements anchor-linkable

content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
This PR updates the CHANGELOG link and GitHub repository link for the PrestaShop plugin.
=> PRES-279: Update CHANGELOG and GitHub links to new repository

content/payments/integrations/ready-made/lightspeed_app/faq/synchronizing-payment-links.md
Hi,
The second part can be removed from lightspeed_app/faq/synchronizing-payment-links.md
=> DOCS: remove sync part lightspeed

content/integration/ready-made/prestashop-1-6/_index.md
It seems this was fixed a couple of days ago in #1874.
Not sure why the links are broken again, perhaps the directory structure changed since then.
It has been reported to me by a user who requires to download the module.
=> DOCS-2912: Fix broken download and changelog links in PrestaShop 1.6

content/integration/ready-made/opencart/faq/supported-checkouts-themes.md
This PR declare support of our extension with AJAX Quick Checkout (a third party plugin which provides a different  experience of the checkout within OpenCart webshops).  Previously was tested only on the free version of this plugin. Now we know are supporting both of them.
=> PLGOPNS-438: Declare support for paid version of AJAX Quick Checkout

content/integration/ready-made/woocommerce/_index.md
This PR change the download link according with the release of 4.11.0 WooCommerce plugin.
=> Release of 4.11.0 WooCommerce plugin

content/integration/ready-made/woocommerce/faq/activating-payment-component.md
This PR introduce a new WooCommerce FAQ item about how to enable the payment component within the Credit Card gateway settings page.
=> DOCS-2931: FAQ item about Payment Component within WooCommerce

content/integration/ready-made/prestashop-1-7/_index.md
This PR changes the download link of PrestaShop 1.7 plugin.
=> Release of 5.2.0 PrestaShop plugin

content/integration/ready-made/woocommerce/_index.md
Change download link according for the just released version 4.13.0 of WooCommerce plugin
=> Release of 4.13.0 WooCommerce plugin

content/integration/ready-made/magento2/_index.md, content/integration/ready-made/magento2/faq/features-of-latest-release.md
As of version 2.15, PWA REST endpoints are back in the plugin, because of high demand. Therefore, I removed it from the features that are no longer available.
This task was initially created to describe which MultiSafepay statuses can now be coupled to Magento order statuses.
=> PLGMAG2V2-431: Add info about setting custom order status

content/integration/ready-made/opencart/_index.md
This PR changes a little bit the requirements of the OpenCart plugin, to declare PHP versions supported
=> DOCS-3242: Adjustment in OpenCart PHP version requirement

content/integration/ready-made/shopware6/faq/enabling-recurring-payments.md
Since the new release of the Shopware 6 (2.6.0) plugin, we have moved the tokenizations (and the newly created payment component) setting to the gateway level to enable it individually. Therefore this change.
_sidenote: Since this update. Merchants have to re-enable tokenization on the gateway level. This is mentioned in the changelog on github_
=> Update recurring payments for release 2.6.0

content/integration/ready-made/woocommerce/_index.md
This PR changes the download link of the WooCommerce plugin.
=> Release of WooCommerce Plugin 4.15.0

content/integration/ready-made/prestashop-1-7/_index.md
This PR change the download link of PrestaShop 1.7 plugin.
=> PRES-338: Release of PrestaShop 1.7 (v. 5.5.0) plugin

content/payment-methods/google-pay-integration.md
=> DOCS-3491: fix Google Pay token location in payment data response

content/integrations/woocommerce.md
This PR:
- Changes the download link of the WooCommerce repository according a new release.
- Remove the installation instructions via Wordpress.org plugin directory, because it has been temporarily removed, after they report there is a probable security problem in the code. We are waiting for their response and hopefully in a shortest time, we can be back to the Wordpress plugin directory.
=> Release of WooCommerce Plugin 4.16.0 

content/integrations/woocommerce.md
This PR: 
- Update the download link according new release. 
- Restore the instructions to install the plugin via Wordpress backend.
=> Release of WooCommerce Plugin 4.17.2

content/integrations/prestashop-1-7.md
This PR: 
Update the download link of the PrestaShop 1.7 plugin according a new release.
=> PRES-353: Release of 5.6.2 of the PrestaShop 1.7 plugin

content/integrations/cs-cart.md
Adding the right URL to download our plugin from Docs for Release 1.6.2
=> PLGCSCS-143: Changing URL to download plugin for release 1.6.2

content/payment-methods/paypal.md
=> DOCS-3882:Clarify how invoice_id is displayed

content/integrations/opencart-4.md
OpenCart 4 launched a version recently with some changes that the integration team needs to cover in the near future.
Because of this, we need to be more specific about the version of Opencart 4 compatible with our plugin and to change the more generalist OpenCart 4.x to 4.0.1.x
=> DOCS-3895: Changing the supported version of OpenCart 4

content/integrations/virtuemart-4.md
As we have released VirtueMart 4 - Version 1.0.1, the URL to download it needs to be changed.
=> PLGVIR4-43: Changing the URL of VirtueMart 4 plugin [Release 1.0.1]

content/integrations/prestashop-1-6.md
This PR updates the download link of the PrestaShop 1.6 plugin according to a new release.
=> PLGPRSS-493: Release of the 3.10.5 of the PrestaShop 1.6 plugin

content/integrations/woocommerce.md
This PR updates the download link, and instead of pointing to the release asset in GitHub, I just changed it to point to the WordPress marketplace. This way is not required to change this page, after each release.
=> PLGWOOS-868: Release of the 5.3.0 of the WooCommerce plugin

content/integrations/shopify-beta.md
This pull request includes an update to the `content/integrations/shopify-beta.md` file to provide clearer guidance on API key usage and environment selection for MultiSafepay payment apps.
Documentation improvements:
* Added a new section explaining that the same API key and selected environment (test or live) will be used across all MultiSafepay payment apps. Any changes to the API key or environment in one app will automatically apply to other active apps associated with the shop.
=> DOCS-4454: Add explanation about API Key setting field to Shopify docs

content/integrations/cs-cart.md
This pull request includes an update to the download link for the CS-Cart plugin in the `content/integrations/cs-cart.md` file. The most important change is the update of the plugin version in the download link.
Update to CS-Cart plugin:
* [`content/integrations/cs-cart.md`](diffhunk://#diff-43c230de9916f1d549d83a8c0ed455196eda916f29dbb87b3e9481dd08696c2bL14-R14): Updated the download link to point to version 1.7.1 of the CS-Cart plugin.
=> DOCS-4479: Release of 1.7.1 of the CS Cart plugin

content/integrations/shopware-6.md
______________________________
**NOTE**:  To provide clearer information about our plugin's compatibility with Shopware 6, we have removed older versions from the documentation.
______________________________
**DESCRIPTION**:
This pull request includes a small update to the `content/integrations/shopware-6.md` file. The changes simplify the prerequisites for Shopware compatibility and testing.
* Updated the Shopware version requirement to only include 6.6.x.x and removed references to older versions.
* Updated the tested versions to include only Shopware 6.6.3.0 and PHP 8.1–8.2.
=> [Shopware 6] - Updating the version compatibility list

content/integrations/cs-cart.md
This pull request includes a minor update to the download link for the CS-Cart plugin in the `content/integrations/cs-cart.md` file.
* Updated the download link to point to version 1.7.2 of the CS-Cart plugin.
=> DOCS-4491: [CS-Cart] Release of 1.7.2

content/integrations/prestashop-1-6.md
This pull request updates the download link for the PrestaShop 1.6 plugin in the documentation to point to the latest version (3.15.0).
* [`content/integrations/prestashop-1-6.md`](diffhunk://#diff-decda0f5c2080fad5aac4227dadbd8bb1849c29dbce398550906ecf24dfd8873L14-R14): Updated the `href` attribute of the download button to reference version 3.15.0 of the PrestaShop 1.6 plugin.
=> DOCS-4623: [PrestaShop 1.6] Release of 3.15.0

content/payment-methods/riverty.md
=> DOCS-4642: Update Riverty Documentation to Not Allow 0% VAT Items

content/integrations/prestashop.md
This pull request updates the download link for the PrestaShop plugin in the `content/integrations/prestashop.md` file to point to the latest version (6.0.1).
=> DOCS-4671: [PrestaShop] Release of 6.0.1
